### ISSUE TITLE
add support to directly link to a Vitessce viewconfig in dataset detail pages if multiple exist

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1000]
Ideally via URL parameter, e.g. `...?vitessce_view=<n>` (where n is the index of the viewconfig in the dropdown).

Could this be handled by updating the URL as soon as the user selects a viewconfig different from the default?

**Comment by mccalluc** [comment]
The URL you get from saving state in vitessce captures the layer dropdown, so I think it's resolved. Closing.
