### ISSUE TITLE
identify and display QC reports for raw and processed data

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1009]
We propose to use the manifest files that are currently used to annotate the pipeline outputs to identify QC reports among the pipeline-generated files and do the same for uploaded data sets by introducing manifests for them as well. This will be also need to be addressed in the context of validating the file listing/directory structure for uploaded datasets (somewhat related to https://github.com/hubmapconsortium/ingest-validation-tools/issues/346).

Once we can identify QC reports among the data files associated with a dataset and these reports being available through the Assets API, we can list them in a separate section of the dataset detail pages. 

Solution for #1006. Supersedes #23.

**Comment by mccalluc** [comment]
Design: #1241
