### ISSUE TITLE
UX: Full Screen "Esc" button browser interaction with Viewer

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1013]
## Feedback

__Help Desk Issue Tracker URL__: n/a (from Google Form Beta response #3) 

__Message__:
Feedback on escape button function effect on browser vs viewer

"The portal was very much improved since last time. The only issue, which is just an annoyance, is that when I enter full screen on a visualization and try to Esc out of it, my entire browser also exits full screen mode (on a Mac using Safari). I can easily put it back into full screen, but having it not exit full screen mode or having an 'X' on the full screen visualization to exit from it would be nice."

**Comment by mccalluc** [comment]
We might be able to fix this: https://superuser.com/questions/315949/dont-exit-full-screen-when-pressing-escape-in-apps-like-safari-on-lion. Removing Triage, unassigning Tiffany.
