### ISSUE TITLE
UX: control display & control tutorial/overview

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1014]
## Feedback

__Help Desk Issue Tracker URL__: n/a (from Google Form Beta testing response #4) 

__Message__:
UX feedback on number of controls, including responsive hide/show and brief controls tutorial

"Too many controls/options once the screen opens. Hide some or make it appear after click. Give a quick help of all the controls available."

**Comment by mccalluc** [comment]
@pecan88 : Do you know which page they're on? This could be search, or vitessce, or something else...
Clearing "triage".

**Comment by pecan88** [comment]
Not sure - here's the full response which may (or may not) provide some context hints.  We can reach out directly to him for additional information (I will send you ID via Slack in a sec).

What problems did you encounter while using the system?
Too many controls/options once the screen opens. Hide some or make it appear after click. Give a quick help of all the controls available. 

What was missing within the scoped list of features and data?
Would have been nice to have looked at montage and/other tiles and not just 1 tile. Is there a way to download single cell segmentation data? Was not clear. Also, full screen support would be ideal.

**Comment by mccalluc** [comment]
Thanks: I'll follow-up via email, and file new granular issues if needed. See also #1015. closing.
