### ISSUE TITLE
Montage view of more than 1 tile; single cell segmentation download; full screen support

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1015]
## Feedback

__Help Desk Issue Tracker URL__: n/a (Google Forms Beta response no. 4)

__Message__:
Looks like:
1. request to view montage over multiple tiles 
2. can we download single cell segmentation data?  (FYI @mruffalo )
3. request for full screen support

"Would have been nice to have looked at montage and/other tiles and not just 1 tile. Is there a way to download single cell segmentation data? Was not clear. Also, full screen support would be ideal."

**Comment by mccalluc** [comment]
> request to view montage over multiple tiles

(Assuming "montage" means stitching the separate images?)
@ilan-gold : Ilan, can you confirm that this a pipeline issue? Is there a tracking issue?

> can we download single cell segmentation data?

Yes, that is supported, @ilan-gold , can you confirm that it would be under the pull-down in Vitessce? @pecan88 , can you loop back to the user and ask if this this menu does what they need? Maybe they were looking for the information elsewhere?

<img width="119" alt="Screen Shot 2020-08-07 at 11 01 42 AM" src="https://user-images.githubusercontent.com/730388/89659226-93d69480-d89d-11ea-856e-cecb4f15cfe9.png">

> request for full screen support

@pecan88 : Do they really mean full screen, ie, the full window is not sufficient? We have that already, but maybe they didn't see it?

<img width="139" alt="Screen Shot 2020-08-07 at 11 05 17 AM" src="https://user-images.githubusercontent.com/730388/89659611-18c1ae00-d89e-11ea-9932-1b6fb7fcf978.png">
----
Keep this open for now for clarification.

**Comment by ngehlenborg** [comment]
I think they didn't see the buttons.

**Comment by ilan-gold** [comment]
I think @ngehlenborg is right, and the user just missed the buttons.  As far as the "tile view" goes, the answer is stitching.  I am not sure if there is a singular issue for this.  Where should I open one @mccalluc?  Not sure whose responsibility this is or when/where it happens.

**Comment by mccalluc** [comment]
- Put "how/when do we start stitching" on [agenda](https://docs.google.com/document/d/1ZXQ-tRYbnV1mRqFjaeaUxNPnh-6r6RkvHTzOTP3uk40/edit#).
- For the rest, Peter gave me the contact info, so I'll get clarification from user, and point out the buttons.

No other action here -- closing.
