### ISSUE TITLE
Text feedback: dataset Creator, email address display, race display

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1019]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/648/activity

__Message__: 
1 of 3 feedback items from an NIH respondent.

-I would remove the "creator" of the dataset - I don't think it's necessary, and if we leave it there, we're going to have to find a way to disambiguate the names
-I don't think we should have people's email addresses available or they are going to be bombarded with questions
-I think we should remove all mentions of race - both in the filtering columns and in the collections

Full message:

Dear HuBMAP helpdesk

Here are just a few suggestions from me about the Data Portal.  Hopefully they are helpful and make sense.

-I would remove the "creator" of the dataset - I don't think it's necessary, and if we leave it there, we're going to have to find a way to disambiguate the names
-I don't think we should have people's email addresses available or they are going to be bombarded with questions
-I think we should remove all mentions of race - both in the filtering columns and in the collections
-should be able to get to the data from anywhere - if I see that there's RNA-seq data available for something, I would like to be able to click on that and get to the data, not to have to go back and re-find it (**I had this conversation with Deb and Robin, hopefully they can be more specific with this)

-what I would love to see is a button that sorts out data from other consortia.  I think Aaron said that we have HTAN data in there, and I think that the option to show where our data is coming from would be great

If you have any questions, please let me know.

**Comment by mccalluc** [comment]
Put on UI agenda.
