### ISSUE TITLE
Needing to "re-find" data to access for download

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1020]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/648/activity

__Message__: 
2 of 3 feedback items from an NIH respondent.

-should be able to get to the data from anywhere - if I see that there's RNA-seq data available for something, I would like to be able to click on that and get to the data, not to have to go back and re-find it (**I had this conversation with @debnigra and [head of comms & engagement] , hopefully they can be more specific with this)

Full message:

Dear HuBMAP helpdesk

Here are just a few suggestions from me about the Data Portal.  Hopefully they are helpful and make sense.

-I would remove the "creator" of the dataset - I don't think it's necessary, and if we leave it there, we're going to have to find a way to disambiguate the names
-I don't think we should have people's email addresses available or they are going to be bombarded with questions
-I think we should remove all mentions of race - both in the filtering columns and in the collections
-should be able to get to the data from anywhere - if I see that there's RNA-seq data available for something, I would like to be able to click on that and get to the data, not to have to go back and re-find it (**I had this conversation with Deb and Robin, hopefully they can be more specific with this)

-what I would love to see is a button that sorts out data from other consortia.  I think Aaron said that we have HTAN data in there, and I think that the option to show where our data is coming from would be great

If you have any questions, please let me know.

**Comment by mccalluc** [comment]
Put this on UI agenda. Will follow-up if we think we can do anything here.

**Comment by ngehlenborg** [comment]
This could be addressed by having file manifests for uploaded data. Somewhat related to #1009.

**Comment by mccalluc** [comment]
> if I see that there's RNA-seq data available for something, I would like to be able to click on that and get to the data, not to have to go back and re-find it 

When we list individual files, they are now directly downloadable. When we don't list files, the globus link goes to the dataset. In neither case do I think people need to "re-find" the data they want. 

Closing... but please reopen and clarify if I'm reading it wrong.
