### ISSUE TITLE
Heatmap UX, Institution abbreviation, Creator response

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1022]
## Feedback

__Help Desk Issue Tracker URL__: n/a (received via email as part of approval)

__Message__:

3. Are you seeing expected results for pipeline processed data? Are the outputs correct?

Yes for CODEX with above caveats ( suggestion the heatmap functionality is hard to read)

7. Alpha feedback related questions:
a. May we abbreviate group names? (e.g. “Stanford” into “STAN”)

Certainly, for TMC-Florida UF or FL would be appropriate abbreviations.

b. For the “Creator” section for data entries, would you prefer we show the creator name & email, the PI name & email, or both? 

PI necessary, creator optional

Full message:

There are a few comments that do not preclude the above:

1. Are the QC reports related to processed data acceptable?

Yes, they are included with metadata submission for 10x
Yes They are with the CODEX dataset but not the cytokit release set

2. Does the assay data look correct after reviewing a couple of instances of each assay?

Yes IMC
Yes 10x
Yes CODEX (the cytokit release is separate fields of view and not stitched so comparison to AKOYA processed is difficult but overall expected cell types and locations)

3. Are you seeing expected results for pipeline processed data? Are the outputs correct?

Yes for CODEX with above caveats ( suggestion the heatmap functionality is hard to read)
Yes, with caveat for scRNASeq that threshold settings and alignment methods vary so local analyses are not identical.

4. Do the visualizations correctly represent your data?

Yes 10x and CODEX and IMC

5. Are you able to download the data? If you download one and run a local analysis, do you get expected results?

Yes

6. Is the metadata associated with the donors, samples, and assays correct? Does it match your local records?

Yes

7. Alpha feedback related questions:
a. May we abbreviate group names? (e.g. “Stanford” into “STAN”)

Certainly, for TMC-Florida UF or FL would be appropriate abbreviations.

b. For the “Creator” section for data entries, would you prefer we show the creator name & email, the PI name & email, or both? 

PI necessary, creator optional

**Comment by mccalluc** [comment]
Put on UI agenda.

**Comment by ngehlenborg** [comment]
Regarding the heatmaps, there is ongoing work in the Vitessce repo: https://github.com/hubmapconsortium/vitessce/issues/656.
