### ISSUE TITLE
Ensure that donor metadata categories match what was ingested

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1033]
These need to be replaced:

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/1216518/90031065-cf50d480-dc8a-11ea-804e-af04a7dd62e9.png">

(note that this will also be replaced with a table once we get the full list of attributes)

**Comment by ngehlenborg** [comment]
Also ensure that this is handled the same way in tile views:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/1216518/90031346-1f2f9b80-dc8b-11ea-82a3-f3d1a231b41e.png">

**Comment by mccalluc** [comment]
(Splitting tile view work (which I'm unclear on) to a separate issue: #1057)

**Comment by mccalluc** [comment]
Now using the same table as for datasets. Closing.
