### ISSUE TITLE
Deliver maintenance page to Bill

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1035]
Chuck will see if there's an easy way to capture the style and JS for our pages, so we can give Bill a static bundle of HTML, JS, and CSS.

**Comment by yuanzhou** [comment]
Let me know if you have the maintenance page ready. I'm working on this topic for ingest UI as well. Integrating this into the gateway nginx too.

**Comment by mccalluc** [comment]
@yuanzhou : I've given you a tar ball [on slack](https://hubmapconsortium.slack.com/archives/DQ0AV4RL1/p1600799544000100). To close this we need
- to hear that it worked.
- document the process on our side.

**Comment by yuanzhou** [comment]
@mccalluc I've set up the maintenance page for portal-ui. In the future, if you want to update the html of this page, just send a PR to gateway repo and the files are at: https://github.com/hubmapconsortium/gateway/tree/master/nginx/html/portal-ui-maintenance

Feel free to close this issue.
