### ISSUE TITLE
track use of facets in Google Analytics

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1045]
Create events to track which facets users are interacting with. We would like to use that to optimize future search page designs.

**Comment by mccalluc** [comment]
In the discussion today, this did not come up as a priority. I'm moving it out of milestone, and I'm going to close it with no-action-taken. The volume of old issues is causing us to lose track of the things we really want to get done.... but feel free to reopen.

**Comment by ngehlenborg** [comment]
It didn't come up because I was thinking about the detail page components. But I think it would be useful to track this. Is it complicated?
