### ISSUE TITLE
Improve provenance table rendering time slow connections

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1061]
Some (https://portal.stage.hubmapconsortium.org/browse/dataset/9f837f9fa6f7669872582c2203d5e339) take around 20s to load completely.

- Can improved indexing give us the data we need in one go?
- Can we select only a few fields to be returned in the response?
- UI: some sort of please-wait placeholder to prevent the UI from jumping around during load?
- Consolidate ES requests? (This might be tricky, and I don't know that it will have much benefit.)

**Comment by ngehlenborg** [comment]
The URL for the examples gives me a 404.

**Comment by john-conroy** [comment]
We presently won't be updating the provenance table. If we do it will be more of a redesign and new issues will be created.
