### ISSUE TITLE
Draft 'application state' use cases

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#1079]
For #1060

**Comment by ngehlenborg** [comment]
### Use Case 1

Maintain a collection of datasets (could also be donors, samples, or other entities) across pages in form of a "shopping cart" that could be converted into a collection object once the user has collected all entities that they are interested in.

**Comment by mccalluc** [comment]
TODO: Designs have been made... link here.

**Comment by mccalluc** [comment]
This was going to motivate the selection of a tool, and with a tool selected, we're good now.
