### ISSUE TITLE
Wrong error when trying to access an existing entity when logged out

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#1089]
Getting 404s.

**Comment by ngehlenborg** [comment]
Discussion and additional observations from @shirey on Slack: https://hubmapconsortium.slack.com/archives/C011RF3NQ23/p1597957064032800

**Comment by mccalluc** [comment]
> That's not what I have ever encountered before. I always got a message that said that I need to log in, along with a link to log in.

Do you mean on this site? I could be confused, but I really don't remember the behavior ever being like that, or there being any changes that would have moved us away from that.

Thinking about this more: When you don't have access to a record, it is simply not in the index you access. There is no mechanism for the search-api to communicate that a record exists, but you don't have access.

You could imagine the portal-ui having special privs, apart from the user token, that it could use to check the main index for objects that are not in the `public` index, but I think this would be a bad idea: Code complexity and security are two concerns.

Or I could imagine the `public` index having stub records which we could intercept and return a 403 response for, but again, this is complex, and a security risk.

This might have been tractable earlier in the project, but at this point where we need to support the production service, and where ensuring index consistency with the portal-ui has already been a problem, I don't think this is something we should push to change.

@ngehlenborg : I suggest closing.

**Comment by ngehlenborg** [comment]
Discussion that lead to resolution of this (non-)issue: 
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/1216518/91087132-f958ae00-e61d-11ea-9e0d-d3895bf6a754.png">
