### ISSUE TITLE
Clicking on a header menu breaks table on search pages in Safari

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1091]
To reproduce:

1. Go to 
2. Click on "Documentation" menu.
3. Search results table now extends past the width of the page.

Before clicking the menu:

<img width="1948" alt="image" src="https://user-images.githubusercontent.com/1216518/90903168-8f30d680-e39b-11ea-9454-19273ee0c566.png">

After clicking the menu:

<img width="1948" alt="image" src="https://user-images.githubusercontent.com/1216518/90903201-99eb6b80-e39b-11ea-8051-5ed197a475e2.png">

**Comment by mccalluc** [comment]
See also  #1144
