### ISSUE TITLE
Mockup: Dataset list

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#11]
Dataset is one of the [basic types](https://github.com/hubmapconsortium/hubmap-data-portal/issues/138#issuecomment-537116792): It needs a list page.

Nils should give requirements, and we should confirm that the API will have the information necessary.

Deliverable is a mockup which has approval from Nils. File a new issue for implementation when this is complete.

**Comment by ngehlenborg** [comment]
This is now obsolete. Will be handled by faceted browsing.
