### ISSUE TITLE
Don't pull donor group for datasets?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1100]
@shirey notes (on slack):
> Chuck, It looks like there is a problem with group field on faceted search and result list display for Datasets.  There are 9 published datasets of type ‘seqFISH’, all from CalTech, but 3 are showing as CalTech and 6 as Stanford.   I check both the database and ES indices, and all of these datasets have the dataset group as Cal Tech, but both the donor and origin sample group is set to Stanford for 6 of them (this is correct because Cal Tech got the tissue from Stanford).  It seems like the faceted search and result list may be using the donor.group_name or origin_sample.group_name field.  If you click to see the details of one of the Stanford seqFISH datasets the detail page shows that it is a Cal Tech dataset.

Search has pulled the dataset group from donor [since this was first implemented](https://github.com/hubmapconsortium/portal-ui/pull/300/files#diff-b50e64bb12c7a29c91ca1d1e0056afe7R34-R49), so it seems intentional. 
```
    field('donor.group_name', 'Group'),
```
My guess is that it seemed like it would make sense to keep the same donor going down the provenance chain, but I'm not sure about the motivation.

Changing the behavior would be easy, but what we should do is a UX question. @tsliaw : Is the appropriate course clear to you? If not, please loop in Nils.

**Comment by shirey** [comment]
To be clear, what I'm asking is to change it to the dataset's group name.  Otherwise you're attributing data coming from Cal Tech to Stanford.

**Comment by ngehlenborg** [comment]
Attribution should be to the group that produced the entity. If it is a dataset, it should be attributed to whoever ran the experiments, no matter the source of the donor or sample. So entity group should be set to the group associated with the entity (which we seem to be displaying on the detail pages).

@mccalluc: what is the UX question here? Maybe I misunderstand.
