### ISSUE TITLE
Changes in column header font sizes with click

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1101]
## Feedback

__Help Desk Issue Tracker URL__:  https://on.spiceworks.com/tickets/open/673/activity

__Message__:
Received from IEC team member.  The following text, sort function, and font size suggestions are below:

~~1. BioMolecular is inter-capped in use in the written out name of HuBMAP - prominent on front page of portal it has incorrectly I think: Biomolecular~~ fixed in master

~~2. When sorting donors with the up and down arrow links for BMI or Age on the donors page something happens incorrectly - the list goes away~~ fixed in master

3. In certain sort process, font sizes vary- repeatable as follows - go to public site with no login, click donors, sort on Sex twice by clicking up Sex up and down arrows

**Comment by mccalluc** [comment]
I'll look at this right now. Removing triage.

**Comment by mccalluc** [comment]
Will address sorting in https://github.com/hubmapconsortium/portal-ui/pull/1095

**Comment by mccalluc** [comment]
I've tried to reproduce the font size change on FF, Safari and Chrome, without success. @pecan88 : If you think it's worthwhile, you could followup with that user to try to get more information... which browser? OS? Every menu does that? Can they take a screen shot? ... but I'm fine with just saying we can't reproduce it.

**Comment by pecan88** [comment]
@computationdoc  - @mccalluc is noting issues with reproducing the font size change.  Would you be able to share any additional detail, screenshots, etc.?

**Comment by mccalluc** [comment]
Not able to reproduce. Reopen if you can provide more information.
