### ISSUE TITLE
improve performance of homepage load time

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1104]
Currently, it seems to take a very long time to get the data for the bar chart and for the entity counts (see `search`) in the screenshot:

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/1216518/91074170-2d29d880-e60a-11ea-8498-0fbb5fa60cda.png">

First query (`{"size":0,"aggs":{"entity_type":{"terms":{"field":"entity_type.keyword"}}}}`):

<img width="372" alt="image" src="https://user-images.githubusercontent.com/1216518/91074266-46328980-e60a-11ea-81d0-8d4c1e429b69.png">

Second query (`{"size":0,"aggs":{"data_types":{"terms":{"field":"data_types.keyword"}}}}`):

<img width="385" alt="image" src="https://user-images.githubusercontent.com/1216518/91074283-4cc10100-e60a-11ea-8b74-5a4eed73fa77.png">

**Comment by ngehlenborg** [comment]
This might be a temporary issue. The IEC is investigating. https://hubmapconsortium.slack.com/archives/C011SHWSG85/p1598288780021000

**Comment by mccalluc** [comment]
Yes: Checked, and both responses came in after 80ms, which is fine. Closing.
