### ISSUE TITLE
Design compressed "detail header" when scrolling down detail pages

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1112]
Section should contain:

- Entity type
- HuBMAP ID

Maybe use the entity tile?

**Comment by ngehlenborg** [comment]
I think that including the information (but not the layout) that we have in the tiles would be ideal, since that is meant to be the most concise summary of those entities.

**Comment by tsliaw** [comment]
Final Design: https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=196%3A86
Prototype: https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=431%3A27
Donor:
![Screen Shot 2020-09-23 at 12 11 08 PM](https://user-images.githubusercontent.com/16737715/94058450-e01a5d00-fd95-11ea-9315-440e25754bf0.png)
Samples:
![Screen Shot 2020-09-23 at 12 11 33 PM](https://user-images.githubusercontent.com/16737715/94058486-edcfe280-fd95-11ea-9637-8cc92da1c06c.png)
Datasets:
![Screen Shot 2020-09-23 at 12 12 04 PM](https://user-images.githubusercontent.com/16737715/94058533-ffb18580-fd95-11ea-85ce-b80a65cf0663.png)
