### ISSUE TITLE
draft (tissue mapping) center page

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1113]
For tissue mapping centers and other components of HuBMAP. 

Possible content:

- [ ] team members (names and roles, link to portal accounts/user page if possible)
- [ ] contact information
- [ ] publications
- [ ] assays provided to HuBMAP (link to separate assay pages)
- [ ] overview of data contributed (donors, samples, datasets
- [ ] funding information (grant numbers and titles)

**Comment by tsliaw** [comment]
Draft of TMC page.
Figma: https://www.figma.com/file/UXEvUhQp6Vap05R3H1eW1j/Center-Entity?node-id=1%3A2
![Screen Shot 2020-09-03 at 9 40 02 AM](https://user-images.githubusercontent.com/16737715/92143008-868fc580-edc9-11ea-93d9-8b13f48e2101.png)
![Screen Shot 2020-09-03 at 9 39 13 AM](https://user-images.githubusercontent.com/16737715/92143018-8abbe300-edc9-11ea-924b-e87e91051dd0.png)

**Comment by mccalluc** [comment]
Filed implementation issue #1868. Closing!
