### ISSUE TITLE
Use File API (when it exists)

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#112]
When the [File API](https://github.com/hubmapconsortium/entity-api/issues/28) is ready, use it! Just a file download option to start would be fine.

**Comment by shirey** [comment]
The final result will be display in Vittessce

**Comment by yuanzhou** [comment]
The URL to the sample json:  https://assets.test.hubmapconsortium.org/2396ff9b-5e4e-409d-ba8d-cd4c23cc78df/umap/linnarsson.cells.json

Note: 2396ff9b-5e4e-409d-ba8d-cd4c23cc78df is a made up UUID

The URL to the airflow generated derived data files: https://assets.test.hubmapconsortium.org/686cd8e0c2a9fa2dc1a321330158dcd7/

Note: there are sub-directories containing the .json, .csv, .arrow files

Globus group access nexus token is required in the HTTP request Authorization header  to access the resources.

Example: `Authorization: Bearer Ag9mN1Vaq8DnKve84v2G3Nzd1dmPQqVXlYWed058nyj1pz831XTpCrQEW2pVX8WXWrvjNBEqJk0pnYsrjegWPSXD0P`

**Comment by mccalluc** [comment]
Conversations about the files-api and assets-api have continued: https://github.com/hubmapconsortium/file-api/issues/3. It sounds like the list of files will be provided by ES. Since that is not yet available, removing `NEXT`.

**Comment by mccalluc** [comment]
Close in favor of #189
