### ISSUE TITLE
General User Feedback

### ISSUE THREAD

**Issue by debnigra** [hubmapconsortium/portal-ui#1121]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/678/activity

__Message__:
* It isn't immediately obvious where to submit comments on the current page layout? Could we have something like "Comments?" or "Feedback?" somewhere on the sidebar or footer?
* The relationship between datasets isn't so obvious - e.g. that there is a relationship between the 26 CODEX datasets and the 26 CODEX [Cytokit + SPRM] datasets until you drill down and look at the individual datasets and then only if you correctly interpret the downward arrow on the provenance section of the data page correctly
* If I open up one of the visualizations of the CODEX datasets and then close all the different panes, it just leaves me with a blank page - it would be great if there was a way of shrink down the visualization and go back to the original page (I guess I press 'esc'?)
* Are the ids for sample, donor and dataset the same? they appear to be similar, so it is not easy to distinguish that as the lead column. I guess that is a side effect of randomization of the ids? e.g. It would be great to see the number of datasets and tissues available for any specific donor as part of the donor page
* As an outside browser, I probably don't care so much about who generated the creator or which center generated the data; it would be great to see similar columns similar to the ones used by HCA; GLORIA PRYHUBER is all caps, the rest of a mix of caps;
* For protected access files, can we link to dbGaP study page?
* There seems to be some inconsistencies - e.g. we call UF both "hubmap-uflorida-tmc" and "University of Florida TMC" in the group field
* There is no way to clear a faceted search once I've made choices
* Is there any way of adding more numbers on the BMI and Age slider bars?
* it is not clear the search on the side bar does anything
* Another one is that we have 1 AA female donor; there are 18 samples noted if I do that search on the samples page, but only 14 datasets (do datasets cover multiple samples, or samples without datasets? or samples without data yet?)
* It would be great to see a link out to each of the facet terms we use and what they mean (e.g. lab processed vs Image Pyramid?)
* Why is there some metadata for donors missing? e.g. the UCSD datasets?
* We talk about SNAREseq on the front page, but we separately process the ATACseq from RNAseq data?
* It would be great to have some guidance on how to zoom in and out of images (e.g. CODEX); the expression level of the CODEX seems to be chunked into 0-9 intensity? It would be great if the heatmap for the CODEX changed based on my selection of markers
* It would be great to see a link for "Please report inconsistencies" or similar on each data page (or the visualizations - e.g. some of the segmentation maps are far from perfect)
--

**Comment by mccalluc** [comment]
Nils addressed many of these in email, which I'll copy here, or link to a github issue, as appropriate.

> > It isn't immediately obvious where to submit comments on the current page layout? Could we have something like "Comments?" or "Feedback?" somewhere on the sidebar or footer?

Fix in #1127

> > The relationship between datasets isn't so obvious - e.g. that there is a relationship between the 26 CODEX datasets and the 26 CODEX [Cytokit + SPRM] datasets until you drill down and look at the individual datasets and then only if you correctly interpret the downward arrow on the provenance section of the data page correctly
>
> This is something we will address once we have a better formal representation of the relationships between samples, assays and data analysis pipelines. 

> > If I open up one of the visualizations of the CODEX datasets and then close all the different panes, it just leaves me with a blank page - it would be great if there was a way of shrink down the visualization and go back to the original page (I guess I press 'esc'?)
>
> Yes, “ESC” is the way to get out of this, but we are discussing alternative solutions.

> > Are the ids for sample, donor and dataset the same? they appear to be similar, so it is not easy to distinguish that as the lead column. I guess that is a side effect of randomization of the ids?
>
> Yes, there is only one format for HuBMAP IDs that applies to all entity types: HBM123.ABCD.456 (HBM + <3 numbers> + ‘.’ + <4 letters> + “.” + <3 numbers>)

>> e.g. It would be great to see the number of datasets and tissues available for any specific donor as part of the donor page
>
> The updated design of the search page already includes those counts but this still needs to be implemented.

>> As an outside browser, I probably don't care so much about who generated the creator or which center generated the data; it would be great to see similar columns similar to the ones used by HCA; GLORIA PRYHUBER is all caps, the rest of a mix of caps;
>
> At the moment we can’t create separate facets for users who are logged in and for users who are not. Once we have that in place, we can remove the creator and group facets but until then I would like to keep them, as they are very important for internal users.
>
> “GLORIA PRYHUBER” must be new and is only associated with unpublished data, so regular users won’t see this. We are getting those strings from the ingestion system that the IEC is running and we are already remapping things like “daniel Cotter” to “Daniel Cotter” but I think we need to solve this at the root.

https://github.com/hubmapconsortium/search-api/issues/169

> > For protected access files, can we link to dbGaP study page?
>
> I will talk to the IEC to find out if they can make that information available.

> > There seems to be some inconsistencies - e.g. we call UF both "hubmap-uflorida-tmc" and "University of Florida TMC" in the group field
>
> That’s an inconsistency coming through the API, we have already asked for that to be changed.

> > There is no way to clear a faceted search once I've made choices
>
> You can just unselect the checkboxes after selecting them. But this is my fault, I asked for the explicit filters to be removed since they take up a lot of space but don’t add functionality. I will look into adding them back. 

Filed #1133

> > Is there any way of adding more numbers on the BMI and Age slider bars?
>
> We will investigate but you can always get the current min/max values when hovering over the sliders.

> > it is not clear the search on the side bar does anything
>
> It does but you need to hit return. That will also be revised with the updated design.

Filed #1134

> > Another one is that we have 1 AA female donor; there are 18 samples noted if I do that search on the samples page, but only 14 datasets (do datasets cover multiple samples, or samples without datasets? or samples without data yet?)
>
> This is likely (but hard to confirm) because the length of a sequence of samples leading to a dataset is longer than 1. E.g. if there is a dataset associated with an organ piece, both the organ and organ piece will be listed in the samples page (i.e. 2 samples) but only one dataset in the dataset page.

> > It would be great to see a link out to each of the facet terms we use and what they mean (e.g. lab processed vs Image Pyramid?)
> 
> We will address this once have a way to describe the assays better. Right now they are literally just a string and it is not possible properly associate other information with them.

Also, once you're on the details page, there is a link from the top of the record to the docs about each type.

> > > Why is there some metadata for donors missing? e.g. the UCSD datasets?
>
> That’s a question for Jonathan (copied) but none of these donors are scheduled to be published for the 1st release. Public users can’t see them.

> > We talk about SNAREseq on the front page, but we separately process the ATACseq from RNAseq data?
> > It would be great to have some guidance on how to zoom in and out of images (e.g. CODEX); the expression level of the CODEX seems to be chunked into 0-9 intensity? It would be great if the heatmap for the CODEX changed based on my selection of markers
>
> Zooming is done via the mousewheel/track pad like Google Maps but we can add a help button for that.The expression levels are mapped continuously and we hope to add a legend eventually. Top row of the heatmap shows the selected marker.

Filed #1135.

> > It would be great to see a link for "Please report inconsistencies" or similar on each data page (or the visualizations - e.g. some of the segmentation maps are far from perfect)
> 
> Will add that to our to do list.

Filed #1136

Closing.
