### ISSUE TITLE
Make lymph nodes plural

### ISSUE THREAD

**Issue by debnigra** [hubmapconsortium/portal-ui#1123]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/674/activity

__Message__:Hi,
I've noticed that in our lists of tissue types on the portal, we have
"lymph node" listed.  I believe it should be "lymph nodes" as there
are many of them.  Please update them to be plural.

**Comment by mccalluc** [comment]
Is this the context for that comment?
<img width="188" alt="Screen Shot 2020-08-28 at 9 31 30 AM" src="https://user-images.githubusercontent.com/730388/91566227-59e33600-e911-11ea-9106-cb702e4688a0.png">
In that context, I'm pretty sure it would remain singular: Each sample comes from a single lymph node, not multiple.

I'll close, but reopen if this is not the list of interest.
