### ISSUE TITLE
Clear out "duplicate" datasets in home-page graph

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#1132]
Right now our graph on the home page contains counts of derived datasets and datasets themselves, but this is somewhat redundant since `Imaging Mass Cytometry` implies `Imaging Mass Cytometry [Image Pyramid]` (and the same for many other datatypes).  We should clean some or all of these up once we have more information about datasets.

**Comment by mccalluc** [comment]
Chart will be redone with homepage re-do. vis-lifting (#1576) will also improve this.
