### ISSUE TITLE
Bring back search tags?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1133]
> But this is my fault, I asked for the explicit filters to be removed since they take up a lot of space but don’t add functionality. I will look into adding them back.

Reverting the earlier change is easy enough, but maybe we don't want exactly what was there before? Get clarity from Nils.

**Comment by mccalluc** [comment]
@tsliaw : Is this a duplicate? You're already working on this. Link to the real issue and close, if appropriate.

**Comment by tsliaw** [comment]
Sorry I didn't see this issue, I'll close #1335. Figma mockup is [here](https://www.figma.com/file/pkIZbpJOAQnylo1zjyhaU6/Search-Page?node-id=657%3A150). Waiting for approval.

**Comment by tsliaw** [comment]
Approved Design: https://www.figma.com/file/pkIZbpJOAQnylo1zjyhaU6/Search-Page?node-id=657%3A150
![Screen Shot 2020-12-07 at 11 27 00 AM](https://user-images.githubusercontent.com/16737715/101395673-20f71d80-387f-11eb-8cc1-58d85d8205d5.png)
![Screen Shot 2020-12-07 at 11 27 17 AM](https://user-images.githubusercontent.com/16737715/101395709-2ce2df80-387f-11eb-9930-758809678151.png)
