### ISSUE TITLE
Bring back search on keypress?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1134]
> > > it is not clear the search on the side bar does anything
>
> It does but you need to hit return. That will also be revised with the updated design.

@tsliaw : It's easy enough to revert that change? Get clarity from Nils.

**Comment by mccalluc** [comment]
@tsliaw -- Can you figure out the direction on this? I would prefer just to close it.

**Comment by tsliaw** [comment]
Can you bring back the search when pressing the 'return' key?
