### ISSUE TITLE
Markdown CSS: Indent <details> under <summary>

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1147]
<img width="787" alt="Screen Shot 2020-08-31 at 1 00 17 PM" src="https://user-images.githubusercontent.com/730388/91746845-42af7d00-eb8b-11ea-9471-7867ed895f7f.png">

This would be more readable if the answer were indented a bit.

**Comment by mccalluc** [comment]
@tsliaw : Do you agree indentation would be good? Any other thoughts?

**Comment by tsliaw** [comment]
Indentation of the body text should help readability. Is is possible to place these into a [Material accordion component](https://material-ui.com/components/accordion/) to match the design on the rest of the portal? That should also help readability, but if not possible then indentation should work for now.

**Comment by mccalluc** [comment]
> Is is possible to place these into a Material accordion component to match the design on the rest of the portal?

Right now, it's just passing the `<details>` tag straight through... changing the rendering machinery to output accordions would be a _much_ bigger job.
