### ISSUE TITLE
Link Colors

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1149]
All links on the portal should be #3781D1 (info color). 

- [ ] Markdown links currently appear to be #0000EE. (Documentation and Preview pages)
- [ ] Search page filter links are currently #0088CC

**Comment by mccalluc** [comment]
- See also #2403 ... the link color may change.

**Comment by mccalluc** [comment]
I think this is fixed: `Markdown/style.js` has:
```
  a {
    color: ${(props) => props.theme.palette.link.main};
  }
```
and using the browser inspector, the link color is now `rgb(55, 129, 209)` == `#3781d1`

I'm not sure what precisely is meant by "search page filter links" ... the "view all"? That is also `rgb(55, 129, 209)` right now... and if you mean something else, it's going to be replaced by John shortly, so not worth worrying about.
