### ISSUE TITLE
triage: display "status" and "access" level definitions in UI?

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1161]
Question is for Nils / Chuck if they want to try to work this into the UI in some appropriate fashion or whether we should simply add it to the documentation.  UI/UX call.  In the meantime, @schwenk102 will be putting up a page for documentation until we decide.

Borromeo, Charles <chuck.borromeo@pitt.edu> wrote:
<blockquote>
Hi Peter and Melissa,
  I recently discussed two facets found on the HuBMAP Portal under the Datasets "tab" (https://portal.hubmapconsortium.org/search?entity_type[0]=Dataset).  There are two facets:"Status" and "Access Level".  There are some instances where the terms found in these facets become conflated and confusing.  Jonathan (cc'd) asked me to supply you with definitions that might alleviate some of the confusion.  Feel free to edit as you see fit.  BTW, I did suggest to Nils that the Portal might want to change the current "Status" facet label to "Workflow Status" or "Curation Status".  So double-check the Portal website to ensure the definitions accurately reflect the facet label.

Below are my definitions:

**Status**- the status of a dataset indicates the dataset's state within the workflow process.  A typical dataset workflow process involves the following status transitions: New -> QA -> Published.  In a typical workflow, the dataset is progressing through steps representing analysis steps or increasingly stringent data quality checks.  The status also includes some non-standard statuses: Hold, Error, Processing, or Reopen.  Please note, the status of "Published" does not indicate the dataset can be seen outside of HuBMAP.  It merely means the data has undergone the necessary data curation and can be considered fit for research purposes.

**Access Level**- there are several access levels supported by HuBMAP including: protected, consortium, and public.  These levels are used by the software and API's to determine if a user has sufficient rights to see the data.  A user's access rights are determined by the information contained in a Globus token.  The levels are defined below (in order from most restrictive to least restrictive):

**protected**- the data associated with this level contains genomic data or other data falling under HIPAA guidelines for access.  A user must formally apply for access to see this data.  Although the data labeled as protected may become known to external researchers through HuBMAP search tools, only a minimal high-level portion of the data will be accessible without a formal application.  In addition to the formal application, a user must provide a valid Globus token to access this data.

**consortium**- the data associated with this level requires the user to be a recognized member of the HuBMAP consortium.  In general, the data in the consortium data access level will eventually be made public in the future.  From a certain perspective, consortium data can be considered "embargoed" within the HuBMAP project for a certain amount of time.  A user must provide a valid Globus token to access this data.

**public**- the data associated with this level can be accessed by users outside of the HuBMAP project.  This is the least restrictive access level.  The user does not need a valid Globus token to access this data.
</blockquote>

**Comment by mccalluc** [comment]
@tsliaw : I know that you've been working on contextual help... could this information fit in that framework? Or do you want to work with Nils to find some other way to make this more clear?

One example from a project I worked with in the past: https://americanarchive.org/catalog?f%5Baccess_types%5D%5B%5D=online&utf8=%E2%9C%93 ... In the past the access control facets had been in the sidebar on the left, with the descriptions always visible, so you can take this as one datapoint.

**Comment by mccalluc** [comment]
With the new search machinery, all columns will have descriptions, so we don't need to track this special case.
