### ISSUE TITLE
Broken image link in Documentation > APIs

### ISSUE THREAD

**Issue by admin-hubmapconsortium** [hubmapconsortium/portal-ui#1163]
Image is not coming through on the API documentation page. (Browser = Chrome, current version)

![image001](https://user-images.githubusercontent.com/70603634/91903942-11f64300-ec72-11ea-9070-2bbd6dc84888.jpg)

**Comment by mccalluc** [comment]
Duplicate of https://github.com/hubmapconsortium/portal-docs/issues/6 . closing.
