### ISSUE TITLE
Unable to consistently open data set via HuBMAP ID in the URL

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1169]
Doesn't work: https://portal.hubmapconsortium.org/browse/HBM.684.PPPQ.769 (dataset exists and is publicly accessible: https://portal.hubmapconsortium.org/browse/dataset/8944e654613a8a31bc90d936dd0fade6)

Works: https://portal.hubmapconsortium.org/browse/HBM955.RNNP.677 (dataset exists and is publicly accessible: 
https://portal.hubmapconsortium.org/browse/dataset/5409cced402ef1eec2d5eca8912bfbee)

**Comment by mccalluc** [comment]
Take the period out and it works:
```diff
- https://portal.hubmapconsortium.org/browse/HBM.684.PPPQ.769
+ https://portal.hubmapconsortium.org/browse/HBM684.PPPQ.769
```
Closing, but reopen if it should be able to handle this.

**Comment by ngehlenborg** [comment]
Haha, ok.
