### ISSUE TITLE
Create a user-friendly summary of HuBMAP data in a table on the home-page.

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/portal-ui#117]
Users should be able to see a simplified overview of the data-types & sample-types available in HuBMAP in a table format on the HOME page. The columns represent data-types. The rows represent the tissue-types. Each cell in the table should contain a number representing the number of datasets available for the selected data-tissue combination. The number is a hyperlink to a table or list showing the breakdown of datasets available for the selected tissue/assay combination.

https://drive.google.com/open?id=10T77acgo9eFiPWd_Za0IMqz_i2KEmj0kaiYnndomht4

![Screen Shot 2020-01-14 at 2 47 27 PM](https://user-images.githubusercontent.com/8284878/72376938-d60b6f00-36dc-11ea-864b-1bfce792a43b.png)

**Comment by mccalluc** [comment]
Hi: I'm going to unpin this, if that's ok: We're using the sprints to set priorities on task, so I added NEXT so we'll see it on Friday.

**Comment by cebriggs7135** [comment]
Here's an example I created from our Loaded Datasets doc https://docs.google.com/spreadsheets/d/1gSSwCi9kx7-x_wcEDQFv-MLNgm_hNNN4PPIL0mg4GSI/edit#gid=1899790107

**Comment by mccalluc** [comment]
Discussed this morning: Nils would prefer bar chart. Closing.
