### ISSUE TITLE
provide seqFISH visualization

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#1175]
I have talked with @cebriggs7135 about the seqFish data and I am going to summarize what we should do here, how we should do it, and also provide some context/motivation:

Right now, the images are split into datasets by position and then each image corresponding to one of many hybridization cycles at that position contains 4 channels.  Each channel corresponds to a wavelength and within each wavelength, combinations of 3 hybridization cycles correspond to showing barcoded genes (a fourth hybridization, while indicated in the docs here: https://portal.hubmapconsortium.org/docs/assays/seqfish is actually a control).

For example on https://portal.hubmapconsortium.org/browse/dataset/7fa46d1b74c3f146f0cb7138b8ac690d you may have that `HybCycle_1`, `HybCycle_12`, and `HybCycle_5` within wavelength `488` together indicate gene id 2491 (this is just a made-up example).  We thus have `num_HybCycle` ^ `3` possible genes for each wavelength, and thus `num_Wavelengths * (num_HybCycle ^ 3)` possible genes total.  However, right now, these hybridization cycles are split across different images which only allows for alpha-blending and generally makes the task combining the hybridization cycles more challenging.

Luckily, CalTech has provided in their "Lab Processed" data gene locations and intensities which we can display using our Vitessce `molecules` functionality like [here](http://vitessce.io/?dataset=linnarsson-2018&theme=dark) or [here](http://vitessce.io/?dataset=wang-2019&theme=dark) ([this](https://app.globus.org/file-manager?destination_id=3a488a36-20fb-11ea-b955-0e16720bb42f&destination_path=%2F~%2FDownloads%2F&origin_id=af603d86-eab9-4eec-bb1d-9d26556741bb&origin_path=%2F7f0e5c10babfa368c9fbaff2e52f79f4%2Fdata%2F) is an example globus directory).  CalTech also provided segmentation masks but I have heard that we may produce our own.

To really visualize the seqFish data in a meaningful way we thus need to:

1) Process the genes data CalTech provided
2) Hook up the `molecules` in Vitessce to the `Genes` component so that you can select to see only certain gene spots (i.e `molecules` in Vitessce) based on gene selections
3) Add a concept of intensity to our current implementation of `molecules` in Vitessce so people may make meaningful spatial comparisons between different genes
4) Show `molecules` (i.e the genes) in 3D in Vitessce - CalTech provides a `z` position that we can use to show a point cloud which is very exciting.  This will require a new implementation in Vitessce of 3D point-cloud data which is a larger discussion, but is also probably necessary given that this is not the first time we are running into 3D point-cloud data in FISH assays (I remember seeing this multiple times during presentations at ISMB and NIH meetings).
5) Process segmentation masks and get expression levels on a per-cell basis for each gene

In addition, and this is optional from what I am hearing from Chris and others in terms of meaningful biological visualization/discovery, if we want to show the raw imaging data we will need to do several more complicated things:

5) Obtain/Find the barcode combinations of `HybCycles` that correspond to genes and show that in Vitessce as well so that users may select combinations of them in the raw imaging data to see where the genes appear in the raw data.  It would be great to make this a controller but I would like to do more digging into this to find out if this sort of combination-based viewing is common
6) Show the raw imaging data in 3D
7) Reprocess the TIFF images so that each image corresponds to a wave length, and, within each new image, a channel is now a hybridization cycle.  This way, you can meaningfully blend the new channels to show actual genetic data.  The current way we have it, images correspond to hybridization cycles and each channel within an image is a wavelength.

**Comment by mccalluc** [comment]
@ilan-gold : If I'm understanding this correctly, there's a lot of work here across repos (pipelines, vitessce, and constructing the new viewconfs in this rep)? If that's the case, when you decide this is a priority, probably good to create sub issues in other repos, and link back here.

**Comment by ilan-gold** [comment]
@mccalluc Yes this would be a rather large lift although I think that most of the challenge here is coordinating/organizing among different people the timing of this work rather than the actual work involved.

I also tried to split up the work into two parts - imaging and non-imaging.  The non-imaging data/coding (i.e the `molecules` work I mention) would not be that much work comparatively, I think.  I think the daunting part is the imaging work and it seems non-essential.

**Comment by ngehlenborg** [comment]
We can revisit this once seqFISH is processed via the portal. Lab processed data is too problematic for visualization as it stands.

**Comment by mccalluc** [comment]
The [9 seqFISH datasets](https://portal.hubmapconsortium.org/search?mapped_data_types[0]=seqFISH&entity_type[0]=Dataset) (not lab processed) have visualizations, so I think this can be closed? If I'm misunderstanding the scope, please re-open and clarify.
