### ISSUE TITLE
Re-Run IMS

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#1176]
In order to visualize the IMS data in concert with the AF/mxIF/PAS images, we need to re-process them so that we have the scale/translation factor available for overlaying the image.  My ideal solution would be to properly crop the images based on their `imzml` file and then write out an OME-TIFF of the cropped image.  We may then use Vitessce to show the overlaid images.

**Comment by mccalluc** [comment]
@ilan-gold : If I'm understanding this correctly, there needs to be a pipeline update before the re-run? Consider moving this issue to that repo.

**Comment by ilan-gold** [comment]
Fixed by having physical sizing scale factor available.
