### ISSUE TITLE
display entity uuid on entity page

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#118]
The UUID of the entity being displayed is currently not shown on the page itself, it is only displayed in the URL. It should be shown in the "JSON table" section of the entity page.

**Comment by mccalluc** [comment]
[Consensus](https://github.com/hubmapconsortium/portal-ui/issues/170#issuecomment-622412417) --> UUID is not displayed on the page: User will only see in URL. Closing.
