### ISSUE TITLE
Add service status page and link in footer

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1187]
We should make the portal UI version and the software versions of other services accessible through the footer.

**Comment by mccalluc** [comment]
Clarification: Link from footer to a page with information about the versions being used.

**Comment by ngehlenborg** [comment]
@tsliaw Could you quick make a rough mock up for the "services" page: 

Could be a simple table with columns:

- status (or "Ok" - green dot? or "Unreachable" - pink dot?)
- service name (e.g. "User Interface")
- version (e.g. "v0.1.0")
- link to GitHub repository (e.g. "https://github.com/hubmapconsortium/portal-ui")

**Comment by tsliaw** [comment]
Figma: https://www.figma.com/file/HfFNyTKAf6T0D1yt5n9XIb/Services?node-id=1%3A9
<img width="770" alt="services" src="https://user-images.githubusercontent.com/16737715/92523035-84b47080-f1d4-11ea-937f-ddda3460f4e8.png">

**Comment by tsliaw** [comment]
Approved v1.0. Figma link: https://www.figma.com/file/HfFNyTKAf6T0D1yt5n9XIb/Services?node-id=8%3A21
![Screen Shot 2020-09-08 at 2 18 10 PM](https://user-images.githubusercontent.com/16737715/92528750-21c7d700-f1de-11ea-91cf-f53e0aeeb804.png)

**Comment by ngehlenborg** [comment]
Based on discussion in #1189, we might need an option to display service specific key-value pairs. I don't expect there to be more than 5 for any given service with 1 to 2 being typical. 

@tsliaw: can you think about a solution about this? I think it could even be fine to have a tooltip/pop up that people can get when hovering over a "Details" label that shows up in an additional column (if additional key-value pairs are available).
