### ISSUE TITLE
Define portal services API

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1189]
Suggested endpoint: `/service-status`

`GET` request response required information:

- name of service
- main GitHub repo for service
- version

Optional?
- link to API documentation?

**Comment by yuanzhou** [comment]
@ngehlenborg @mccalluc we actually already have all the API status: https://gateway.api.hubmapconsortium.org/status.json and the corresponding simple HTML version: https://gateway.api.hubmapconsortium.org/status.html

For displaying these API status on portal-ui, you can also make calls to the individual API status endpoint:
- entity-api: https://entity.api.hubmapconsortium.org/status
- ingest-api: https://ingest.api.hubmapconsortium.org/status
- uuid-api: https://uuid.api.hubmapconsortium.org/status
- search-api: https://search.api.hubmapconsortium.org/status
- file assets: https://assets.hubmapconsortium.org/status/file_assets_status.json

In general if you get 200 back from the calls to the above API status endpoints, it means the API is up running. We also provide additional information like neo4j connection and elasticsearch connections, etc.

**Comment by yuanzhou** [comment]
I've been also working on adding the API version and build version to each API service, so the above status calls will also return the version and build information.

**Comment by yuanzhou** [comment]
@shirey I think I'm can roll out the version/build changes.

**Comment by ngehlenborg** [comment]
This is great and good to know. 

If we can agree on a set of common fields supported by all services, e.g., name, status (HTTP 200 is fine), version, build hash (if that makes sense in addition to the version), GitHub repository, API auth (looks like your services all have that although I am not sure what it means), as well as a field for additional key-value pairs to support service specific status information, we can add that to the status page.

**Comment by mccalluc** [comment]
@yuanzhou : I see that [you've got this on STAGE](https://entity-api.stage.hubmapconsortium.org/status).
```json
{
  "build": "devel-based-1.8.0:8133fd7",
  "neo4j_connection": true,
  "version": "1.8.0"
}
```
Great! We can start developing against this, but we wouldn't merge that feature branch or deploy until it's on prod. Thanks.

**Comment by mccalluc** [comment]
Status APIs are in place. If there are particular fields missing, that can be a new more granular issue.
