### ISSUE TITLE
explore integration of statistics from Google Analytics in portal UI 

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1199]
Decide if we (1) want to and (2) can incorporate statistics from Google Analytics directly into the portal UI, e.g., like here: http://tisch.comp-genomics.org/statistics/

**Comment by mccalluc** [comment]
$0.02: (1) no, (2) [yes](https://developers.google.com/analytics/devguides/reporting/core/v4)

**Comment by mccalluc** [comment]
@ngehlenborg -- My sense is that this came before we had the analytics dashboards set up. I believe they are a good-enough solution, and that there will always be higher priority tasks... but reopen if I'm mistaken.
