### ISSUE TITLE
triage: Section header hidden by links going to anchor 

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1200]
Fill in as much as seems useful:

**Describe the issue**
Selecting the assay type on a dataset entry links you to the assay documentation, however when you first access the page, the banner covers the actual name of the assay.

**To Reproduce**
1. Go to datasets
2. Select dataset (ex. IMC)
3. Select assay type under title of dataset
4. See list of assays, but initially don't see the assay type

**Expected behavior**
Ideally show the section header / anchor target

**Screenshots**

**Environment**
 - Browser: Chrome / Windows 10
 - Browser version:
 - Portal version: `/static/VERSION`

**Best guesses**
 - Relevant repos:
 - Developers to involve: Likely Tiffany?

**Comment by mccalluc** [comment]
In the next deployment, links to `/docs/assays` will no longer be anchored to sections, so you'll always just land at the top of the page.

But, more generally, yes, this could be better. We have internal links to `/docs/donor#more` for example.

**Comment by mccalluc** [comment]
@john-conroy : Since you're thinking about page-header issues right now, this might be something to consider. This issue itself is low priority... but I think linking to an anchor is something we'd like to have work on all our pages.

**Comment by mccalluc** [comment]
@john-conroy ... Since you're thinking about anchored links right now, this is one thing to  consider.

**Comment by mccalluc** [comment]
docs are now longer hosted here. Anchor links don't matter so much in other parts of the site. Closing.
