### ISSUE TITLE
Documentation needed for processed datasets?

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1201]
JCS pointed out that when you go to view any of the dataset types that include "[pyramid]" in the title, the link to the assay type below the title takes you to a non-existent assay type anchor.

I'm tentatively assigning to @cebriggs7135 to determine the format of documentation needed for processed data types.  In the meantime, I will confirm via Microscopy assay teams the need for this documentation.

![pyramid2](https://user-images.githubusercontent.com/21177919/92733761-ed6f2a80-f345-11ea-8b56-76ce93f8a774.JPG)
![pyramid](https://user-images.githubusercontent.com/21177919/92733764-ee07c100-f345-11ea-81af-4c523c01be09.JPG)

**Comment by mccalluc** [comment]
We've gotten rid of the anchored links for assays in master, because of this sort of issue: with multiple assay types represented by a single string, we don't want to link to just one.

So that might not be perceived as an improvement, but this particular issue is gone on master.
