### ISSUE TITLE
Handle dag provenance origin fields which do not have .git extension in provenance analysis details

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#1215]
From slack:

> future versions will not include the '.git' extension but some data already present in the PROD database does include the '.git'.  In any case, both URLs are valid, so I think it's best to accept both forms.

**Comment by mccalluc** [comment]
Before closing, make sure [this thread](https://hubmapconsortium.slack.com/archives/C011RF3NQ23/p1600103546124800?thread_ts=1600102861.124700&cid=C011RF3NQ23) came to a conclusion.

> We understand that retroactively changing this field is not feasible, but going forward, how should we ensure consistency in this field and others? If we can have consistency earlier in the process, it will save trouble in every step downstream.
