### ISSUE TITLE
404s in log for "Multimodal Molecular Imaging Data" Preview

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1217]
For https://portal.stage.hubmapconsortium.org/preview/multimodal-molecular-imaging-data there are a number of 404s in the log. For example:

> https://vitessce-data.storage.googleapis.com/0.0.27/master_release/spraggins/spraggins.mxif.zarr/4/.zgroup

@ilan-gold ?

**Comment by ilan-gold** [comment]
The zarr.js library tries to find certain parts of the zarr store that are not necessarily there for (potential) parsing purposes.

**Comment by mccalluc** [comment]
Ok, so it's expected behavior, and there's nothing to worry about here? Closing.

**Comment by ilan-gold** [comment]
Yes, exactly. Thanks.
