### ISSUE TITLE
Mockup User-Customizable Collections

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1228]
Notes:
- Consider user with multiple devices
- Version 1 might have to be on local storage
- There should be "shopping cart" of data, which can be used to make a user-customizable collection

**Comment by mccalluc** [comment]
Tiffany needs to rewind... identify subset to implement.

**Comment by mccalluc** [comment]
Needs Nils feedback. Big!

**Comment by tsliaw** [comment]
Approved Figma Design:
- [Detail Page "Save" Addition](https://www.figma.com/file/EQSyXT2wv6lh9cYfsggRql/My-Lists-Page?node-id=90%3A261)
- [My Lists Page](https://www.figma.com/file/EQSyXT2wv6lh9cYfsggRql/My-Lists-Page?node-id=2121%3A6311)
-[List Detail Page](https://www.figma.com/file/EQSyXT2wv6lh9cYfsggRql/My-Lists-Page?node-id=38%3A570)
