### ISSUE TITLE
Create plan for provenance graph revision

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#1232]
We've identified a few issues and areas of improvement for the provenance graph. We should create a formal plan to update the provenance graph.

**Comment by mccalluc** [comment]
Take discussions we've already had, outline all the things we've considered, and all the things we want to investigate. (Goals for 2nd quarter.)

Deliverable for this issue is a document.

**Comment by john-conroy** [comment]
We now have a better grasp on what we'd like to accomplish with #1595 and #1596 as starting points
