### ISSUE TITLE
Use schema.org to improve findability

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1237]
Findable with Google datasets search

**Comment by ngehlenborg** [comment]
Can you provide more information about this? What does this refer to?

**Comment by mccalluc** [comment]
Providing machine-readable would make it more Findable with [datasetsearch.research.google.com](https://datasetsearch.research.google.com/search?query=fastq&docid=MrdtoRnZWzfrxUESAAAAAA%3D%3D)

**Comment by mccalluc** [comment]
Get input from other groups about scope.

**Comment by mccalluc** [comment]
In progress: PRs are in, but I want to confirm that google can read the data before closing.

**Comment by mccalluc** [comment]
Google is able to read our JSON-LD. There will be tweaks. Addressed by PR #1292.
