### ISSUE TITLE
Highlight QA info

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1241]
- Flag on QA output files in datasets
- Separate file section into QA files and other files

**Comment by shirey** [comment]
@ngehlenborg Can you clarify what we need here?  Joel, Matt and I can start a conversation about this, but we're unclear of where to even start.

**Comment by tsliaw** [comment]
Mockup v1.0 for QA filtering on file table: https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=1141%3A5779
Will open new issue for QA section on datasets.  

![Screen Shot 2020-11-02 at 8 53 36 AM](https://user-images.githubusercontent.com/16737715/97895659-ee3e9000-1ce8-11eb-94e2-8d9981b6b76a.png)
![Screen Shot 2020-11-02 at 8 53 41 AM](https://user-images.githubusercontent.com/16737715/97895637-eaab0900-1ce8-11eb-9ca6-fd0b27c42e28.png)
