### ISSUE TITLE
Revise display of assays in faceted browsing UI

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1260]
The long list of assay types and the amount of indentation is making it very hard to read this list and to get an overview.

We need to redesign this. There are some quick fixes (e.g., use less indentation, make the column wider, split the pipeline name from the assay type name and make the former smaller in a separate line, etc.) and some longer term solutions (e.g., 
grouping by assay class, using a completely different layout, etc.). 

<img width="788" alt="image" src="https://user-images.githubusercontent.com/1216518/94601974-430e6700-0262-11eb-89b4-4a20d07918e5.png">

**Comment by mccalluc** [comment]
One reason this list blows up are the coordinated names we have for derived data sets: Having one facet for "Image Pyramid" rather than creating pairs of assays in this list is one possibility.

**Comment by mccalluc** [comment]
Vis lifting (#1576) will partly resolve this. If more should be done, put on an agenda to clarify next steps.
