### ISSUE TITLE
Add better names to UMAP Scatterplot?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#128]
@mruffalo : Right now, the points in the UMAP scatterplot are going to be identified by a short genetic sequence... Is there some other ID in that file which would make a better display name?

**Comment by mccalluc** [comment]
My sense is that the cells really are identified by these tag sequences. No action required.

**Comment by mruffalo** [comment]
Correct -- the cell barcode is the only thing that really qualifies as a cell ID. Maybe cell type with a consecutive integer at some point in the future, but we don't have that data yet.
