### ISSUE TITLE
Fullscreen Vitessce on Preview page has gap on top

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1288]
When Vitessce is in fullscreen on preview pages, there is a gap between the header and where Vitessce begins. Screenshot is attached. 
<img width="1774" alt="Screen Shot 2020-10-06 at 1 54 12 PM" src="https://user-images.githubusercontent.com/16737715/95259041-6d6ca100-07db-11eb-9f82-07d073a913d6.png">

**Comment by john-conroy** [comment]
Thanks!
