### ISSUE TITLE
Data Download Folder Structure, Readme, and understanding contents

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1296]
Fill in as much as seems useful:

**Describe the issue**
After downloading dataset, finding unexpected structure / data / lack of data
Issue sent from NIH

**To Reproduce**

1. Go to Portal
2. Search for AF dataset
3. Navigate to download function
4. Select download
5. open file

**Expected behavior**

**Screenshots**

**Environment**
 - Browser: 
 - Browser version: 
 - Portal version: `/static/VERSION`

**Best guesses**
 - Relevant repos: UI, Ingest, possibly others?
 - Developers to involve: @shirey , @mccalluc , @pdblood ?

Full message:
----
So, I was looking at Vanderbilt’s AF data. Clicking on the download files I got a bunch of weirdly named folders. No Readme, I couldn’t parse what was expected in the different folders. I read the assay description. It talks about data states so I expected to be able to download multiple data states, but found nothing that corresponded to that. I expected a metadata file, didn’t find those and so on … 

[Who should I contact re: this kind of thing?]

I am also puzzled that no one from the community has found these issues … this is worrying.

----
 
The data and contact points are listed in the portal documentation at the bottom of assay documents as well as on the metadata page:
 
https://portal.hubmapconsortium.org/docs/metadata
 
----
Which data are in question?  Peter can you help?
 
----
I am trying to understand what some of the data downloads and I am being unable to figure it out. Do you know who I can reach out to to understand what I should expect to get? Thanks.

**Comment by mccalluc** [comment]
> Clicking on the download files I got a bunch of weirdly named folders. 

Assuming "Bulk Data Transfer" is meant here?

> No Readme, I couldn’t parse what was expected in the different folders.

With directory schemas in ingest-validation-tools, we should be able to offer a description of the files that make up a submission, but that's a work in progress. I don't believe general documentation about the assay type should repeated in every dataset... but a short README that just points to other documentation wouldn't be the end of the world.

> I read the assay description. It talks about data states so I expected to be able to download multiple data states, but found nothing that corresponded to that. I expected a metadata file, didn’t find those and so on …

These docs were originally written for the data submitters, and then repurposed for the data consumers. 

> The data and contact points are listed in the portal documentation at the bottom of assay documents as well as on the metadata page:
>
> https://portal.hubmapconsortium.org/docs/metadata
>
> Which data are in question? Peter can you help?

I'm not sure what the question is here.

> I am trying to understand what some of the data downloads and I am being unable to figure it out. Do you know who I can reach out to to understand what I should expect to get? Thanks.

Again, the submission structure really wasn't prescribed the first time around, but we're trying to catch up.

- So at the next UI meeting, I'll raise the idea of a README in each dataset directory, probably added after submission... This would ultimately need to be done by Bill, but the idea should be evaluated first.
- @pecan88  : I believe you own the documentation, so I'll let you decide if there is anything actionable here?
- @pdblood : Documenting the directory structure in ingest-validation-tools is in your court? When we have that, we might show the globus files in the UI, as we do for the outputs of the pipeline.

**Comment by mccalluc** [comment]
(Will close when Peter and Phil respond, and either no action required, or they are tracking that aspect of the issue somewhere else.)

**Comment by mccalluc** [comment]
> So at the next UI meeting, I'll raise the idea of a README in each dataset directory, probably added after submission... This would ultimately need to be done by Bill, but the idea should be evaluated first.

Yes, Nils would be ok with a README being generated, based on the directory schema, to describe what the data set is about, but it doesn't seem like a really high priority. 

At this point, I don't think there's anything actionable in the portal-ui codebase relevant to this issue, and it should be moved somewhere else, where the work will be done. (Or new issues should be filed, linking back to this one.)

**Comment by shirey** [comment]
I talked to Peter about this we're going to explore further and will track elsewhere so I'll close.
