### ISSUE TITLE
Design lab-processed / outside-consortia datasets

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1297]
Two distinct stories, which overlap:
- HuBMAP TMCs may run their own processing pipelines, instead of, for whatever reason, having the HIVE do it.
- Outside consortia will be contributing data which we'll want to display.

Areas of work:
- The details pages should have some of indicating that this might not be the gold-standard of HIVE processed data.
- There might be new search facets, or other navigational tweaks.

**Comment by mccalluc** [comment]
@tsliaw : We can talk at standup, but how is this going?

**Comment by mccalluc** [comment]
working on it now!

**Comment by tsliaw** [comment]
Design: https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=1252%3A6861
- Added project facets to search page
- Added flag to detail pages with linkage out to consortium project page
![Screen Shot 2020-12-01 at 9 57 06 AM](https://user-images.githubusercontent.com/16737715/100778510-f3602f00-33bb-11eb-9927-ccc111dbb8e9.png)
![Screen Shot 2020-12-01 at 9 51 37 AM](https://user-images.githubusercontent.com/16737715/100778516-f529f280-33bb-11eb-95d1-94aeaec4eff2.png)

**Comment by tsliaw** [comment]
Approved Design: https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=1251%3A0
![Uploading Screen Shot 2020-12-07 at 10.14.48 AM.png…]()
