### ISSUE TITLE
User Research for Advanced Queries

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1298]
To Do:

- [x] Review other sites for advanced query features
- [x] Review previous work done to progress advanced queries
- [x] Gather use cases by 11/09
- [x] Create user interview questionnaire and gather list of people to interview by 11/15
- [x] Create use case templates / generalizations of use cases

Will create new issue for mockup for user testing

**Comment by mccalluc** [comment]
@tsliaw : Can you check off some of the boxes? I think actually talking with the biologist would be good, as you've noted, but I don't think it's going to happen in the next two weeks, so not something for the next sprint. Perhaps you can identify a granular sub-goal? Or perhaps not?

**Comment by tsliaw** [comment]
Updated task list to reflect timeline of user research as discussed with Nils.

**Comment by tsliaw** [comment]
All user research should be close to finishing with one more interview scheduled and results in process of analyzing. Use cases in google docs need to be updated still, but are in Figma. Will close this issue and open design issue for molecular/cellular query.
