### ISSUE TITLE
What license are the datasets?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1305]
It should be a URL: https://developers.google.com/search/docs/data-types/dataset

**Comment by mccalluc** [comment]
put on agenda, again.

**Comment by mccalluc** [comment]
Nils will follow up with Ajay on this to communicate that there is very little concern that there will be changes to the data.

@ngehlenborg -- So we're waiting for confirmation from Ajay before moving forward?

**Comment by mccalluc** [comment]
cc-by 4.0!

**Comment by tsliaw** [comment]
[Figma Design Link](https://www.figma.com/file/9nlXn9704s2zQ9CRvAQTXU/Data-Use-Agreement?node-id=0%3A1)
