### ISSUE TITLE
Globus Timeouts on CODEX data

### ISSUE THREAD

**Issue by debnigra** [hubmapconsortium/portal-ui#1307]
From ticket # 849 in the HuBMAP help desk:
I've been receiving timeouts trying to access various HuBMAP CODEX
directories from the portal using Globus. 

I've attached a screenshot of the Globus Directory (Globus1.PNG). Clicking
on a subdirectory [e.g. cyc002_reg001_191213_140502, though it doesn't
matter which one] frequently gives the timeout message (Globus2.PNG) 
I believe that this timeout may need to be increased (currently seems to be
~20 seconds), but there may be other latency issues involved. 

<img width="391" alt="Globus1" src="https://user-images.githubusercontent.com/3306741/96512473-88550180-122e-11eb-9e5b-df948560fdf6.PNG">
<img width="395" alt="Globus2" src="https://user-images.githubusercontent.com/3306741/96512474-88550180-122e-11eb-87a2-c90bbd5d166a.PNG">

**Comment by mccalluc** [comment]
@debnigra :
- Have you just created the `spiceworks` label? How will this be used differently from `triage`?
- What goes on in the Globus UI has no relationship to the portal-ui codebase. Bill Shirey might be the best contact, but he doesn't look at bugs in this repo.

Closing.

**Comment by debnigra** [comment]
@mccalluc 
Yes, I created the spiceworks label, so that Stephen and I can track any issues that we refer here from the helpdesk.
