### ISSUE TITLE
Expose version number on Status page

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1310]
Right way is probably to keep the version in package.json and read it from there... and update the scripts... but another approach, perhaps simpler, would be to add a webpack plugin so we can read raw files. @john-conroy : Do you have a strong preference between these two, or would you approach it a different way?

**Comment by john-conroy** [comment]
I'd slightly lean towards the former as to not possibly add another dependency in a webpack plugin and further complicate the webpack config, but if you think it's worse to maintain the version number in another place I'm fine with that.
