### ISSUE TITLE
Move search pagination to bottom of table, not bottom of facet list

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1350]

**Comment by john-conroy** [comment]
@mccalluc can you provide a screenshot of this bug?

**Comment by mccalluc** [comment]
@john-conroy : Sorry! Here it is:
<img width="388" alt="Screen Shot 2020-11-12 at 10 59 21 AM" src="https://user-images.githubusercontent.com/730388/98963884-265a8580-24d6-11eb-8989-8ce6304f817e.png">
