### ISSUE TITLE
Mockup QA Section v1.1

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1351]
Figma: https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=1163%3A6145

Current Mockup: 
![Screen Shot 2020-11-06 at 2 04 09 PM](https://user-images.githubusercontent.com/16737715/98419118-3b986580-2039-11eb-812e-d16a5f2bb8bc.png)

**Comment by tsliaw** [comment]
Approved Design: https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=1187%3A6173
<img width="850" alt="Screen Shot 2020-12-07 at 10 22 08 AM" src="https://user-images.githubusercontent.com/16737715/101389296-108e7500-3876-11eb-9f27-63f3a4cfd54f.png">

**Comment by ngehlenborg** [comment]
Sorry for re-opening this, but can we change the section title to "Quality Assurance Information"? Not everything that might end up in there is a report (e.g. the qc_results.hdf5 in the example above).

**Comment by tsliaw** [comment]
Updated Design. [Figma](https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=1163%3A6147) is also updated
![Screen Shot 2021-02-11 at 9 37 40 AM](https://user-images.githubusercontent.com/16737715/107675312-d1e9b200-6c4c-11eb-8aeb-62351d502b4e.png)
