### ISSUE TITLE
Increase spacing between description and creation/modified dates on entity detail pages

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#1369]
<img width="1280" alt="Screen Shot 2020-11-18 at 4 28 33 PM" src="https://user-images.githubusercontent.com/62477388/99590291-261d2700-29bb-11eb-8b23-32b1de06edf9.png">

**Comment by mccalluc** [comment]
Creation date and modification date are now at the bottom, rather than the side, so this is moot. Yay. Closing.
