### ISSUE TITLE
Vitessce Error Snackbar Can't be Read on Dark Visualizations

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#1380]
See below:
<img width="1086" alt="Screen Shot 2020-11-24 at 10 22 26 AM" src="https://user-images.githubusercontent.com/43999641/100114179-24ca7f00-2e3f-11eb-93e6-67e15b58292a.png">
<img width="1087" alt="Screen Shot 2020-11-24 at 10 12 23 AM" src="https://user-images.githubusercontent.com/43999641/100114182-25631580-2e3f-11eb-8b08-056f68aa385b.png">
<img width="1085" alt="Screen Shot 2020-11-24 at 10 12 16 AM" src="https://user-images.githubusercontent.com/43999641/100114188-28f69c80-2e3f-11eb-8fd0-5b56656f8185.png">
Not sure what the best options are - non-transparent background for the snackbar?

**Comment by ilan-gold** [comment]
We use a white background now as of #1371: <img width="1085" alt="Screen Shot 2020-11-24 at 11 25 16 AM" src="https://user-images.githubusercontent.com/43999641/100123662-c3a7a900-2e48-11eb-9d4f-b9cd3f6499f7.png">

**Comment by mccalluc** [comment]
Nils says it looks good.
