### ISSUE TITLE
Suggestion for CCF links from portal user

### ISSUE THREAD

**Issue by debnigra** [hubmapconsortium/portal-ui#1384]
#Hi,

The CCF link in a sample web page (see attached pic) takes the user to the CCF main page. I think it would be an improvement if it directed the user to the CCF site but filtered based on the selected sample metadata.# Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/965

![Screen Shot 2020-11-25 at 7 12 16 PM](https://user-images.githubusercontent.com/3306741/100279458-8fa9b200-2f34-11eb-85a9-90f8854ac350.png)

__Message__:

**Comment by mccalluc** [comment]
I don't believe deep linking is currently possible in the CCF, but it certainly would be nice. Moving issue over to that repo.

**Comment by mccalluc** [comment]
I don't have privs, so opened a new issue. https://github.com/hubmapconsortium/ccf-ui/issues/428

 Closing this one.
