### ISSUE TITLE
On PAS, "+ Add Channel" just brightens image

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1391]
On a [PAS image pyramid](https://portal-prod.stage.hubmapconsortium.org/browse/dataset/1eadf62812799712d4b1232cc92b132f), there is really just an RGB image, but "+ Add Channel" is still available. When I click it there is no dialog to pick a channel, but the image brightens, and with a couple more clicks is just white.

- Probably don't show "+ Add Channel" if the single channel is already being shown? 
- Perhaps this should be filed against Vitessce?

**Comment by ilan-gold** [comment]
Good catch, you can just leave this here and I will resolve it there.  Thanks!
