### ISSUE TITLE
Clarify who can login in UI

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1393]
In the user feedback we got, there was confusion around this, and the [docs are muddled](https://github.com/hubmapconsortium/portal-docs/issues/37).

@tsliaw : Should there be contextual help near the login button that explains that
- login is only useful to hubmap consortium members?
- if you are a consortium member, how to get an account, and who to contact with problems?

**Comment by tsliaw** [comment]
Will look into this and is related to #1190. Thinking of probably:
- Changing wording of "Login" to something like "HubMAP Member Login"
- Adding tooltip to provide contextual help

**Comment by mccalluc** [comment]
@tsliaw : Does this need more design, or can it be implemented from your description?
