### ISSUE TITLE
Implement inside/outside consortium data

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1406]
Design in #1297 

----

- [x] Map the "EXT ..." string to a clean name, and put it in an optional field.
- [x] #2267
- [ ] Separately, add a search facet that includes HuBMAP and external consortia? Default to just hubmap. #2316

**Comment by ngehlenborg** [comment]
Can we implement this in https://github.com/hubmapconsortium/portal-ui/milestone/15? I assume we need that in the API before it can be implement.

**Comment by cebriggs7135** [comment]
@mccalluc calluc Still waiting for Matt R to upload the data & JS to enter the donor metadata I gave him. I'll ping them Wednesday.
