### ISSUE TITLE
Resolve Chuck's comments on datasets search tutorial

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#1413]
The comments are from #1411.

1.
> Little thing: There's still an animation down from the upper left corner of the window... I think it's distracting, but I could be off-base?

Neither Tiffany nor I could reproduce a tutorial tooltip transition animation.

2.
> Bigger thing: I worry that there are steps that read like calls-to-action, but if the user actually does that, the tutorial just exits. Like step 2: "Click the View All button to display the entire list of filters in the selected category." If I actually do that, pouf! -- no more tutorial.

The toggle tile view step no longer instructs or requires the user to click the button and instead relies on a next button. We should revisit the language and whether clicking the highlighted element should end the tutorial.

3.
> Does the library support using the forward and back keys to move through slides?

It doesn't, but since we're using a custom tooltip we could easily add this. Is it the correct decision for accessibility?

4.
> @tsliaw : Is there an idiom for "The End" slides? I read the last slide as another call to action, and when I clicked, the tutorial going away was a surprise.

@tsliaw in response:

> Given that the "Next" button becomes "Last" and (6/6) is displayed, I think what is currently displayed should be good enough for now. We can revisit this later if this becomes an issue.

5.
> Where does the app bar get its z-index from? Should it be added to list?

App bar gets its z-index from MUI. We could overwrite that value if we'd prefer it to come from our code.

**Comment by tsliaw** [comment]
Revising Text for Tutorial:
1. No changes
2. Clicking the "View All" button will display the entire list of filters in the selected category.
3. A period is missing after the last sentence.
4. Clicking the arrow button by the relevant column will sort search results. A bolded arrow indicates the current sorting selection. Clicking again will reverse the order. 
5. Toggling the results display mode will switch between table view and tile view. 
6. Selecting your sorting option in this dropdown menu will sort your search results in tile view.
