### ISSUE TITLE
Spatial view of results: Design

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1440]

**Comment by tsliaw** [comment]
Option A: Toggle On/Off Body Map
<img width="906" alt="Screen Shot 2021-01-25 at 9 48 58 AM" src="https://user-images.githubusercontent.com/16737715/105744905-8e741180-5ef2-11eb-9353-2c547faaf68e.png">

Option B: Body Map Separate Tab
<img width="647" alt="Screen Shot 2021-01-25 at 9 51 07 AM" src="https://user-images.githubusercontent.com/16737715/105745171-da26bb00-5ef2-11eb-8271-410657f2cea8.png">

**Comment by mccalluc** [comment]
@tsliaw : Is there a next step on this? Is it something Nils can make a call on, or is it a collaborative decision with IU?

**Comment by tsliaw** [comment]
We are going with Option A, and after adding small details/annotations on the mockup, I will file implementation issue.

**Comment by mccalluc** [comment]
@tsliaw : Can you link the implementation issue here, and close this?

**Comment by tsliaw** [comment]
Waiting to file implementation issue until after features asked for is provided (highlighting, filtering and zooming to element in body map) so that design can be updated before filing new implementation issue.

**Comment by mccalluc** [comment]
@tsliaw -- Going to take this out of the milestone, since nothing will be delivered before May. When they are able to deliver the component, we can look at what it does, and round out any last bits of the design work.

**Comment by mccalluc** [comment]
- Implementation has been filed: #1441
- Still waiting on IU to deliver component.
