### ISSUE TITLE
table / ccf toggle on dev-search

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1445]
So Bruce can get something merged into master quickly, and then refine it until it's ready to be public.

(If you don't see this being a good way to move forward, feel free to close.)

**Comment by bherr2** [comment]
With dev-search, I'm thinking I'd pass the set of datasets to the component OR it'd pass the query I should call myself to search-api? I may need some assistance getting data to the web component, but once in there I can work things out.

**Comment by mccalluc** [comment]
The former: your component will get a list of search results; actually making the search-api request is a detail handled by the framework, and not something we've had to tweak any details on.
