### ISSUE TITLE
Conduct User Interviews for Molecular/Cellular Query

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1463]
Sub-issue for #1298. Will conduct 10-15 interviews and analyze results.

**Comment by mccalluc** [comment]
@tsliaw : Analysis of results will continue into next week, so this should be move to the next sprint, right?

**Comment by tsliaw** [comment]
Interviews are continuing into next week (last week of interviews) and analysis is ongoing, so should be moved to next spring.

**Comment by tsliaw** [comment]
Last interview scheduled for 3/2. 
Total interviews: 17 
Results summary are in [google drive](https://docs.google.com/document/d/1cFP3WlfraP_FtZrG2KtsMhy61pOpHavLJo7el3okH94/edit?usp=sharing).
