### ISSUE TITLE
Show contributors

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1467]
For incoming datasets multiple contributors, with their ORCIDs, will soon be available. How should this be displayed? File issue for implementation when ready.

**Comment by tsliaw** [comment]
Approved Design: https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=1353%3A7109
<img width="969" alt="Screen Shot 2021-01-21 at 12 42 48 PM" src="https://user-images.githubusercontent.com/16737715/105410073-45684880-5be6-11eb-8ab4-086f081861ca.png">
