### ISSUE TITLE
Assets API outages

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1480]
Bill writes:
> After reviewing with Zhou this afternoon, I don’t think it is load related.  Seems more like it could be a network outage between PSC and AWS.  I’m asking Zhou to get more logging in place so we can track this better, but if it is happening at the junction that Zhou thinks it is there is no way to improve the logging there.  Perhaps we can set up a network monitor specifically between the PSC and AWS where this auth resource sits.  After we improve the logging it will be important for Ilan to still report the issue as it seems like he is the only one seeing (or possibly the only one reporting) the error.

**Comment by mccalluc** [comment]
Is this still an issue? If so, do we have a better understanding of the root cause?

**Comment by yuanzhou** [comment]
Based on @ilan-gold's findings:
> I believe I have a lead on the 500's.  URL length seems to play a factor, and the behavior is different between browsers.  For example [this url](http://vitessce.io/?url=data:,{%22version%22:%20%221.0.0%22,%22name%22:%20%22Spraggins%20Multi-Modal%22,%22description%22:%20%22PAS%20+%20IMS%20+%20AF%20From%20https://portal.hubmapconsortium.org/browse/collection/6a6efd0c1a2681dc7d2faab8e4ab0bca%22,%22datasets%22:%20[{%22uid%22:%20%22A%22,%22name%22:%20%22Spraggins%22,%22files%22:%20[{%22type%22:%20%22raster%22,%22fileType%22:%20%22raster.json%22,%22options%22:%20{%22schemaVersion%22:%20%220.0.2%22,%22usePhysicalSizeScaling%22:%20true,%22images%22:%20[{%22name%22:%20%22PAS%22,%22type%22:%20%22ome-tiff%22,%22url%22:%20%22https://assets.hubmapconsortium.org/f4188a148e4c759092d19369d310883b/ometiff-pyramids/processedMicroscopy/VAN0006-LK-2-85-PAS_images/VAN0006-LK-2-85-PAS_registered.ome.tif?token=%22},{%22name%22:%20%22AF%22,%22type%22:%20%22ome-tiff%22,%22url%22:%20%22https://assets.hubmapconsortium.org/2130d5f91ce61d7157a42c0497b06de8/ometiff-pyramids/processedMicroscopy/VAN0006-LK-2-85-AF_preIMS_images/VAN0006-LK-2-85-AF_preIMS_registered.ome.tif?token=%22},{%22name%22:%20%22IMS%22,%22type%22:%20%22ome-tiff%22,%22url%22:%20%22https://assets.hubmapconsortium.org/be503a021ed910c0918842e318e6efa2/ometiff-pyramids/ometiffs/VAN0006-LK-2-85-IMS_PosMode_multilayer.ome.tif?token=%22}],%22renderLayers%22:%20[%22PAS%22,%22AF%22,%22IMS%22]}}]}],%22coordinationSpace%22:%20{%22dataset%22:%20{%22A%22:%20%22A%22},%22spatialZoom%22:%20{%22A%22:%20-6},%22spatialTargetX%22:%20{%22A%22:%2020000},%22spatialTargetY%22:%20{%22A%22:%2020000},%22spatialRotation%22:%20{%22A%22:%200},%22spatialTargetZ%22:%20{%22A%22:%200},%22cellFilter%22:%20{%22A%22:%20null},%22cellHighlight%22:%20{%22A%22:%20null},%22cellSetSelection%22:%20{%22A%22:%20null},%22cellSetHighlight%22:%20{%22A%22:%20null},%22cellSetColor%22:%20{%22A%22:%20null},%22geneHighlight%22:%20{%22A%22:%20null},%22geneSelection%22:%20{%22A%22:%20null},%22geneExpressionColormap%22:%20{%22A%22:%20%22plasma%22},%22geneExpressionColormapRange%22:%20{%22A%22:%20[0,1]},%22cellColorEncoding%22:%20{%22A%22:%20%22cellSetSelection%22},%22spatialLayers%22:%20{%22A%22:%20null},%22additionalCellSets%22:%20{%22A%22:%20null},%22moleculeHighlight%22:%20{%22A%22:%20null}},%22layout%22:%20[{%22component%22:%20%22spatial%22,%22coordinationScopes%22:%20{%22dataset%22:%20%22A%22,%22spatialZoom%22:%20%22A%22,%22spatialTargetX%22:%20%22A%22,%22spatialTargetY%22:%20%22A%22,%22spatialRotation%22:%20%22A%22,%22spatialTargetZ%22:%20%22A%22,%22cellFilter%22:%20%22A%22,%22cellHighlight%22:%20%22A%22,%22cellSetSelection%22:%20%22A%22,%22cellSetHighlight%22:%20%22A%22,%22cellSetColor%22:%20%22A%22,%22geneHighlight%22:%20%22A%22,%22geneSelection%22:%20%22A%22,%22geneExpressionColormap%22:%20%22A%22,%22geneExpressionColormapRange%22:%20%22A%22,%22cellColorEncoding%22:%20%22A%22,%22spatialLayers%22:%20%22A%22,%22additionalCellSets%22:%20%22A%22,%22moleculeHighlight%22:%20%22A%22},%22x%22:%200,%22y%22:%200,%22w%22:%209,%22h%22:%2012},{%22component%22:%20%22layerController%22,%22coordinationScopes%22:%20{%22dataset%22:%20%22A%22,%22spatialLayers%22:%20%22A%22},%22x%22:%209,%22y%22:%200,%22w%22:%203,%22h%22:%2012}],%22initStrategy%22:%20%22auto%22}) loads its files from the assets API in chrome (i.e the images show up) but not firefox (500 errors in the network tabs).  And [this url](http://vitessce.io/?url=data:,{%22version%22:%20%221.0.0%22,%22name%22:%20%22Spraggins%20Multi-Modal%22,%22description%22:%20%22PAS%20+%20IMS%20+%20AF%20From%20https://portal.hubmapconsortium.org/browse/collection/6a6efd0c1a2681dc7d2faab8e4ab0bca%22,%22datasets%22:%20[{%22uid%22:%20%22A%22,%22name%22:%20%22Spraggins%22,%22files%22:%20[{%22type%22:%20%22raster%22,%22fileType%22:%20%22raster.json%22,%22options%22:%20{%22schemaVersion%22:%20%220.0.2%22,%22usePhysicalSizeScaling%22:%20true,%22images%22:%20[{%22name%22:%20%22PAS%22,%22type%22:%20%22ome-tiff%22,%22url%22:%20%22https://assets.hubmapconsortium.org/f4188a148e4c759092d19369d310883b/ometiff-pyramids/processedMicroscopy/VAN0006-LK-2-85-PAS_images/VAN0006-LK-2-85-PAS_registered.ome.tif?token=%22},{%22name%22:%20%22AF%22,%22type%22:%20%22ome-tiff%22,%22url%22:%20%22https://assets.hubmapconsortium.org/2130d5f91ce61d7157a42c0497b06de8/ometiff-pyramids/processedMicroscopy/VAN0006-LK-2-85-AF_preIMS_images/VAN0006-LK-2-85-AF_preIMS_registered.ome.tif?token=%22},{%22name%22:%20%22IMS%22,%22type%22:%20%22ome-tiff%22,%22url%22:%20%22https://assets.hubmapconsortium.org/be503a021ed910c0918842e318e6efa2/ometiff-pyramids/ometiffs/VAN0006-LK-2-85-IMS_PosMode_multilayer.ome.tif?token=%22}],%22renderLayers%22:%20[%22PAS%22,%22AF%22,%22IMS%22]}}]}],%22coordinationSpace%22:%20{%22dataset%22:%20{%22A%22:%20%22A%22},%22spatialZoom%22:%20{%22A%22:%20-6},%22spatialTargetX%22:%20{%22A%22:%2020000},%22spatialTargetY%22:%20{%22A%22:%2020000},%22spatialRotation%22:%20{%22A%22:%200},%22spatialTargetZ%22:%20{%22A%22:%200},%22cellFilter%22:%20{%22A%22:%20null},%22cellHighlight%22:%20{%22A%22:%20null},%22cellSetSelection%22:%20{%22A%22:%20null},%22cellSetHighlight%22:%20{%22A%22:%20null},%22cellSetColor%22:%20{%22A%22:%20null},%22geneHighlight%22:%20{%22A%22:%20null},%22geneSelection%22:%20{%22A%22:%20null},%22cellColorEncoding%22:%20{%22A%22:%20%22cellSetSelection%22},%22spatialLayers%22:%20{%22A%22:%20null},%22additionalCellSets%22:%20{%22A%22:%20null},%22moleculeHighlight%22:%20{%22A%22:%20null}},%22layout%22:%20[{%22component%22:%20%22spatial%22,%22coordinationScopes%22:%20{%22dataset%22:%20%22A%22,%22spatialZoom%22:%20%22A%22,%22spatialTargetX%22:%20%22A%22,%22spatialTargetY%22:%20%22A%22,%22spatialRotation%22:%20%22A%22,%22spatialTargetZ%22:%20%22A%22,%22cellFilter%22:%20%22A%22,%22cellHighlight%22:%20%22A%22,%22cellSetSelection%22:%20%22A%22,%22cellSetHighlight%22:%20%22A%22,%22cellSetColor%22:%20%22A%22,%22geneHighlight%22:%20%22A%22,%22geneSelection%22:%20%22A%22,%22geneExpressionColormap%22:%20%22A%22,%22geneExpressionColormapRange%22:%20%22A%22,%22cellColorEncoding%22:%20%22A%22,%22spatialLayers%22:%20%22A%22,%22additionalCellSets%22:%20%22A%22,%22moleculeHighlight%22:%20%22A%22},%22x%22:%200,%22y%22:%200,%22w%22:%209,%22h%22:%2012},{%22component%22:%20%22layerController%22,%22coordinationScopes%22:%20{%22dataset%22:%20%22A%22,%22spatialLayers%22:%20%22A%22},%22x%22:%209,%22y%22:%200,%22w%22:%203,%22h%22:%2012}],%22initStrategy%22:%20%22auto%22}) which is slightly shorter but still long displays its image in both browsers properly.

@mccalluc @shirey This inspired me to find the solution. Everything is fine with nginx, it was caused due to the lack of buffer when the big request gets proxied to uWSGI server. I verified on PROD and deployed the fix. Looking good now.

**Comment by mccalluc** [comment]
Closing. Thanks!
