### ISSUE TITLE
Move unused repos to graveyard

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1491]
PK is getting a sense of the landscape: Move the ones that aren't being used to the graveyard. (May need to nudge Bill for some.)

**Comment by pecan88** [comment]
Here is a current list of the suspect repos that may (likely) need to be removed: @mccalluc @shirey @mruffalo 

[collab-website](https://github.com/hubmapconsortium/collab-website)
[metadata-schema](https://github.com/hubmapconsortium/metadata-schema)
[tissue-viewer](https://github.com/hubmapconsortium/tissue-viewer)
[iec-general](https://github.com/hubmapconsortium/iec-general)
[q2-demo-day-map-hubmap](https://github.com/hubmapconsortium/q2-demo-day-map-hubmap)
[ccf-data-wiki](https://github.com/hubmapconsortium/ccf-data-wiki)
[collab-slack ](https://github.com/hubmapconsortium/collab-slack)

I believe @mruffalo can confirm that at least one of these is defunct.

**Comment by mccalluc** [comment]
Notes from Matt on forked repos:
> The SnapTools and cwltool repos are needed, I'm not sure about airflow and metadata-schema
>
> I seem to recall the IEC using a modified version of Airflow, but I've also heard some discussion of them working toward using a "standard" version
>
> Not sure of the status of that though
> 
> The upstream version of SnapTools is more-or-less abandoned, and has some bugs that the author doesn't seem interested in merging PRs to fix
> https://github.com/r3fang/SnapTools/pull/29
> https://github.com/r3fang/SnapTools/pull/31

**Comment by mccalluc** [comment]
Update: 

- collab-website is still in use. Make a PR to explain purpose: https://github.com/hubmapconsortium/collab-website/pull/113
- tissue-viewer is archived in graveyard
- iec-general is deleted
- q2-demo-day-map-hubmap is archived in graveyard
- ccf-data-wiki is archived in graveyard
- collab-slack is archived in graveyard

Several others were also cleaned up. For the forks (like metadata-schema) I'll try to get a note added to the top of the readme to explain how we use it. 

Closing, but this will be an on-going housekeeping task.

**Comment by pecan88** [comment]
@computationdoc @pdblood @khanshawPSC - this issue thread is an example of the documentation organization that Chuck mentioned during the Portal meeting today.  Just FYI for context / specific example.
