### ISSUE TITLE
Make sure semantic IDs don't leak through

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1495]
We could strip those in the UI... or they could be removed earlier in the pipeline. Slight preference for the later, just to be more confident that those internal IDs aren't leaking out... but UI tweak isn't hard.

**Comment by shirey** [comment]
The main issue that @computationdoc is worried about is the fact that these "submission ids" are in metadata.tsv files that are downloaded with a dataset.

**Comment by ngehlenborg** [comment]
Maybe they should be striped from the metadata.tsv upon ingestion?
