### ISSUE TITLE
Mockup: Sample details

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#15]
Sample is one of the [basic types](https://github.com/hubmapconsortium/hubmap-data-portal/issues/138#issuecomment-537116792): It needs a details page.

Nils should give requirements, and we should confirm that the API will have the information necessary.

Deliverable is a mockup which has approval from Nils. File a new issue for implementation when this is complete.

**Comment by tsliaw** [comment]
Sample detail mockup is in the Figma file.
