### ISSUE TITLE
Clean up prov issues

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1507]
Roadmap is provide more of the information the table provides through the graph, or other means. There are a lot of old issues that may not be on this path: Close them.
```
Determine how to collapse and skip provenance graph nodes
Create plan for provenance graph revision
Improve provenance table rendering time slow connections
Lack of clarity on which datasets belong to the same experiment
Update sample hierarchy in provenance table
Update provenance table tiles with mapped fields for ancestors
Provenance: Collapse nodes with lots of multiples (Hard?)
In react, use prov-vis directly 
```

**Comment by john-conroy** [comment]
I've pruned older issues with a focus on provenance table issues since updating the table won't be a focus. I've also created a provenance git label to better organize these issues.
