### ISSUE TITLE
Redesign Homepage

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1513]
Features/user feedback about homepage to consider: 
- Showcases on homepage
- Select Vitessce visualizations (e.g. slideshow) 
- Summary statistics (if available)
- Newsfeed
- Redesign/relocate bar chart
- Faster/increased navigation to the data

**Comment by mccalluc** [comment]
Copying over requirement from #1568: Links to Software, Protocols, and Publications should be in new homepage... footer would be fine.

**Comment by tsliaw** [comment]
Approved design: ([Figma](https://www.figma.com/file/cEZdI2tOMByTBW8RQ2kuAm/Home-Page?node-id=755%3A44))
![Click on Search Menu](https://user-images.githubusercontent.com/16737715/112409998-b48e1600-8cd7-11eb-9019-961acf8f53ff.png)
