### ISSUE TITLE
Could the inital ome-tiff transfer for CODEX be smaller?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1516]
![image](https://user-images.githubusercontent.com/730388/107044744-b84ef300-6792-11eb-8866-7f58787bbdb3.png)

If there's something that could be done to enhance the pipeline so it would take less data transfer for the first render, great, but that might not be feasible.

cc: @ilan-gold

**Comment by ilan-gold** [comment]
FWIW I think this is a bug in Vitessce but would need to confirm to be sure.  I don't see this behavior in Avivator @ngehlenborg

**Comment by ilan-gold** [comment]
This is definitely a Vitessce bug and can seen with Zarr stores as well:

<img width="1680" alt="Screen Shot 2021-02-10 at 1 23 26 PM" src="https://user-images.githubusercontent.com/43999641/107553928-410acc00-6ba3-11eb-89ae-2cd73b79bdda.png">

**Comment by mccalluc** [comment]
Update from Ilan:
> This one I actually did address to some degree but it didn’t actually speed anything up so I left it open.  I can leave a note that nothing materially changed, or we can close because the transfer is technically smaller.

Chuck:
> No worries — It sounds like it’s something that still isn’t ideal… but we also don’t have any good ideas for how to fix it right now… so I think I won’t carry it to the next sprint, but keep it open?

**Comment by ilan-gold** [comment]
Sounds good @mccalluc
