### ISSUE TITLE
Freshen the manual QA process

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1535]
It should reflect what we actually check. 
- Less emphasis on the Homepage, 
- add coverage for My Lists,
- perhaps move to git?

**Comment by mccalluc** [comment]
@john-conroy - Looks like you trimmed some of the details at the top, and started the "My Lists" section, but didn't fill it in. Please close this when you've wrapped it up - Thanks!

**Comment by john-conroy** [comment]
We've updated the manual qa process and included it in the repo as of #1621.
