### ISSUE TITLE
Ilan Tracker Task

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#1547]
- [x] Replace the portal backend for Vitessce
 - See: https://github.com/vitessce/vitessce-python/pull/45 for the current progress

**Comment by mccalluc** [comment]
@ilan-gold - linked issue is closed, but is there work still to be done to pull that code in to the portal?

**Comment by ilan-gold** [comment]
The PR here is almost ready, so that should be merged by EOD tomorrow and if not, soon after.  I think it's ok to close this issue.
