### ISSUE TITLE
React in docker should work by design, not by accident

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#155]
Follow-up to #152.

If you build by hand, there is a `static/public/bundle.js` and the react code works in docker... except it shouldn't.
- Add a docker ignore so files which are built during local development aren't accidentally incorporated in the image.
- Add npm steps to the docker file so that assets like this a built as part of the image.
- ... and once that's working and merged, tidy it up by using a multi-stage build: We shouldn't need node_modules at run time, etc.

(Assigning @jkmarx ... but just as another possible option for the next couple days: Testing would also be good.)

**Comment by jkmarx** [comment]
I believe #159 will resolve this issue also.

**Comment by mccalluc** [comment]
This still needs to happen, unless I'm confused. 

>   Add a docker ignore so files which are built during local development aren't accidentally incorporated in the image.

app/static/public is git-ignored, but not docker-ignored.

**Comment by john-conroy** [comment]
I'll take a look once I'm finished with the react details page.
