### ISSUE TITLE
Should hitting "return" save changes in modal?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1561]
@tsliaw : I'm expecting hitting "return" to work the same as hitting "save" in the "Edit Saved Status" and "Add To" modals: Does that sound right to you?

**Comment by john-conroy** [comment]
@mccalluc It should probably only save if they focus the submit button. Otherwise it would probably be an accessibility issue.

**Comment by mccalluc** [comment]
I haven't made myself comfortable with this. [One SO thread](https://stackoverflow.com/questions/57064691/is-implicit-submission-submit-on-enter-key-useful-to-people-using-readers-and): users of screen-readers expect return to submit. 

@john-conroy - Do you think the situation here is different than that thread? Or do you think that is a minority view?

(Probably easier to talk through it again start a conversation here.)

**Comment by john-conroy** [comment]
> For <textarea>, pressing enter usually produces a new line, and implicit form submission doesn't happen. For <input type="text">, pressing enter causes implicit form submission.

The description is a text area so no implicit submission there. I can make it so that when the title input is focused and the submit button is not disabled, enter will submit?

**Comment by mccalluc** [comment]
@john-conroy -- We talked yesterday: I don't think there are outstanding questions? I'll remove `design` and move into `backlog`... feel free to move to `v0.13` if it seems easy.
