### ISSUE TITLE
Change Portal Documentation drop down to include Software

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1567]
May we please add the following item to the drop down menu and have it link to the to-be-loaded markdown page that will cover a list of software products?  "Software"  @schwenk102 will provide the link here once the markdown page is generated in the HuBMAP GitHub organization > Documents repository.

After the change, the Dropdown menu would look like:

Documentation
>    Overview
>    Software
>    FAQ
>    About

I am including @computationdoc & @shirey on this request for reference and assume this will need review by @mccalluc & @ngehlenborg

**Comment by schwenk102** [comment]
Here is the software markdown page: https://github.com/hubmapconsortium/portal-docs/blob/master/software.md

**Comment by mccalluc** [comment]
This is feasible: Put in backlog.

**Comment by mccalluc** [comment]
@tsliaw : This is easy, and doesn't add too much clutter. I'd suggest that a new software link is not also needed elsewhere (#1568), but I'll defer to you. Moving into next milestone.
