### ISSUE TITLE
Add the Products (software), Protocols, and Publications as first class citizens to web navigation

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1568]
May we please incorporate into the Portal navigation links to the following key outputs & measured outcomes of HuBMAP to demonstrate our success and disseminate our products?

1. Products [Software in this case and would link to [our GitHub repository ](https://github.com/hubmapconsortium)or the Software page that is currently under development in markdown]
2. Protocols [link to [HuBMAP organization in protocols.io](https://www.protocols.io/workspaces/human-biomolecular-atlas-program-hubmap-method-development)]
3. Publications [link to either a Google scholar page that will be created by @schwenk102 & Jesse Helfer OR to whatever the current listing of published works are for the consortium]

Including @computationdoc & @schwenk102 & @JAH386 for awareness.  Review needed by @mccalluc & @ngehlenborg .

**Comment by mccalluc** [comment]
@pecan88 : Please clarify: Are you asking for these links in a particular place (homepage, header menu, ...), or is the design task on our end, and it's up to us where it goes? Software is already covered in #1567... Do you want something else?

**Comment by pecan88** [comment]
@mccalluc - I can suggest locations and I completely defer to the design sensibilities that are not mine!  :)  (I'd imagine you, Tiffany, Nils and run by some of the HIVE PIs?)  (You da man!)

**Comment by mccalluc** [comment]
@tsliaw -- This is coming in late, but could this information be part of the homepage redesign you're working on now?

**Comment by tsliaw** [comment]
This can be done, most likely will be placed in the footer

**Comment by mccalluc** [comment]
@tsliaw : I believe this is subsumed in the homepage redesign (#1513), so I'll add a comment there, noting that we want these links, but this issue can be closed, I think.
