### ISSUE TITLE
ccf menu

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1571]
in HuBMAP Portal, pease rename ‘CCF’ into ‘CCF Atlas’ with submenus
- Common Coordinate Framework (CCF) Portal // links to this site 
- CCF Anatomical Structures, Cell Types and Biomarkers (ASCT+B) Tables/Reporter
- CCF Registration User Interface
- CCF Exploration User Interface

cc @bherr2

**Comment by bherr2** [comment]
Links for the submenu items (respectively):
* https://hubmapconsortium.github.io/ccf/
* https://hubmapconsortium.github.io/ccf-asct-reporter/
* https://portal.hubmapconsortium.org/ccf-eui
* https://hubmapconsortium.github.io/ccf-ui/rui/
