### ISSUE TITLE
Resolve first node in prov graph

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#1574]
Seen in #1570.

```function getNameForEntity(id, prov) {
    const entity = prov.entity[id];
    // NOTE: The initial entity node was not included in the sample data;
    // Fallback to ID, if needed. https://github.com/hubmapconsortium/prov-vis/issues/15
```

From @mccalluc:

> That repo is archived, so this has fallen off the radar. Could you ...
> 
> Confirm that the referenced entity is still not included in the API response...
> If it's not, ping Bill on Slack and ask if this is something they might fix...
> if so, make sure there's a tracking issue on their side,
> if not, make an issue on our side to strip out the useless node before rendering.

**Comment by mccalluc** [comment]
@john-conroy - I think this is outdated, and what we really want is to just start the graph with `Donor`? That is #1609 -- I've added it to the milestone, and I'll close this one. If I'm confused, let's talk. Thanks!
