### ISSUE TITLE
Is the footer on the portal maintenance page different from the regular footer on purpose?

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1577]
Several links (including the whole software category) are missing:

Default footer:

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/1216518/108844186-c631b000-75a9-11eb-82cb-03b6e865eac0.png">

Maintenance page:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1216518/108843903-53c0d000-75a9-11eb-8576-1109fba109b1.png">

**Comment by john-conroy** [comment]
This was part of the design, @tsliaw?

**Comment by tsliaw** [comment]
I believe that was part of the design since the other links are links to around the portal, which won't be accessible if the portal is doing maintenance.

**Comment by john-conroy** [comment]
@ngehlenborg do you want us to make the footers identical?

**Comment by ngehlenborg** [comment]
> I believe that was part of the design since the other links are links to around the portal, which won't be accessible if the portal is doing maintenance.

That's what I was wondering about and I think that is the right approach.

Let's add the software section and the GitHub link but not the services link.

Low priority.
