### ISSUE TITLE
include full bibliographic citation information on collections landing pages

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1578]
@tsliaw: please design a separate "Citation" section to go between the header and the contact section, and file an implementation issue when complete.
- DOI line is to be removed (was #1580)
- best practices for landing pages: https://support.datacite.org/docs/landing-pages

**Comment by tsliaw** [comment]
Proposed mockup: [Figma](https://www.figma.com/file/W2HtnD1g9FAknOt9YFPyVK/Collections?node-id=708%3A1901)
Screenshot 1: Without hover help text
![Screen Shot 2021-03-26 at 2 00 35 PM](https://user-images.githubusercontent.com/16737715/112692116-a48f4700-8e3b-11eb-807c-d7453096ed43.png)

Screenshot 2: With hover help text
![Screen Shot 2021-03-26 at 2 00 17 PM](https://user-images.githubusercontent.com/16737715/112692088-99d4b200-8e3b-11eb-9f46-49cca6866d6a.png)

**Comment by tsliaw** [comment]
Approved Design. [Figma](https://www.figma.com/file/W2HtnD1g9FAknOt9YFPyVK/Collections?node-id=708%3A1901)
![Screen Shot 2021-04-05 at 12 52 00 PM](https://user-images.githubusercontent.com/16737715/113619356-b88e3200-960d-11eb-8407-fdd1179b6939.png)
