### ISSUE TITLE
create "Collections" section for dataset pages

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1579]
Each dataset page should have a section that lists all collections that the dataset is part of. This should include the title of the collection and the DOI.

We can resuse the collection list design from the Collections overview page:

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/1216518/108845921-01cd7980-75ac-11eb-84ba-f3b71d48b276.png">

**Comment by john-conroy** [comment]
@tsliaw if this is just the same section with a 'Collections' header, just let me know where on the page it should go?

**Comment by tsliaw** [comment]
@john-conroy This should just be a list section of the collections with a "Collections" header, I would put this at the bottom of the detail page after the "Files" section, but before the upcoming "Contributors" section, which I don't think is implemented yet. Let me know if you need a mockup.

**Comment by tsliaw** [comment]
[Figma](https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=1353%3A7109) to see position of collection section for your reference
