### ISSUE TITLE
remove DOI link at top of collections pages 

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1580]
The DOI link at the top of a collection page links to the page itself (via DOI resolver):

<img width="511" alt="image" src="https://user-images.githubusercontent.com/1216518/108846471-99cb6300-75ac-11eb-826d-0beb96ea6ac2.png">

Let's remove this (information will be replaced/enhanced in #1578) and not include a link to the DOI. We could link to the corresponding DataCite page (e.g., https://search.datacite.org/works/10.35079/hbm237.xggl.844), which provides an easy way to get citation information formatted for different citation styles (I don't see any other benefits than that).

**Comment by john-conroy** [comment]
Do you want the text to be the URL or something different?

**Comment by ngehlenborg** [comment]
We can leave this as is until #1578 has been implemented and then remove this completely.

**Comment by mccalluc** [comment]
I'm just going to combine this with #1578 since they will be done at the same time, so there's one less issue to track.
