### ISSUE TITLE
HuBMAP members with multiple Globus accounts might get confusing error pages when logging in

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1607]
Users who have multiple Globus accounts (I ended up with a second one when testing something) who should have member access but are logged into their non-HuBMAP Globus account do get an error page with no indication about what is wrong. 

The error page should tell the user which globus account their are logged into an offer the option to log out of that account and log back in with the correct account for the HuBMAP portal. At a minimum, the error page should include a link to http://app.globus.org/.

This is also related to #1575.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1216518/110472153-01a0a400-80ab-11eb-81c7-11566932d993.png">

**Comment by mccalluc** [comment]
@ngehlenborg: Would it be acceptable to just update the message, but not get into the logic? I'm not sure we get enough information back in the 401 response to really know what's going on, and even with a reproducer, there would probably be edge cases we'd miss.

Proposal: update text to:
> Could not confirm your Globus credentials.
> - You may not have been added to the HuBMAP Group on Globus. Request access at help@hubmapconsortium.org.
> - Or, you may be logged into a different Globus account from the one in the HuBMAP Group. Check http://app.globus.org/ for details on your account.

**Comment by mccalluc** [comment]
(Please add this to the next milestone if a text update will be sufficient.)
