### ISSUE TITLE
Prov-vis: Make activity nodes smaller, just use icons

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1610]
@tsliaw : Not sure if a separate design task is needed, but if you have ideas have the best icons for these, that would be useful.

**Comment by john-conroy** [comment]
Probably won't be able to do this without making fundamental changes to the workflow viz library we depend on. We can change the representation of the node from portal-ui, but we can't change the starting placement of the following arrow/edge or subsequent nodes.

**Comment by john-conroy** [comment]
We could change the size of all nodes, but not some of them.

**Comment by john-conroy** [comment]
Closing, we will explore removing activity nodes altogether.
