### ISSUE TITLE
Possible parsing error

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/portal-ui#1619]
The provenance graph on PROD https://portal.hubmapconsortium.org/browse/dataset/ead5cc01250b4f9ea73dd91503c313a5 doesn't render the Activity correctly. 
![image](https://user-images.githubusercontent.com/195873/110688180-4d3c7600-81af-11eb-8c35-6ecec69936c6.png)

However, it renders correctly on TEST (which is good, since we will be releasing the version on TEST):  https://portal.test.hubmapconsortium.org/browse/dataset/ead5cc01250b4f9ea73dd91503c313a5
![image](https://user-images.githubusercontent.com/195873/110688346-7a892400-81af-11eb-905a-1797225f3542.png)

**Comment by mccalluc** [comment]
It looks fine on production now. I expect John fixed this as some point.
<img width="273" alt="Screen Shot 2021-04-30 at 10 26 04 AM" src="https://user-images.githubusercontent.com/730388/116709334-92ef1100-a99e-11eb-837b-a18003e36d0d.png">
