### ISSUE TITLE
Investigate Integrative Visualization of Multiple Datasets

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#1622]
Opening this issue to track what is needed for this.  Will be discussed further at the next UI meeting.

**Comment by ilan-gold** [comment]
Two (main) scenarios:
- vanderbilt use case: AF + PAS + IMS, but how do we know they’re are aligned?
    -  Very hard to correctly line up the vanderbilt data…. requires their filename conventions.
- scRNAseq: only makes sense with cell type, nothing connects them.
- Biggest issue:  we don’t actually have data that people could combine.

**Comment by mccalluc** [comment]
Consolidating this with #1641. Closing.
