### ISSUE TITLE
Maybe my-lists should be in the banner, evenin mobile layout?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1624]
@tsliaw - I'm wondering if it would make sense to keep "My Lists" in the banner, even in mobile layout? There would be enough room, I think, and being at the bottom on the pulldown menu it can get lost.

Really minor point, and I'm not sure it would be an improvement.

Just give this a quick thumbs-up or -down. Thanks!

**Comment by tsliaw** [comment]
I think it might clutter the header too much in narrow layout, especially for mobile. I think the issue of "My Lists" being at the bottom of the pulldown menu might get better when/if we get around to cleaning up the amount of things in the header.
