### ISSUE TITLE
Implement v1.0 of Antibody Table

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1631]
#1468 references this design. [Figma](https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=1353%3A7109)
Full table view:
![Screen Shot 2021-03-11 at 11 01 55 AM](https://user-images.githubusercontent.com/16737715/110840121-34889a80-8259-11eb-9a47-4836ee086675.png)

Positioning on dataset detail page. 
![Screen Shot 2021-03-11 at 11 02 17 AM](https://user-images.githubusercontent.com/16737715/110840162-423e2000-8259-11eb-905b-548a57293751.png)

**Comment by john-conroy** [comment]
Data unavailable through APIs for now.

**Comment by mccalluc** [comment]
Contractors have delivered code to IEC; Waiting for Bill to deploy.

**Comment by mccalluc** [comment]
IEC went ahead an implemented a UI as well as an API. In their court. Closing wont-fix.
