### ISSUE TITLE
Test every execution path in build_vitessce_conf

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1639]
#1638 along with earlier bugs suggest our QA on this was inadequate. For every execution path build_vitessce_conf, we need to identify a dataset to exercise it, and make sure it not only doesn't throw an exception, but that the visualization is what is desired... and expand the test suite to capture the current error, and make sure we have a strategy to keep the test suite up to date.

**Comment by mccalluc** [comment]
> Furthermore I added "malformed" tests for each assay in response to #1639 

@ilan-gold : Is more work needed here, or can we close it?

**Comment by ilan-gold** [comment]
Closing! Thanks for opening!
