### ISSUE TITLE
scRNA-seq (10x Genomics) [Salmon] should have vis?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1644]
Joel believes this should have a visualization. Requires login: https://portal.test.hubmapconsortium.org/browse/dataset/99d1d2779907fed926f32413cae814af 

(I think this is one that used to error before #1640.)

**Comment by mccalluc** [comment]
@ilan-gold , before we lose context, can you add your thoughts here? Should there be a vis for this? Is there work in progress?

**Comment by ilan-gold** [comment]
#1669 is the "fix"
