### ISSUE TITLE
Better Error Reporting to Remove Try-Catch in Vitessce Configuration Generation

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#1645]
Re #1637's aggressive try-catching to prevent 500 errors during Vitessce configuration-generation: 

> then, separately, a bigger PR to return {} even if there is an error...but don't think that should be left in forever. If we had better error reporting, perhaps, but I don't think we can rely on IEC to grep the logs on an on-going basis for us, and having silent failures is worse than noisy failures. (The NIH has signed off on the idea that this is "research-quality" software, so I don't think we should sweep problems under the rug.)

**Comment by mccalluc** [comment]
We have cloudwatch now, so this should be actionable.
