### ISSUE TITLE
Redesign provenance graph detail pane

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#1653]
- What information is available for a node? 
- Differentiate the background.
- Include a notice that more information is available.

**Comment by mccalluc** [comment]
@tsliaw : I think the one action item was to move the button to the right -- Can you link to the design and close this?

(For the record, Chuck and John both found the use of a single tile here odd, but it has buy-in from Nils, and that's enough.)

**Comment by tsliaw** [comment]
Approved Design: [Figma](https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=1503%3A8855)
![Screen Shot 2021-04-06 at 1 51 23 PM](https://user-images.githubusercontent.com/16737715/113776922-4be36800-96df-11eb-9cd5-94ce5c6a74ad.png)
![Screen Shot 2021-04-06 at 1 51 31 PM](https://user-images.githubusercontent.com/16737715/113776940-50a81c00-96df-11eb-9be1-153c9db41851.png)
![Screen Shot 2021-04-06 at 1 52 36 PM](https://user-images.githubusercontent.com/16737715/113776974-5b62b100-96df-11eb-9652-3477ca3c901c.png)
