### ISSUE TITLE
Should Sample-Datasets table columns match search?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1656]
Is there a reason for the headers on the two tables to be different? Unless there's a reason, I think `Group` should be added, `Organ Type` should be `Organ`, and `Derived Dataset Count` should be removed, and the order should be:

> HuBMAP ID Group Data Types Organ Status Last Modified

<img width="829" alt="Screen Shot 2021-03-19 at 11 19 01 AM" src="https://user-images.githubusercontent.com/730388/111803631-983c4480-88a5-11eb-9a62-669a31f52f30.png">

... but if this is intentional, great! Just close this.

**Comment by tsliaw** [comment]
Good catch, no this wasn't intentional. I'll fix the design and change this issue to an implementation issue when I finish. 

The reason I didn't include group column was because I thought if we're on a sample page, the attribution should have always just be one group right?

**Comment by mccalluc** [comment]
> The reason I didn't include group column was because I thought if we're on a sample page, the attribution should have always just be one group right?

They'll probably all be from the same organ, too, which could be inferred from the Sample's organ in any case... I don't really care strongly, but I think it would be good to articulate the guiding philosophy here: Is it to mirror the search interface? Or economically present information that will be of the most use in this context? 

I started out thinking consistency should be the goal... but I'm now inclining towards the second option... but I'll leave it to you.

**Comment by tsliaw** [comment]
Changing this to implementation issue. Columns should be arranged like this:
![Screen Shot 2021-03-31 at 9 37 53 AM](https://user-images.githubusercontent.com/16737715/113179722-c6eedf00-9204-11eb-836d-1731b91c6852.png)

**Comment by mccalluc** [comment]
@tsliaw -- One small point: You have the left-most column labelled "Dataset"... on search right now (and in this code) it's "HuBMAP ID".

This is ringing a very faint bell... do we uniformly want that first column to be the entity type, ie, Donor, Sample, or Dataset?

**Comment by tsliaw** [comment]
I think we decided on "HuBMAP ID" in a meeting a while back if I remember correctly, so change the "Dataset" to "HuBMAP ID".
