### ISSUE TITLE
upgrade commons to v2.0.2

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1660]
Believe it just loosens constraints, so shouldn't cause problems.

see also https://github.com/hubmapconsortium/ingest-validation-tools/issues/629

**Comment by yuanzhou** [comment]
I'm curious which module or dependency in commons is being used by portal-ui?

**Comment by mccalluc** [comment]
@yuanzhou 
```
from hubmap_commons.type_client import TypeClient
from hubmap_commons.singleton_metaclass import SingletonMetaClass
```

Ilan uses the information about assays from the `TypeClient` to help construct vitessce configs for those clients.
