### ISSUE TITLE
"donor is undefined" on unpublised DART-FISH

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1675]
Point at production, login, and visit http://localhost:5001/browse/dataset/57921b6bda5396fc8afde7e24d0e08ad

```
Uncaught TypeError: donor is undefined
    getDatasetLD schema.org.js:4
    setJsonLD schema.org.js:39
    jsx index.jsx:22
```

(This is the code that adds metatdata in the header: No obvious problems in the visible part of the UI.)

Is the data bad? The assay name is certainly weird... or is this a case the UI will need to handle? I'll ping @shirey .

**Comment by mccalluc** [comment]
```
  const donor = entity.donor.mapped_metadata;
```
`entity.donor` exists, but the `mapped_metadata` is empty... because there is no `metadata`, so there's nothing to do at index-time.
 
- Is this an error?
- If so, should something have caught it before render-time?

**Comment by shirey** [comment]
Not an error and nothing to catch that I know of.  In general (though, there may be a case or two that I don't know about), published/public data will always be connected to a donor who has metadata.  BUT- it will often be the case for pre-published information that the donor and sample metadata hasn't been collected, transformed or imported yet.

Upcoming information coming from external consortia may not have any donor information.  Not sure a plan was ever settled for that.
