### ISSUE TITLE
Implement new {Tools,Atlas,...} menu

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1689]
Nils:
> ... Unless the response from Katy and Rahul is controversial, just go ahead ...

Rahul:
> my preference is for Tools (or 'Mapping Tools') instead of Atlas. Thanks!

Katy:
> The ASCT+B tables are not a tool but the begin of an Atlas CCF reference system.
> What about “Atlas & Tools”?

![Screen Shot 2021-03-30 at 11 22 17 AM](https://user-images.githubusercontent.com/730388/113042341-0f58bf00-9169-11eb-8ad6-bb28da002e06.png)

Replaces #1630 

Azimuth is: https://azimuth.hubmapconsortium.org/

**Comment by ngehlenborg** [comment]
Menu name: "Atlas & Tools"

Sections:
1. CCF related tools
-----------
2. Azimuth
