### ISSUE TITLE
Clarify usage of identifiers once and for all! :)

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#170]
There are three different locations where I use IDs:
- Metadata TSVs
- Portal URLS
- Displayed in the body of the Portal pages.

There are three different kinds of IDs I am aware of:
- UUIDs: 32 digit hexadecimal
- HuBMAP Display IDs: ABC123-LK-1-1-1 (embedded semantics!)
- HuBMAP Display DOIs: HBM:123-ABCD-789

(Are these the correct names?)

Which should be used where? I think @ngehlenborg should re-state his preferences, and then @shirey can say if there is a technical reason we can't do it that way.

Context: Nils [wrote](https://github.com/hubmapconsortium/ingest-validation-tools/issues/108#issuecomment-611040592):
> Sorry for being nitpicky here but I think identifiers are extremely critical because people will use them to reference data: does everything that has an "ABC123" (for Donors) or "ABC123-LK-1-1-1" (for Samples) identifier also a HuBMAP identifier (HBM...)?
>
> If there is such an identifier, we would want to display those on the portal and generally would want to use them for public consumption.
>
> In essence, my question is if we could just use the HuBMAP identifiers (assuming they exist) for everything to avoid confusion (even if that is just at the level of submitters).

### Other ID Issues

- [Can the UUID be the ES `_id`?](https://github.com/hubmapconsortium/search-api/issues/23)
- [`display_doi` are not unique, and inconsistently formatted](https://github.com/hubmapconsortium/search-api/issues/11)

**Comment by ngehlenborg** [comment]
My policy for HuBMAP (and everything else): No semantics in IDs that are shared with the public.

- URLs: let's use UUIDs for now, we can introduce vanity URLs later if necessary.
- "HuBMAP Display IDs: ABC123-LK-1-1-1" - only internally for submission
- "HuBMAP Display DOIs: HBM:123-ABCD-789" - for everything that is facing people who are not submitters, that includes people within HuBMAP

@shirey: can we agree on this?

**Comment by ngehlenborg** [comment]
@shirey: can you comment on the above?

**Comment by shirey** [comment]
@ngehlenborg This seems reasonable.  My main concern is that we not show the full 32 character UUIDs to any users.

**Comment by ngehlenborg** [comment]
We can display them on the entity detail pages but for search results etc. I would prefer to use the human-readable HuBMAP IDs.

**Comment by ngehlenborg** [comment]
Policy discussed and agreed during 5/1/2020 Portal Call:

**only displayed to submitters and curators**
Lab Internal: ???
HuBMAP Display IDs: ABC123-LK-1-1-1 (<- embedded semantics)

**displayed to public**
*HuBMAP ID* - use in overviews, detail views: HuBMAP ID: HBM:123-ABCD-789 (<- DOI suffix)
*DOI* - use in details views: doi:10.xxxxx/HBM:123-ABCD-789

**used for internal referencing**
*UUID* - use in detail views: UUIDs: 32 digit hexadecimal

**Comment by mccalluc** [comment]
Usage of identifiers clarified, so I'll close this.

Open new issues as we see parts of the UI that need tweaking.
