### ISSUE TITLE
log aggregation / log monitoring

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1707]
mccalluc:
> Is there log monitoring in place? I think we would want to know if these were being hit... Can your log monitor aggregate errors and send them to us once a day, or something like that?

shirey:
> we can add log monitoring  for the portal via AWS Cloudwatch as we do with other services, but I think to do that we may need to explicitly write portal logs to a file. Right now I think the only way to get to the portal logs is via "docker log", which I don't think we can monitor.
>
> Looking for an agent to monitor Docker logs and not finding anything.  Docker logs do produce a file, but the location/name changes I think.

_Originally posted by @shirey in https://github.com/hubmapconsortium/portal-ui/issues/1692#issuecomment-812638621_

There are many options for [configuring log drivers with Docker](https://docs.docker.com/config/containers/logging/configure/), including logging straight to [AWS CloudWatch](https://docs.docker.com/config/containers/logging/awslogs/). These options are not available if you take an idiosyncratic approach to logging, like writing to a mounted file, but the portal container follows Docker conventions, so this is not a problem.

The motivating user story is that Portal developers either need to be notified about warnings in the logs, or they need a way to look for failures retrospectively. Access to aggregated logs is a basic element of a microservices architecture.

**Comment by yuanzhou** [comment]
I've successfully set up the Docker log forwarding to AWS CloudWatch log group, across DEV/TEST/STAGE/PROD for portal-ui. Please coordinate with @khanshawPSC  to create your SSO for the NIH.OD.CommonFund.HuBMAP.Harvard AWS account (178091070370). Once you have the access, go to **CloudWatch -> Logs -> Log groups -> portal-ui-logs**, you'll see the log streams for each deployment based on domain name.

![image](https://user-images.githubusercontent.com/195873/117207583-1b681a00-adc2-11eb-88b6-c09d1a61fcfc.png)


All the setup is using this IAM `docker-awslogs-driver-policy` policy and the `docker-awslogs-driver-user` user, please don't make changes to them.

![image](https://user-images.githubusercontent.com/195873/117207654-320e7100-adc2-11eb-9f10-335988dda1b5.png)

![image](https://user-images.githubusercontent.com/195873/117207677-376bbb80-adc2-11eb-8c7e-44ae1b29588c.png)
