### ISSUE TITLE
Implement Citation section on Collections page

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1709]
See design in #1578

**Comment by mccalluc** [comment]
Just talking with Jonathan, he strongly desires that citations be in NLM format ... (which may already be the case in your design, I haven't checked) ... There will still be matters of interpretation: https://www.nlm.nih.gov/bsd/policy/cit_format.html

**Comment by tsliaw** [comment]
It's currently in APA, I'll update the design to NLM

**Comment by tsliaw** [comment]
Figma mockup is now updated to NLM. FYI, the DataCite page does not have NLM, but it appears the Vancouver citation is identical to NLM.
