### ISSUE TITLE
Standard titling

### ISSUE THREAD

**Issue by JAH386** [hubmapconsortium/portal-ui#1722]
One option could be display titles auto-generating based on the values you indicate below

For example -  Unbiased scRNASeq of cryopreserved cells obtained from 1 cubic centimeter of spleen from 18 yo M donor 

14 parameter CODEX imaging of FFPE spleen from 18 yo M donor

Inclusion of VIP data providers into the discussion

**Comment by mccalluc** [comment]
@shirey -- I believe the conclusion was that you would generate the names on your side, and include in the Entity JSON? I've filed #1723 for all aspects of making good landing pages, and this is a trivial portion of that, when the data is available.

Closing, but reopen if I've misunderstood, and it really is the responsibility of the portal to construct names. (We actually are doing that already, in metadata for web spiders, so it's not a big ask, if the plan needs to change.)
