### ISSUE TITLE
Faceted search counts text too light

### ISSUE THREAD

**Issue by schwenk102** [hubmapconsortium/portal-ui#1730]
## Feedback

__Help Desk Issue Tracker URL__: #1235 for helpdesk

__Message__: Faceted search counts text too light

Hi:

I compared on several systems and monitors with several people and all agreed:

Faceted search counts have text that is way too light in color - barely readable on white background

Applies to Donors Samples and Datasets pages.

Thanks,

JCS

**Comment by mccalluc** [comment]
@tsliaw - looking at [figma](https://www.figma.com/file/pkIZbpJOAQnylo1zjyhaU6/Search-Page?node-id=1064%3A17825) it looks like the counts should be the same weight as the strings. Not sure where the discrepancy came from.

I'll put this in the next milestone.
