### ISSUE TITLE
MALDI IMS Vitessce config doesn't conform to schema

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1732]
On https://portal-prod.stage.hubmapconsortium.org/browse/dataset/72d7f6895a34be4e0f43df278c675da2 (v0.16.1)
- Turned on dark mode
- zoomed in
- saved link
- followed [link](https://portal-prod.stage.hubmapconsortium.org/browse/dataset/72d7f6895a34be4e0f43df278c675da2#vitessce_conf_length=2436&vitessce_conf_version=0.0.1&vitessce_conf=N4Igxg9hBOAmCWA7AhgF3hRBlADssApiAFyixrIDOBqJoAgiSIwL4A0Ile6yANgFpQAtnWYkAtAAYAdACYArADYALJOWLFARgCc2zQHZNmhe07d4fAEoRUaDIlGNik01zt8AKsmgBzGgA1HEkV9eWllbXl9bWUAZljFeWNY13NPbz9UAE0g4mMNcOV9WVVDAA55ZTKUjjceXi9fGn5c2OlNatlYzWUlWUl5Eu0CcWNTQl5eADF4XlQCaFzEAFdJ8YJJgAl4HwALXh3d2lIxYhW1jgneLBob3gIwdEwl1d51yZvUbb2DveOGEjnN6XDbXGgAYQgvBgLwuID8iAI332h3+pyBpgRBDuDyeDhOTgxHCxAFEAB44aAESiUeyQ6HQITIHC5EA4XhUJkgTEERHkynU2mYekwJk4SzIRB+XIAbUkbE0AF13rwRdASYhIAgpayrp8cY97NzamleBLKPNoAAZZAATwWlFloFQtpwRGIIFoHCQsAIZJI8vAUNFzMBrw4EDwYHgLpImg4sAgTKQHld7pAAFkkAB6DPIf0cVDQSVuKmIVBqsOTS67SWI3iO4gy0DUe6G54nMABjgAL27noD42Diyb8vlCnkio4ADd4LSAEb3EhF5YEWoHX0jmXyNrKIzyGKxbSSMqKPTKNjFfTKtgtja4o2duO9-vHFyXYckOVsCdsSRTkBZwXJdiBXNdOA3BYv33bRpEMZQunibQyjiUIfwMCJpHifQymPRQFBvO82zxUQu2IWQX2cQtBw-Bkv1-cd5EnGc53gRd3TA9d4E3aCjHCSRYn0HDJH0LRyjKBVVGULCz0kDomPUMpQkIzh73bfFQDI2JKMDN8hzoptfwYgCgLYkDOIg7ioKbWIwk0eQBlkaJKk0OSlDYfDFGkbQnK0Lo1EUJTJxYZUbzMdxVVBSgbXtEcATOV5UgijMoQeVZqRi6z4qJcL6gAOQIQ55xgXYoFgaK7Sy9FEo4ZBYAQPE+HBUFPkbbKapAIRUrAdLkV+I5YTeUxyFsahUEbZsQAAM1makv1AGb7lTN0mGLC0FmkAArShngjHA8TakB4CZPwJtAIQaDqihRCTAgPHgKapoAeUesbKAAVWgXgmCOVAcEoYhs2zKg3ukC1kD8aRdmWecxUgRAdugdBliEaQYB8bNilgfQpsCyJkFiZR5wIZQCEkKa4lgKanLKMAQnkchZGzCBlj+1mAH0IFemhKGZi70Fe7MADV6DyyRxf0cQrQAaXEfpYlGATxAASQzLB2YABQgSgUt9dmhFWdAOVitHufGradsQAB+VAIAAa15ABeegfAAdWgHsygARxJac1GUaWIAIIREH8AgNYIZAyh7AB3PKhCFp6MxJDMcFte5bNdgApIXAp8TayTygBxIQSWWHxwSexASV4GOcAARQgMoABFNGgaXNttIvNAILJEHkWvxfgZQ8qznxkA1zYvaLoXNGNEAUAupgRbFiWpdl+XFYV1X1a1nWID1g25lmSroDRi7pAFkBCzTJhbvEAWpuvkBli+n7UD+gGgZBnmwdsSHoaw2ZPDRGyNUbo0xrIbGuNcLyAJkTEmZMKaxCpjTOmoRGZ8xoA9Ka4g07FiENxXmt1H68xXuLES685ZK1ctvNWmtta6wIPrQ2J8Ta3Uvg9G29snYu3dp7H2ftlAByDiHMOEco6x3jonZOqd04EEzjnPOBdi6l3LpXautcG5N1bu3Tu3de790HpIYeo9x6T2nrPbkAFKBgF2MHZAQsHSPhADIGQshn7LGoBrXYtpaRgD4FgeAPZsQBIODqYgU0+DUFMC6FaHo1qWmsRwRe6YhZzmWHwYJdhMAAAIZj3EdBwZY3EmCsAAr6Wx0B4D7Rcc-JAMYsBFjQAQHwtomDIFZhAZ+xsWbHEmpAIQOBMC8mOLlCw30PwwG1Dk7AkA3SHRGlQGgZTn51AmYIJMqyTQRWsLYEiHpGA7PqI0TIgRDlrNNKcmgOQLnHImdc1ALQ7ngFBAUpJLyrh9VRNs15HxbhqQOWIEE-yviHH6mMo5fywQVk-C8rE3y-i-KxAaIFULSQUipDSOkw4xTIt5AQfkWKhSIDVGKCUUp0xQquGqDUWokA+F+esqwVBLSZWgI2YF4ympRXZUy00KU2zpQqrFflEUCpFRKmVEV1kuV1QavYHloLOVQq6kK+4iKBoXNMLsOMFEQAxxINoDg-piDaRAO05w7BNJJmGYicsTBKlgGqbU3aQZplIFmVgeZc0ThLLGmK+o5o2WnxVfPXVxALwGpIOa01gZLVlGtUGIZIyHUemNgsSE5ZoBQnuIsKZcBPV4m9ZGX1ZAKABpecys0rKFjsrDfcpVDY+VVoFd1YVLauXVolXsYq0BSoHxlSOMQOqSASWjWak1-ZLUuAAqkpgmxlgACEMz0A1rk5uFBclayRnwZ+05nEdhAJoaQMg54sCAA)
- Got this error:
```
[
  {
    "keyword": "type",
    "dataPath": ".coordinationSpace.spatialRasterLayers['A']",
    "schemaPath": "#/properties/coordinationSpace/properties/spatialRasterLayers/patternProperties/./oneOf/0/type",
    "params": {
      "type": "null"
    },
    "message": "should be null"
  },
  {
    "keyword": "enum",
    "dataPath": ".coordinationSpace.spatialRasterLayers['A'][0].type",
    "schemaPath": "#/definitions/rasterLayer/properties/type/enum",
    "params": {
      "allowedValues": [
        "raster"
      ]
    },
    "message": "should be equal to one of the allowed values"
  },
  {
    "keyword": "oneOf",
    "dataPath": ".coordinationSpace.spatialRasterLayers['A']",
    "schemaPath": "#/properties/coordinationSpace/properties/spatialRasterLayers/patternProperties/./oneOf",
    "params": {
      "passingSchemas": null
    },
    "message": "should match exactly one schema in oneOf"
  }
]
```
@ilan-gold ?

(Update: same error if link saved without any changes to initial view. [link](https://portal-prod.stage.hubmapconsortium.org/browse/dataset/72d7f6895a34be4e0f43df278c675da2#vitessce_conf_length=2394&vitessce_conf_version=0.0.1&vitessce_conf=N4Igxg9hBOAmCWA7AhgF3hRBlADssApiAFyixrIDOBqJoAgiSIwL4A0Ile6yANgFpQAtnWYkAtACYAdJICMATgDMkgGyq56gAxyAHFq0AWdp27w+AJQio0GRKMbEtJrrb4AVZNADmNABoOJADskgCs0qEuZh5evqgAmoHEcpqqEVFuvJ4+NPxJzhyEvLwAYvC8qATQSYgArsUmRbwAEvDeABa8be20pGLEdQ2FBMVYNGO8BGDomDX1vI0jvGOorR1dHb0MJIMLw6M0AMIQvDBzQyC+iARrnd1b-bsmVwQTUzP2fY5PHC8AogAPHDQAiUSh2Y6naBCZA4JIgHC8KgwkDPAjXQHA0HgzCQmAwnAWZCIXxJADaWjYcgAuotinjoH9EJAECT4U0Vm9pnZURxXDxeETKJVoAAZZAATyqlHJoFQEpwRGIIFoHCQsAIAJIlPAJ3xsJ28w4EDwYHg8pIcg4sAgMKQ7gVSpAAFkkAB6Z3ILUcVDQYmuEGIVAMw3FQrtYnXXgy4hk0DUSbc2Z9MDajgALzTKu1jT11VjlMpYVC1I4ADd4OCAEaTEi+2oEPldDX5smhJTSQwpUIKQxKBRaXSqBRyQxU1SGNJaIJKGdGVS6IIl9jxkbvHkpy0ZrO9Aq6qEkClsYtsLSlkAV6u14j1xucZtVQ-dhTSIKjyRKT8KXR9pfHuRBIYL6fkEugDqoYS0mwq6Jh8oipsQkjbk4Po5oUeaHieRahCW5aVvANZKreTbwC2T4pJ2WizqB04aG+ui6FShhGNISjDjoug4ZOi7LtBnBrkmnygAhSjITqu65gesYnlh56XgR17EfepGPrGSjhHIoRaKEkhBAooRdjooSqGwEFpAoukaB+848bSdkZAKhxLJQ4pSvm2wDPMDnmLwzonFM9Sgq5qkeT8piZAAcgQ3RVjA7RQLALmSiFjxeRwyCwAgHx8E5ByoDGoVpSAQj+WAgW3BsPTnAsJjkDY1D5YeoAAGblKCTUgK1kwOoqTB+sKVTSAAVpQszGjgHwFSA8Awr4MZxsVNAZRQoi2gQ7jwM1zUAPJbQ1lAAKrQLwTA9KgOCUMQbpulQ+3SMKyC+NI7S1FWBKQIgo3QOgtRCNIMDeG6ISwEEzULvpyBKIYVYEIYBBaM1fawM1um6GAqhLuQkhuhAtTnXjAD6EB7TQlA40INCbc1ZMAGr0BFBjTuIooANJSFR4hyBzACSzpYATAAKECUH5GoE0I9ToEibn-ST+XDaNiAAPyoBAADW6IALz0N4ADq0DproACOfxlkYhgsxABBCIgfgEALBDILo6YAO4RUINPbc6fzOjgEqTOpusAFI0wu3hDQCEUAOJCH8tTeIc22IH8vAuzgACKEC6AAInI0As0NEpR3IBDxIgoSpwY8CGBFQfeMgAvNEbUc03IvIgCgFNMHTDMGEEzNs5IHNc0o4i8-zQsixAYsSxU5TJdA-0U9I6DNSAPqOkwa3iKva8cLUx2nag52Xddt2k-dNhPS9b2wh9X0-X9ANA5IINg2BoSQ9DsPw4jSjI6jdGmNkDYzWrvcQfs-RCFImTMBVNab00Zv3Vm7NR4jzHnzQWwtRYEHFpLeeMs1or02irdWWsdb60NibM2hgLZWxtnbB2TtXbu09t7X2-sCCBxDmHCO0dY7x0TsnVOGcs653zoXYupdy6Vy0NXWu9dG7N1bqic8lAwDtGtsgGm0oNwgC0NIAxkh14gFqNQAW7QJTgjAHwLA8B0yvBsV0NkxBmp8GoCYeUvVlT9RFKojgncnQ00rLUPg9jbCYAAARlEmDKfepEmCsHPBqdR0B4ATT0SYpA5osC+jQAQbwEomDIDxhAEx0tca9AWpAIQOBMDol6OFAUJjIAwFZBE7AkBFRTTqlQGgiSTH8h8oIW0Ay+TREFNYDpYymk+WyHEAIypGDjMyPMmgiQlmDImWs1AeRNn7FKOUPx+zwBLAqvcGZHJxgCTgicq5qxuiVUacs05eUQwnJeOczYMyXhcluWIX46ICCYhBGCCEeYCQ-KBSC7E4KoQEiJCSJ0LymgMiZCyJA3gZlDMsFQEUwVoAxgBbMnKzkCXYomX5RMgUkpuQpZFaKHRYrQHitPWlqliUZSynYUleUiUvJKtSyYXyqqbJMO0S0SEQAuxIAoDgWpiCiRAEUpwK5dS1PqUGJgKSwBpIyWNXUbSkAdKwF09qfRekNXpQKIU+KF78vbhK4gY5pUkCVQqnUKrdBqpqXU64WrlTSyqMcIM0ATiTGqOhI1KAPimpNOasgFArUnJxYKPFVQCUOpWY5MlC9rU+SpQFWJ5KU0TKijFOKCV2X5jEOKkgjFXWKvlVmFVzhzyBKYM0WoAAhZ09ABaROzhQSJQtvp8BMWWXRyYQByEMdINuLAgA))

**Comment by ilan-gold** [comment]
https://github.com/vitessce/vitessce/pull/907
