### ISSUE TITLE
Vitessce schema validation errors are truncated

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1733]
Prompted by #1732: The Vitessce error JSON is truncated: The last third is out of view, and the box can't scroll down.

<img width="351" alt="Screen Shot 2021-04-16 at 11 28 11 AM" src="https://user-images.githubusercontent.com/730388/115047870-efcecf80-9ea6-11eb-85c8-cff5ef42fabb.png">

@ilan-gold ?

**Comment by ilan-gold** [comment]
https://github.com/vitessce/vitessce/pull/907

**Comment by ilan-gold** [comment]
This is because scroll is disabled on vitessce, I believe.
