### ISSUE TITLE
Selecting any of the HuBMAP IDs other than the first one (default) cause a Portal Erro

### ISSUE THREAD

**Issue by khanshawPSC** [hubmapconsortium/portal-ui#1737]
On the Data Portal when using menu item Previews /
Cell Type Annotations
Selecting any of the HuBMAP IDs other than the first one (default) cause a Portal Error:

Error
URL: https://portal.hubmapconsortium.org/preview/cell-type-annotations

TypeError: null is not an object (evaluating 'n.find')

**Comment by mccalluc** [comment]
Duplicate of #1731
