### ISSUE TITLE
Design UI for Cells API 

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1750]
Primary stories:
- Select a set of datasets where cells express a given gene, and for each dataset, give the number of matching cells, and the total number of cells. (Perhaps the same thing could be achieved with group by but it would take a pair of queries, one constrained, and one unconstrained.) → _I don’t think this is currently available._
- Refine what it means for a dataset to match a cells query: It’s probably not useful to include a dataset if only a single cell highly expresses the gene in question. Besides a gene, and an expression level, probably want to say the percent of the total cells in the assay that match. → _I don’t think you have anything like this, but I could be mistaken._
- For a single dataset we want to get the expression level of a given gene for all cells. (In our discussion, we started by thinking about the set of matching cells, and then showing expression levels for the two groups, but that’s not needed.) → _I think this is already available._

@tsliaw, please work with @SFD5311 early in the process to develop a collab notebook that documents exactly what data you need, and how their API can provide it.

I'll file a single implementation issue, but if the design turns out to be composed of discrete independent components, please to separate sub-tasks.

**Comment by mccalluc** [comment]
Update: 
- Tiffany is [charting out the user flow](https://www.figma.com/file/VLkirv1D0ytHVLchKvcaFt/Molecular-%26-Cellular-Query-User-Flowchart?node-id=0%3A1)
- Chuck [started a PR](https://github.com/hubmapconsortium/portal-ui/issues/1774) to stub out the flask endpoints we'll need
- Sean increased the request page size, and is working on some database issues.

**Comment by tsliaw** [comment]
I will close out this issue as the main design has been mostly finished, and file smaller issues for future UI fixes from the user testing/minor fixes/language. Implementation Issue here: #1984
