### ISSUE TITLE
For Dataset DOI landing pages: `Publication` instead of `Creation`

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1754]
High-level issue: #1723

> Jonathan prefers "Publication" to "Creation". We have Creation Date right now, and the semantics are different, so it's not just changing the words.

@shirey : If I'm understanding Jonathan's requirements correctly, update here when `publish_timestamp` is available in the document JSON... Or if I've misunderstood the requirements, please close this.

**Comment by shirey** [comment]
We have a `Dataset.published_timestamp` attribute in the database, we'll get it into ES with this:  https://github.com/hubmapconsortium/search-api/issues/302

**Comment by mccalluc** [comment]
@shirey -- This fell off the radar, and now that I'm looking at it, it seems like it should apply to Donors and Samples as well, but the field doesn't seem to be present on those entities. In the code, the same components are used for all Entities, so showing the publication for some and the creation for others add complexity.

@tsliaw -- Unlike "Creation Date", "Publication Date" is not always present: It will obviously be missing on unpublished entities. How should this be handled in the UI? Out of the box, it will render as `Undefined`, and I can live with that... but you may have a better idea.

**Comment by mccalluc** [comment]
Nils says that `Undefined` should be shown as "not applicable".
