### ISSUE TITLE
fix "No translation" indications on assay types

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1761]
Fill in as much as seems useful:

**Describe the issue**
When one accesses certain datasets on the HuBMAP Portal, you can find "no translation" listed in a number of facet-related fields such as in the attached example.  I believe we want to have a different label.

**To Reproduce**
1. Go to: https://portal.hubmapconsortium.org/browse/dataset/3074b1e59c8a747a6598e20efe04ee26
2. Look at blue text under HBM title

**Expected behavior**
Show appropriate info / label / thing

**Screenshots**
![image](https://user-images.githubusercontent.com/21177919/115619118-82b1a480-a2c1-11eb-9556-04adc721c646.png)

**Environment**
 - Browser: Chrome
 - Browser version: Current
 - Portal version: `/static/VERSION` (Current - April 21)

**Best guesses**
 - Relevant repos: UI?  API?
 - Developers to involve: Chuck, Bill, Matt

**Comment by mccalluc** [comment]
This is a fix needed at index-time: https://github.com/hubmapconsortium/search-api/issues/268

Keeping this open until we actually see the correct values in the portal, though I don't think any portal code changes are required.

**Comment by mccalluc** [comment]
(Fix is deployed on TEST, should be on PROD soon.)

**Comment by mccalluc** [comment]
(Either not yet on prod, or there's still a config problem with [`salmon_rnaseq_10x_sn`](https://github.com/hubmapconsortium/search-api/pull/310/files#diff-2bee40c75016c9731a187e68922eace757f9cc0ff2f5e551c963c2fbeba5e793R286))
