### ISSUE TITLE
triage: Provenance for GE Cell DIVE datasets show no sample and samples show no datasets

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1788]
Fill in as much as seems useful:

**Describe the issue**
When I am logged in and accessing the list of GE Cell DIVE datasets and select one, the provenance graph displays only the donor and no sample.

When I am logged in and accessing the list of GE Cell DIVE related tissue samples datasets and select one, the provenance graph displays only the donor and not the dataset.

**To Reproduce**

1. Go to here: https://portal.hubmapconsortium.org/browse/sample/a4c7b437e1e74ee5fd3ef2bb4fffa67c
2. Look at provenance graph
3. See no derived datasets displayed
4. Select donor, select derived datasets
5. See derived datasets displayed

1. Go to here: https://portal.hubmapconsortium.org/browse/dataset/060dfa0fdf2b840864f62d2cd1a7a456
2. Look at provenance graph
3. See no sample linked to dataset

**Expected behavior**
I would see a connected chain of Donor > Sample > Organ relationships

**Screenshots**
![image](https://user-images.githubusercontent.com/21177919/116416831-b2eccc00-a808-11eb-958e-acd728a45be0.png)
![image](https://user-images.githubusercontent.com/21177919/116416928-d0219a80-a808-11eb-833b-e2f69408ef6e.png)

**Environment**
 - Browser: Chrome
 - Browser version: most recent
 - Portal version: `/static/VERSION`; as of April 28, 20201 am

**Best guesses**
 - Relevant repos: ?
 - Developers to involve: Chuck, Bill

**Comment by mccalluc** [comment]
I believe the UI rendering is correct, with the information it has been given. I know that there has been some discussion about the provenance for GE datasets... but all I remember was that the metadata was sparse, not that the provenance DAG had an unusual structure. Looping in @shirey to see if there's backend work here...

**Comment by shirey** [comment]
@pecan88 
It looks like the data was registered directly against a Donor instead of against tissue sample(s).  Pink node is the donor, red nodes are tissue (organ, ffpe-block, ffpe-slides) and the blue node is the data.

![image](https://user-images.githubusercontent.com/5816400/116456695-8b115e80-a830-11eb-8826-f1a2739960f3.png)

**Comment by ngehlenborg** [comment]
Not sure if that matters in any way, but the Globus folder associated with dataset https://portal.hubmapconsortium.org/browse/dataset/060dfa0fdf2b840864f62d2cd1a7a456 (HBM732.FZVZ.656) is empty.

**Comment by mccalluc** [comment]
Update from Chris
> I connected @shirey  directly with Fiona & Liz at GE so the provenance issue is getting resolved.

(Still keeping this open until fixed in portal, or alternate tracking is available.)

**Comment by pecan88** [comment]
@mccalluc GE has gone through and updated much of the provenance.  I noted one lack of linking between a sample and a dataset and asked GE's project manager to review the sample to dataset linkages to make sure we aren't missing any others ...

**Comment by mccalluc** [comment]
@shirey : The dataset now has the intermediate samples, but the sample does not show derived datasets... It's possible this is the case because there are none. Do you know?

@pecan88 : Do you have reason to believe there are datasets which are derived from https://portal.hubmapconsortium.org/browse/sample/a4c7b437e1e74ee5fd3ef2bb4fffa67c ?

**Comment by pecan88** [comment]
@mccalluc - yes, there have been no HIVE based processing for the datasets so there will not (yet) be derived datasets.  The decision at TC-CMU & RTI-GE about 2-3 weeks back was to seek to have the pipeline ready for testing by May 14 - currently it is pending.  (I'll close this issue unless you see reason otherwise for it to remain open.)
