### ISSUE TITLE
Create a favicon

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#180]
@tsliaw: please create a few options when you have time.

**Comment by ngehlenborg** [comment]
Here are some materials that could be helpful: https://drive.google.com/drive/folders/1i-JdnsSphQYzpnh7KMciazarJhT4ctkd

**Comment by mccalluc** [comment]
Done!

**Comment by ngehlenborg** [comment]
It looks like the generic detail pages are missing the favicon. @john-conroy: can you fix that when you create per-type detail pages?

<img width="903" alt="image" src="https://user-images.githubusercontent.com/1216518/81865153-8da17800-953b-11ea-84a9-abebb8f62f02.png">

https://portal.test.hubmapconsortium.org/browse/dataset/4f80da2501a9547fbbb6f2a1b9458633

**Comment by mccalluc** [comment]
Close in favor of #293
