### ISSUE TITLE
Integrative Visualization of Vanderbilt Data

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#1807]
Currently the multiple Vanderbilt datasets located in each collection can be visualized together provided they are from the same serial slice.  We have a way of accessing this information because it is systematically stored in the file name.  There is also potentially a way of using the RUI information to get at this data, but TBD.

Here are the steps to creating integrative visualizations for Vanderbilt:
1. Go to a collection of Vanderbilt data
2. Look at the filenames (or use the RUI information) and group together datasets from the same serial slice (i.e the same slide of tissue)
3. Create a Vitessce visualization with all of the images from a given slice overlaid

**Comment by mccalluc** [comment]
@ilan-gold -- I think it's great to take Vanderbilt as a leading edge test case, but I'd be very reluctant to create code that depends on structures particular to this one provider. 

>  We have a way of accessing this information because it is systematically stored in the file name

I would strongly urge us _not_ to write any new code that depends on these file name structures. We should hear more soon from Bruce about how the information needed is / will be encoded in the RUI-JSON. When that's clear, that's what we can build on... but the Vanderbilt filenames will still be useful as a sanity check when doing manual testing.

If this conflicts with what you're hearing from Nils, let's talk.

**Comment by ilan-gold** [comment]
Totally agree @mccalluc.  Nils asked me to write up the current state of things so we have it documented.

**Comment by mccalluc** [comment]
Quoting Nils from slack:
> We definitely don’t want to do anything will file paths :slightly_smiling_face:

So when we get to this (which won't be soon), we're not going to do anything special for Vanderbilt. Until the data we need is in the provenance or the RUI-JSON (Bill and Bruce need to sort out which it is), we're blocked on #1791.

There is nothing actionable here, so I'll close, but thanks for writing it up.
