### ISSUE TITLE
Design Organ Detail Pages

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1824]
Todo:

- ID info that needs to be displayed on a tissue-specific page (organ = organ type, ie all kidneys, not specific sample)
- Description text
- Possible links: Azimuth datasets,  reference object used by CCF, ASCT+B table, for all organs of that type a built-in faceted browsing interface for that datatype
- List of TMCs generating data on this organ
- Overview of assays

**Comment by mccalluc** [comment]
@tsliaw -- What's necessary to consider this complete? We know the backend needs to be there, but I think what you've got now looks pretty good.

**Comment by tsliaw** [comment]
@mccalluc I'll see the comments tomorrow in the portal meetings and make the adjustments necessary. This might need to go to backlog if the design changes needs to wait on decisions from other groups, so that I know to go back to it. But if the design can be revised with the comments from tomorrow, I'll mark it complete.
