### ISSUE TITLE
Stitched Cytokit Visualization

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#1845]
There are currently two blockers to visualizing the stitched cytokit data from our end
- [x] Visualizing bitmasks - see https://github.com/vitessce/vitessce/pull/927
- [ ] Handling the very large heatmaps that have a lot of cells but few features.  It is currently very slow.

**Comment by mccalluc** [comment]
@ilan-gold
- vitessce/vitessce#927 is merged, so I've checked it off.
- Do you have any strategies in mind for lots-of-cells-few-features?

Once the blockers are resolved, there would still be work here, right? Maybe just setting up the viewconf?

**Comment by ilan-gold** [comment]
Yes, I started the release process but caught a few bugs.  Mark and I are discussing the heat map tomorrow morning so should know more then about that.

**Comment by ngehlenborg** [comment]
The stitched CODEX datasets are now supported.
