### ISSUE TITLE
Set maximum character/word length for collection list on dataset detail pages + collections page

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1862]
![Screen Shot 2021-05-25 at 9 59 56 AM](https://user-images.githubusercontent.com/16737715/119538437-f7a05000-bd3f-11eb-87b3-fd5d7c0ba493.png)

Titles that are too long are running into the 'dataset count' on the collections list on dataset detail pages. Set a maximum character/word limit so that it doesn't run into the dataset count and add ellipsis to the rest of the title. See "Line length" section on [material ui documentation ](https://material.io/components/lists#behavior).

**Comment by mccalluc** [comment]
@tsliaw -- Agree that something needs to change, but my first thought was that it should wrap? Decision can be yours, but want to make sure that was considered. Thanks!

**Comment by tsliaw** [comment]
I was thinking to not wrap so the each list item is a fixed height, and the documentation for material design seems to also suggest cutting the text off with the ellipsis.

**Comment by mccalluc** [comment]
(The same fix should also be applied to the collections list page: https://portal-prod.stage.hubmapconsortium.org/collections )
