### ISSUE TITLE
creation and modification top aligned instead of spread out

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1869]
<img width="483" alt="Screen Shot 2021-05-27 at 1 27 42 PM" src="https://user-images.githubusercontent.com/730388/119870598-8dc6a880-beef-11eb-8a51-44012505fd77.png">

With long descriptions, the creation and modification date are spread out, at least on collection pages. @tsliaw -- Should these be top aligned instead? Or if the status-quo is what we want, please close. Thanks!

**Comment by tsliaw** [comment]
These should be top-aligned, thanks for the catch~ I'll reassign to John
