### ISSUE TITLE
Gateway API URL should not be hard coded

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1871]
The status page depends on a hard coded path in `context/app/static/js/components/ServiceStatusTable/hooks.js`:
```
const gatewayUrl = 'https://gateway.api.hubmapconsortium.org/status.json';
```

This should be provided as an envvar like the other APIs.

**Comment by mccalluc** [comment]
Still needs to be done, but now in `routes_main.py`:
```
def _get_endpoints():
    return {
        'elasticsearchEndpoint': current_app.config['ELASTICSEARCH_ENDPOINT']
        + current_app.config['PORTAL_INDEX_PATH'],
        'assetsEndpoint': current_app.config['ASSETS_ENDPOINT'],
        'entityEndpoint': current_app.config['ENTITY_API_BASE'],
        'cellsEndpoint': current_app.config['CELLS_API_ENDPOINT'],
        'gatewayEndpoint': 'https://gateway.api.hubmapconsortium.org'
    }
```

**Comment by mccalluc** [comment]
@yuanzhou - Could you add a `GATEWAY_ENDPOINT` to the environments? Forgive me if there's another thread where we discussed this.

(When we get around to implementing, see also: #1880.)

**Comment by yuanzhou** [comment]
@mccalluc The `GATEWAY_ENDPOINT` had already been added to the `app.conf` per our early discussion: https://github.com/hubmapconsortium/portal-ui/pull/1876#issuecomment-851746554
