### ISSUE TITLE
triage: Confirming Organ level identification for certain samples

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1881]
Fill in as much as seems useful:

**Describe the issue**
@computationdoc  noted a few samples listed at the organ level rather than something like the organ piece level.  Is that the correct categorization @shirey ?  If not, is the issue on the data entry side or the mapping of labels?  (Or something else?)

**To Reproduce**
https://portal.hubmapconsortium.org/search?mapped_data_types[0]=CODEX&source_sample.mapped_specimen_type[0]=Organ&entity_type[0]=Dataset

**Expected behavior**
Possibly should be showing organ piece rather than organ (?)

**Screenshots**
![image](https://user-images.githubusercontent.com/21177919/120520642-091dd380-c3a2-11eb-8501-09b2a91401b7.png)

**Environment**
 - Browser: Safari
 - Browser version: current
 - Portal version: `/static/VERSION`

**Best guesses**
 - Relevant repos: either whatever is mapping the organ enums in the UI or the data itself is wrong ... ?
 - Developers to involve: @shirey @cebriggs7135

**Comment by shirey** [comment]
@pecan88 and @computationdoc It looks like those datasets were registered directly against an organ instead of downstream tissue blocks/slices/pieces...

**Comment by computationdoc** [comment]
@pecan88 please work with data provider to get the corrected provenance information, then with Bill Shirey as to whether the data provider would/will have privilege to correct it or if correction needs to be done by dev team on back end

**Comment by mccalluc** [comment]
Looks like this is a data problem, and we haven't been tracking those with issues in this repo. Closing.
