### ISSUE TITLE
Enable users to view pdf files within dataset detail page

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#1886]
We want users to be able to better interact with the files without having to download them. As a start, we'd like to display pdf files in a modal.

Notes from @tsliaw for design:
- Use a pdf icon button for users to open the file viewer.
- Add an 'x' button at the top right of the pdf for users to exit the file viewer.
- Display an alert in the event of an error opening the pdf.

**Comment by mccalluc** [comment]
@john-conroy -- I think you had started work on this?
