### ISSUE TITLE
Access assets

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#189]
The path in the json should be `ingest_metadata.files`... unless that's changed.

----

Bill Shirey:spiral_calendar_pad:  16 minutes ago
For the example dataset that you found I put a test file in place for src_data/segmentation.json

Bill Shirey:spiral_calendar_pad:  14 minutes ago
The algorithm to construct the url is:  make a url/path by concatenating the file service server url with the dataset id with the relative path to the file…so…
curl -X GET -H "Authorization: Bearer <NEXUS TOKEN HERE>" https://assets.dev.hubmapconsortium.org/fd1c1ab4890f527704b20de52b797551/src_data/segmentation.json will get you the file that I just put in place.

Bill Shirey:spiral_calendar_pad:  14 minutes ago
Of course replace <NEXUS TOKEN HERE> with a good Globus Nexus token..

Bill Shirey:spiral_calendar_pad:  11 minutes ago
The file service servers/base urls are
DEV: https://assets.dev.hubmapconsortium.org
TEST: https://assets.test.hubmapconsortium.org
PROD:   https://assets.hubmapconsortium.org

**Comment by ilan-gold** [comment]
@mccalluc Is there an action item here?  Do you want me to replace the current "Vitessce demo" in the portal with this file?

**Comment by ilan-gold** [comment]
Or rather, some output confirming the message we get in that file since there is no real data?

**Comment by mccalluc** [comment]
@ilan-gold : If you can,
- Find one record that has `ingest_metadata.files`.
- Write a curl statement that convinces you that the recipe given (with the special http header) it actually does return a file.

That's enough to close this issue. For follow-up, might file new issues to:
- Can you find other records with `ingest_metadata.files` using elasticsearch? Could that be a facet we expose?
- Prepare the code that constructs a viewconfig, so that as soon as their is appropriate data for vitessce, we can visualize it.

**Comment by ilan-gold** [comment]
Looks like we got the response we were looking for.  Going to leave this open until we actually see the CODEX data on the screen, but things are looking good.

<img width="1680" alt="Screen Shot 2020-04-30 at 3 00 33 PM" src="https://user-images.githubusercontent.com/43999641/80749148-07754280-8af4-11ea-909c-362eb640f315.png">

**Comment by mccalluc** [comment]
(Ilan will open more specific issues for CODEX and UMAP data.)
