### ISSUE TITLE
Link to CCF-UI in header

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#190]
https://hubmapconsortium.github.io/ccf-ui/home

**Comment by john-conroy** [comment]
Add tooltip which says “Explore HuBMAP data using the Common Coordinate Framework”.

**Comment by john-conroy** [comment]
Link has been added. Will create a new issue for tooltip design improvements.

**Comment by mccalluc** [comment]
Link an tooltip are in place. Closing.
