### ISSUE TITLE
triage: pagination by 18?

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1910]
Fill in as much as seems useful:

Is there a reason we are displaying 18 records per page for the search results rather than a round number such as 20?

**Describe the issue**
Feels weird to not have a round number

**To Reproduce**
Search for datasets with a large number and count rows for pagination

**Expected behavior**
I guess I'd expect a round number ...

**Screenshots**
not needed

**Environment**
 - Browser: Chrome
 - Browser version: latest
 - Portal version: `/static/VERSION`

**Best guesses**
 - Relevant repos: portal-UI
 - Developers to involve: Chuck?  Bill?

**Comment by mccalluc** [comment]
There is a reason: besides the list layout, we also have the tiles layout, and there, there information can be presented more compactly with 3 columns. Tradeoffs.
