### ISSUE TITLE
Ongoing IMC 3D Data Type Issue

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#1914]
TL;DR It's not clear if the data is quantized or transformed, or if either of those things are desirable. I need to understand more about the issue and perhaps involve someone who knows more about this than me.  If it's just insignificant quantization, that's fine but the data looks different as my email suggests and Laura's email seems to confirm although I am trying to clarify this.

From Ilan:

> 
>  Hello Laura and Hunter,
> 
> The latest data does seem to have the correct data type in principle but I noticed something strange - the data looks quantized.  While the data is floating point and marked as such in the metadata, it looks like integer data that has simply had its data type changed (or something to that effect).  From what I remember of the data you had sent a few months ago, the IMC data actually does have floating point decimal places but this most recent data does not appear to have that.  Is this true?  I would not want to have data uploaded that has lost its precision or is wrong.
> 
> For example, I went on globus and downloaded the MCD files and then ran the following commands (using your imctools package):
> 
> ```
> parser = McdParser('/path/to/20201120_HuBMAP_thymus_slide3_MD.mcd')
> ids = parser.session.acquisition_ids
> # 2 was one of the ids
> ac_data = parser.get_acquisition_data(2)
> ac_data.get_image_by_index(0)
> array([[3737.8735, 4114.1973, 3734.9067, ..., 3997.5852, 3839.6492,
>         3838.899 ],
>        [3826.8599, 3893.7876, 3993.7104, ..., 3947.3582, 3804.6697,
>         3767.051 ],
>        [3818.166 , 4059.406 , 3944.1985, ..., 3687.4478, 3687.96  ,
>         3836.798 ],
>        ...,
>        [3533.6082, 3897.4316, 4116.8257, ..., 3878.084 , 4162.4062,
>         4112.7886],
>        [3722.6094, 4060.9897, 4219.163 , ..., 3827.092 , 4076.5823,
>         4345.713 ],
>        [3951.5034, 3742.944 , 3703.6963, ..., 3891.3425, 3889.2761,
>         4141.814 ]], dtype=float32)
> ```
> 
> This final data array, while it has the same type as the OME-TIFF, looks very different from the data I'm seeing in the OME-TIFF files.  I've attached a screenshot but there are a lot of ones and twos, and no decimal places.
> 
> Please let me know what I can do to help.  I'm happy to help with debugging and what not again.  Sorry for the back and forth, hopefully we can resolve this soon 🙂
> 
> Best,
> Ilan

From Laura:

> Hi Ilan,
> 
> So this is my first attempt to solving the problem :) So the short answer is that our IMC ome-tiffs could either be float32 or uint16. And a quick solution would be to have the current models in uint16, but to expect future ones (especially any 2d imc) to be float32 or uint16 (update in the imctools v1 to v2). I could convert the current ones to  float32 but I would have to update my pipeline  so it would take me some time make the changes (unless you just want float32 images that are the current ones, but these were converted from uint16).
> 
> A long answer is that the topic of data precision has been discussed in our group and there are two prevailing thoughts on this that either support float32 or uint16. So what we used to do is to convert the mcd into float32 ometiffs and then also convert ometiffs into single channel analysis tiffs that were uint16. These analysis tiffs were then used for segmentation and for extracting single cell data. And in my case to align the images for 3d models and to generate the final 3d ometiff stacks.  The person who established the pipeline considered that our IMC is a count data and thus the precision of the data is limited by the poisson nature of the data. Therefore the accuracy of the data is limited to square root of the expected value, and the digits behind the coma are not considered significant and could be cut without affecting the precision. And considering the memory benefit, our analysis tiffs were uint16. But for some people it seemed unnecessary/unsatisfactory  to change the data type between the ometiffs and the analysis tiffs and to lose some precision  so now with our latest pipeline both are generated as float 32 as a default. This was reasoned to avoid the loss of precision due to the discretization and being able to capture intensity values > 65535 (but these high values are negligible for IMC). 
> 
> 
> Anyway the latest decision was to have float32 as a default but leave users to decide weather they want to work with uint16, but scientifically we are not losing accuracy in our measurements when choosing uint16. Most of the time IMC ometiffs will be float32 as the ometiffs are generated in the first step of our pipeline, but in the 3d IMC case the original ometiffs undergo few processing steps before resulting in another ometiff stack that only contains the overlapping area and the channels that worked. So in my case when producing 3d imc models  I ended up working with single channel uint16 tiff files as lot of the image registration and 3d segmentation programs expect single channel images, so then once I have the alignment I bundle the images into a new ometiff that I sent to you :)
> 
> So Im not sure how flexible hubmap data specification is? Could IMC have both options?
> 
> Laura
>

**Comment by mccalluc** [comment]
ilan :
> I emailed Laura, the meeting already happened.  This isn’t really in my court though so I can’t make this happen sooner than she generates the data unfortunately.

**Comment by ngehlenborg** [comment]
Issue has been addressed per @ilan-gold.
