### ISSUE TITLE
DCWG Sample: feedback on provenance / display & dual organs

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#1918]
## Feedback

__Help Desk Issue Tracker URL__: none yet

__Message__: 
The following image contains feedback from a member of the data coordination working group sample team leadership.  Her comments relate to the structure and/or display of tissue provenance and dual organs.  I wasn't sure what to do with this beyond passing along if relevant.

![image](https://user-images.githubusercontent.com/21177919/122787698-965a9680-d283-11eb-8889-3ea09c744a1b.png)

@khanshawPSC - do we want to log this in the help desk tracker?

**Comment by mccalluc** [comment]
Will put on UI meeting agenda.

**Comment by ngehlenborg** [comment]
The provenance that we display in the provenance table is just what we get from the API/database. We can't change that.

The question of paired organs was raised by us before (in the context of organ pages, faceted search, cells API, etc.) and needs to be discussed at a higher level.
