### ISSUE TITLE
Deploy storybook (to github pages?)

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1919]
My guess is that a good way to do this would be to have the deployment script also build and push the storybook to a `gh-pages` branch, but pushing to s3 is also a possibility.

If we do use gh-pages, could we re-write that branch in place, rather than adding new commits to the repo history?

**Comment by john-conroy** [comment]
The storybook developers also offer [Chromatic](https://www.chromatic.com/).

**Comment by mccalluc** [comment]
Done!
