### ISSUE TITLE
Cells UI: Get user feedback on design

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1923]
By the July 1 meeting we at least want user feedback on the proposed design, and, if there's time, integrate the feedback into the designs... but that can come after, if necessary.

**Comment by tsliaw** [comment]
Update:
Nils will send out updated [prototype](https://www.figma.com/proto/bVGvGSEKUTy1p9vnMX8PsF/Molecular-and-Cellular-Query?page-id=221%3A4065&node-id=484%3A10731&viewport=302%2C609%2C0.05130083113908768&scaling=min-zoom&starting-point-node-id=484%3A10731) and video demo to receive user feedback.

**Comment by mccalluc** [comment]
@tsliaw -- Confirming that this should stay open? My sense is that the API is still in flux, and so the UI may be in flux, unfortunately. Nils says

> Matt gave updates on some recent calls and says that they are working on the performance and stability. They will also incorporate cell type assignments, which will be available going forward. The ball is in their court, there is nothing we should do at this point.

**Comment by tsliaw** [comment]
@mccalluc We can close this until after we get the updates back from the API to see if we still need to do this.
