### ISSUE TITLE
Identify interesting questions about donor characteristics

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1931]

**Comment by Roselkisma** [comment]
I created a survey with the following questions:

1- Which patient characteristics would you like to view when assessing the diversity of the population in a biomedical dataset?

The patient characteristics listed on the survey are:
- age
- blood type
- cause of death
-  race
- sex
- death event
- rh factor
- height
- social history
- medical history
- weight

2- Based on the data that is available what information would you like to learn about the diversity of the HuBMAP study? What variables do you want to be able to compare across different groups of patients' characteristics (age, sex, race, etc.)?
