### ISSUE TITLE
Figure out how to answer an interesting question with data from elasticsearch

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1932]
Identifying the question is #1931

**Comment by Roselkisma** [comment]
Based on question 1 on the survey "Which patient characteristics would you like to view when assessing the diversity of the population in a biomedical dataset?" I think that the best way to visualize this question is with a table. I attached a picture of how I think the table should look like. I was thinking that I will need to add the list of donors and then the user will choose the donor they are looking for. 

![donor's table](https://user-images.githubusercontent.com/85570580/125347600-1f1b9e00-e329-11eb-88c3-adcc611613c5.PNG)

**Comment by mccalluc** [comment]
That's not really what we're looking for: For an individual donor, we can always go to that donor's page to get the details. Some suggestions/possibilities:
- How do the causes of death of Hubmap donors compare to the the general population, when stratified by age?
- Are blood-type / weight / height representative of the American population?
- When stratified by any one variable, does uneven sampling along other variables show up?

**Comment by mccalluc** [comment]
@Roselkisma -- I think the last screenshot with ethnicity rows and gender columns does this. Can you make a PR, and link this issue to it?
