### ISSUE TITLE
dataset lifting should fail if multiple derived datasets are present

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1947]
We discovered a lightsheet image dataset that had two derived image pyramid datasets (note that as of 06/25/2021 the plan is to delete the older derived dataset, i.e., the provenance graph will change and some links in this issue might no longer work):

![image](https://user-images.githubusercontent.com/1216518/123484192-f6c83b80-d5d5-11eb-8023-f1ef901dacd8.png)

- Parent: https://portal.hubmapconsortium.org/browse/dataset/073cad035ce246a0134e2214569adde9
- Child 1 (older, upper branch in screenshot): https://portal.hubmapconsortium.org/browse/support/7728bedd91e159fb7951c6c78a5ed28f
- Child 2 (newer, lower branch in screenshot): https://portal.hubmapconsortium.org/browse/support/71b3fdd770de565e5d48a73060b72189

In this case the lifting used the older derived dataset, which led to major confusion because the newer derived dataset had been created to fix an issue with the older one but it appeared that the fix had not worked. 

This issue was compounded by the fact that the displayed lightsheet image is from the derived dataset but the Globus directory shown on the dataset page is for the parent dataset, which made it hard to confirm that the displayed image had been processed. 

Proposed fixes: 
1. Fail build/deployment/indexing (?) when multiple derived datasets are present for an assay type that uses dataset lifting.
2. Provide a link to the Globus directory of the derived dataset.

**Comment by mccalluc** [comment]
@ngehlenborg 
- Please add a `triage` if something is a priority. I check those frequently, but I noticed this by chance.
- "Fail build/deployment/indexing" ... I will start a PR for that... but people are generally unhappy when the indexing fails... I think you want to push the check farther upstream.
- [The code in question](https://github.com/hubmapconsortium/portal-ui/blob/master/context/app/api/client.py#L109-L114): There should have been an error in the logs, and John and Ilan should be checking the logs... but we didn't hear anything from them. Will ask on slack.
- "Provide a link to the Globus directory of the derived dataset": Proposal:
```diff
Files are available through the Globus Research Data Management System. 
Access dataset HBM423.JZTB.864 on Globus.
+ Access derived dataset HBM123.ABCD.456 on Globus
```
... And in this case there would be links to two derived datasets?

**Comment by mccalluc** [comment]
Filed https://github.com/hubmapconsortium/search-api/issues/340 for indexing changes. Want input from Bill before carrying that farther.

**Comment by mccalluc** [comment]
At the UI meeting, decided on two follow-up tasks: Issues filed.
- #1972
- #1974
