### ISSUE TITLE
Donor title display does not handle multi-valued fields correctly

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1955]
Fields with more than one value (here: race) are directly concatenated but should be concatenated with a ", ":

<img width="417" alt="image" src="https://user-images.githubusercontent.com/1216518/123709515-32b00a80-d83b-11eb-9739-6676989b90ab.png">

(HBM245.ZWNT.288: https://portal-prod.stage.hubmapconsortium.org/browse/donor/95a62662006235867084078a1e10bebf#provenance)

**Comment by mccalluc** [comment]
Adding to next milestone.
