### ISSUE TITLE
Entities API call for `New` `Protected` dataset returns 403

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1968]
(Similar to hubmapconsortium/entity-api#166, except this is on PROD, not TEST.)

- With the console open, login and visit https://portal-prod.stage.hubmapconsortium.org/browse/dataset/1e575f0e86af91631cf8d399de53a459
- In the console, I see:
```
Entities API failed 
Response { type: "cors", url: "https://entity.api.hubmapconsortium.org/entities/dataset/globus-url/1e575f0e86af91631cf8d399de53a459", redirected: false, status: 403, ok: false, statusText: "FORBIDDEN", headers: Headers, body: ReadableStream, bodyUsed: false }
```

Not sure whether 
- portal-ui is not passing the credentials it should pass?
- My credentials just aren't good enough?
- bug on entity API?

**Comment by shirey** [comment]
@mccalluc I don't think the portal can just use the data_access_level property- it needs to tell if the user/token has access to the data or not.

**Comment by mccalluc** [comment]
So the API 403 isn't a problem, and in #2089 we've tweaked the console log so it seems like less of a problem.
