### ISSUE TITLE
Molecular & Cellular Query

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1984]
[Figma with notes.](https://www.figma.com/file/bVGvGSEKUTy1p9vnMX8PsF/Molecular-and-Cellular-Query?node-id=487%3A11426). As a warning ahead of time, there still might be some edits to the mockup while you are working on implementation, specifically with language/smaller UI fixes, but for the most part the design is ready for implementation. I'll make note if I make any changes to the mockup after you begin implementing. 

Here's the [prototype stills figma](https://www.figma.com/file/bVGvGSEKUTy1p9vnMX8PsF/Molecular-and-Cellular-Query?node-id=484%3A10731) in case there are any frames you want to refer back to and the actual [prototype](https://www.figma.com/proto/bVGvGSEKUTy1p9vnMX8PsF/Molecular-and-Cellular-Query?page-id=221%3A4065&node-id=484%3A10731&viewport=2727%2C1465%2C0.49398913979530334&scaling=min-zoom) if you want to click through. 

Design issue: #1750

**Comment by mccalluc** [comment]
UI has been implemented, and we're just stuck on performance issues. Closing.
