### ISSUE TITLE
Add access control for private raw data (e.g. RNA-seq FASTQ)

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/portal-ui#20]
We will almost definitely have some sensitive data, e.g. the FASTQ files from RNA-seq runs. We should implement access control ASAP so this isn't something we have to bolt on later.

Users who aren't authenticated or authorized should _see_ all data, but be unable to download things that require additional access.

**Comment by mccalluc** [comment]
See also: https://github.com/hubmapconsortium/gateway/issues/5

ES will filter out items the current user does not have access to from search results. I will follow up about access controls on the file server.
