### ISSUE TITLE
On details pages, make react the default

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#202]
Looks good, but there are some gaps to be filled before it can be the default.
- [x] Breadcrumb links should be fixed. (Right now it says "Mock Donor ID 567 / Mock Sample ID 32546".)
- [ ] Visualizations should be filled in.
- [x] There needs to be a way to just pretty print the json... we're not actually interested in the structure as JSON per-se, so I think something like the nested rectangles on the jinja version would be good.

If the way forward on the third item isn't clear, feel free to make a stop gap, and file a new issue for design.

**Comment by john-conroy** [comment]
@mccalluc Could you explain the intended functionality of the breadcrumb links?

**Comment by mccalluc** [comment]
The idea is if we are on dataset, to be able to navigate "up" to the sample it came from, the organ the sample came from, and the donor. (And there might be navigation in the other direction to, but since that's a list, not sure not sure if the same idiom works.)

One larger purpose is that being able to navigate to the donor should take the burden off this page for displaying all the donor information, and being able to navigate to the sample takes off the burden for displaying sample information... Does that help?

**Comment by mccalluc** [comment]
Done.
