### ISSUE TITLE
Ordino/lineup for metadata

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2040]
Building on #2039 (lots of questions there about scope, column naming, etc.), we would like to make it easy for users to understand the data.

@ngehlenborg : The is [no documentation](https://github.com/Caleydo/ordino) on how Ordino would be used as a component. Would it be ok to try the [React wrapper for Lineup](https://github.com/lineupjs/lineupjsx) for now?

**Comment by ngehlenborg** [comment]
I checked with the developers of Ordino and they don't have any suggestions for integrating Ordino beyond an iframe, so let's use the React wrapper for LineUp.
