### ISSUE TITLE
I'd suggest factoring this out into a reusable component, like you did for the chart... Perhaps it's one component that could render both?

### ISSUE THREAD

**Issue by Roselkisma** [hubmapconsortium/portal-ui#2044]
I'd suggest factoring this out into a reusable component, like you did for the chart... Perhaps it's one component that could render both?

_Originally posted by @mccalluc in https://github.com/hubmapconsortium/portal-ui/pull/2036#discussion_r679457566_

**Comment by mccalluc** [comment]
In #2097 I'm just using a chart for everything, so factoring out a table component is moot.
