### ISSUE TITLE
Will the diversity page be linked to from anywhere else?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2059]
Maybe the footer? Doesn't have to be, but wondering if there is a plan. cc @Roselkisma

**Comment by mccalluc** [comment]
(Added to agenda for next UI meeting.)

**Comment by ngehlenborg** [comment]
Yes, let's add that page as "Diversity" to the footer in the "About" section. We should address #2075 and #2076 soon but they are not prerequisites for this issues.
