### ISSUE TITLE
TSNE Features for SPRM

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#2069]
- [ ] Add factors/clustering to spatial plots
 - [ ] Fix naming [(`tnse` -> `tsne`)](https://github.com/hubmapconsortium/portal-containers/blob/master/containers/sprm-to-anndata/context/main.py#L64) in pipeline
 - [ ] Fix incorrect file usage for scatterplot i.e TSNE not clustering: https://github.com/hubmapconsortium/portal-containers/blob/master/containers/sprm-to-anndata/context/main.py#L56
 - [ ] Decide on new view configuration for adding scatterplot to visualization

**Comment by ngehlenborg** [comment]
I believe this has been rolled out.
