### ISSUE TITLE
Add metadata table download to search pages

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#2079]
With #2039 having been addressed, we should add a download option for the metadata TSV tables to the donor, sample, and dataset search pages.

It should be made clear that this will result in a download of metadata for *all* donors/samples/datasets, irrespective of the filters applied on the page.

**Comment by mccalluc** [comment]
Design? I would lean towards putting it below the results, but whatever. Adding to next milestone.

**Comment by ngehlenborg** [comment]
At the bottom works for me but @tsliaw should suggest a design and then hand over to @john-conroy.

**Comment by tsliaw** [comment]
[Figma Link](https://www.figma.com/file/pkIZbpJOAQnylo1zjyhaU6/Search-Page?node-id=1362%3A20055)
Donors
![Screen Shot 2021-09-03 at 7 53 03 AM](https://user-images.githubusercontent.com/16737715/132025427-8591be53-1f3c-4234-810d-74b7eccaffc5.png)

Samples
![Screen Shot 2021-09-03 at 7 53 20 AM](https://user-images.githubusercontent.com/16737715/132025477-015852ed-7312-49fa-9011-92ee6fc418a2.png)

Datasets
![Screen Shot 2021-09-03 at 7 53 38 AM](https://user-images.githubusercontent.com/16737715/132025520-dd0a9caa-3b22-4101-9718-3eb4f6a7f817.png)
![Screen Shot 2021-09-03 at 7 53 49 AM](https://user-images.githubusercontent.com/16737715/132025557-498fe364-cc99-4c79-8305-b19c8e45ed11.png)

**Comment by ngehlenborg** [comment]
Should it maybe say "Download Metadata"? That would distinguish it from the table that is shown (but is filtered unlike what users get).

Does the dropdown for the datasets metadata download support selection of multiple values? I believe we can support that in the API and that we decided to support that in the UI as well.

**Comment by tsliaw** [comment]
Updated dataset search page. The menu should allow multiple selection now.
![Screen Shot 2021-09-03 at 10 14 30 AM](https://user-images.githubusercontent.com/16737715/132043322-424001ac-5a94-4298-90dc-bc7276c19296.png)

**Comment by tsliaw** [comment]
Will close this issue and file an implementation issue. Above screenshot should be the most recent updates, but check Figma to be certain. Notes on how the data types menu should operate is in the mockup and I'll make a note of it in the implementation issue.
