### ISSUE TITLE
IMC 2D Broken Viz

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#2085]
`iterAssays` in `TypeClient` does not produce deprecated assays but the entity response, which is fixed and does not change, still contains `IMC`.  Therefore https://github.com/hubmapconsortium/portal-ui/blob/07958d154206cd74ca0f354a79c9400dd1691637/context/app/api/vitessce_confs/assay_confs.py#L301-L313 breaks due to the `_assays[data_type]` call for `data_type` set to `IMC`.

**Comment by jswelling** [comment]
The assay type 'IMC' has recently been deprecated in favor of IMC2D.  Since TypeClient does not (currently) report deprecated names in tc.iterAssays(), there is no longer an entry in _assays for the name string 'IMC'.
