### ISSUE TITLE
Implement Organ pages

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2090]
[diagram](https://docs.google.com/presentation/d/1ZznSezXx-vnIlTRMafdMquFWlsSsrtcbV-qCQK7SNZ4/edit#slide=id.p)

### Design:
- [x] #1824
- [x] #2091
- [x] #2092

### Implementation, details:
- [ ] Get organ descriptions
- [ ] Anatomy:
  - [ ] Get UBERON list with descriptions from IU
  - [ ] Get web component from IU
  - [ ] Add ES facets to description mapping from IU
- [ ] Reference-based analysis:
  - [x] #2126 
  - [ ] Get list of modalities for each organ
  - [ ] Get count of nuclei
  - [ ] Get list of reference datasets
  - [ ] Get link to Azimuth
  - [ ] Get Vitessce config
- [ ] Assays:
  - [ ] Query the assays
  - [ ] Make a barchart
- [ ] Samples:
  - [ ] Query the samples  

### Implementation, list:
- [ ] Implement Organ list

### Implementation, navigation from home:
- [ ] Implement link from home page

**Comment by ngehlenborg** [comment]
We will also need to cross-reference the organ pages from other places where organs are mentioned. That might be the trickiest part.
