### ISSUE TITLE
Show preview images for imaging studies

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/portal-ui#21]
We don’t intend this to be a very full-featured interface at first. We should perhaps choose a few randomly-selected images for mass spec or microscopy studies, and show previews of these in the data portal. These preview images can be saved by data processing pipelines; maybe we should save 5 or 10 and choose a random subset of the available images for previews.

**Comment by mccalluc** [comment]
Having a preview in search results is plausible. Adding "proposal" tag to get product-owner feedback before going farther.

**Comment by mccalluc** [comment]
This is sort-of handled by the Showcase machinery. I've also filed a question-issue under [`ingest-validation-tools`](https://github.com/hubmapconsortium/ingest-validation-tools/issues/337) to see if this is something we would want to make provision for during submission.
