### ISSUE TITLE
Dataset warning design

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2101]
usecase: Checkerboard raster: We understand the problem, and will be fixed for future datasets, but it’s a physical problem with the experiment… but it’s not so bad that we’d want to retract the dataset.

(This will need backend support, but we want to a picture to be able to explain to everyone what we're thinking about.)

**Comment by tsliaw** [comment]
[Figma](https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=2059%3A12125)
 
![Screen Shot 2021-08-31 at 1 34 55 PM](https://user-images.githubusercontent.com/16737715/131572379-06f2b429-5ed1-470c-91b9-e54fea357583.png)

**Comment by tsliaw** [comment]
Updated Mockup
![Screen Shot 2021-08-31 at 2 29 49 PM](https://user-images.githubusercontent.com/16737715/131578395-dc4c4868-7b4e-4f0c-b055-f14d9069cad9.png)
