### ISSUE TITLE
Integrate CODEX into the Portal

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#211]
My Steps:
- Allow for headers (temporarily) in viv: https://github.com/hubmapconsortium/vitessce-image-viewer/pull/169
- Integrate loading OME-TIFF files into Vitessce.
- Integrate Vitessce with the OME-TIFF loading into the portal.

External Steps:
- Wait for Joel to finish the CODEX pipeline

**Comment by mccalluc** [comment]
@ilan-gold : Have we seen CODEX in the portal? If there's work remaining, file a new smaller bug?

**Comment by ilan-gold** [comment]
This is done.
