### ISSUE TITLE
Integrate scRNASEQ 10X Visualization into Vitessce

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#212]
There should be a json behind the entities-api that we can query for and display as a scatterplot in Vitessce for these scRNASEQ datasets.

**Comment by ngehlenborg** [comment]
Has this been taken care of?

**Comment by ilan-gold** [comment]
I think so.  There's still these other visualizations that we could do that I learned about from Matt after opening this issue: https://github.com/hubmapconsortium/portal-containers/issues/30. Aside from that, there is just the color palette in Vitessce, really.  I'll raise an issue there.

**Comment by ilan-gold** [comment]
Added an issue in Vitessce: https://github.com/hubmapconsortium/vitessce/issues/567

**Comment by keller-mark** [comment]
Going to close this, the portal-containers issue https://github.com/hubmapconsortium/portal-containers/issues/30 should take care of the rest of the data processing steps
