### ISSUE TITLE
Implement metadata table download on search pages

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#2129]
See #2079 for design. [Figma Link](https://www.figma.com/file/pkIZbpJOAQnylo1zjyhaU6/Search-Page?node-id=1362%3A20055). 

The mockup is called v2.0. It is an update to how the search page currently looks on the portal and does not have the molecular & cellular query updates in case this feature gets implemented before that. The 'Add to List' feature/checkboxes in the search results is also in this mockup but does not have to be implemented for this. 

Datasets Dropdown Menu

- The dropdown menu should be a multi-selectable list of data types
- First option should be a option called "All Data Types" and should be selected automatically unless unselected by the user
- Preferably menu should be fixed height and scrollable

**Comment by mccalluc** [comment]
@ngehlenborg -- With a more public exposure of the URL, I would really like the question in
- #2099 
to be resolved before the work here is deployed. Status quo is fine with me, but I'd like that confirmed.

**Comment by mccalluc** [comment]
Declaring this complete. Rather than implement a type pull-down, let's try to get the the code worked out so we can get the current found set: Filed #2166.
