### ISSUE TITLE
set correct column type in LineUp

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#2134]
Quantitative fields are currently configured as text fields in LineUp but should be set up as numeric fields to enable correct sorting and display of appropriate visualizations (histograms, etc.)

<img width="296" alt="image" src="https://user-images.githubusercontent.com/1216518/132707526-c91e03b2-19fb-4ca1-a299-9b7808ca1327.png">

**Comment by mccalluc** [comment]
Types can't safely be inferred from names. I think the best approach will be to add a `field-types.yaml` in `ingest-validation-tools`, and then the portal can reference this from the submodule. 

(Another approach would be to include the type and the description information in a single generated file, but this would necessitate a migration path, and it would make access a little more cumbersome.)

**Comment by mccalluc** [comment]
Fixed by #2273
