### ISSUE TITLE
Mismatched version numbers

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2136]
Changelog says `v0.26.2` ... but there is no such version on [dockerhub](https://hub.docker.com/r/hubmap/portal-ui/tags?page=1&ordering=last_updated)... just `v0.26.3`.

@ilan-gold -- was there anything different that you did with this latest release? Is there a problem with the script?

**Comment by ilan-gold** [comment]
From slack
```
I think I what happened was that my docker crashed during the build so I pruned the system but didn’t remove the tags properly.
```

And the proposed solution

- add `docker system prune` to our script.  I think this has happened to John too.

**Comment by ilan-gold** [comment]
I think another option would be to add a "reversion" step to the deployment so if anything fails, the whole process is reverted i.e docker and github tags/commits.

**Comment by mccalluc** [comment]
@ilan-gold : It looks like `prune` also clears the layer cache. I'd be hesitant to add this as the default: I'm imagining a future maintainer, perhaps also building images for other projects, and every so often their cache gets wiped, and everything needs to be built from scratch. I think they'd have trouble tracking it back to this script.

I'd also be hesitant to rewrite git history: Hopefully nothing goes wrong, but could be dangerous.

It actually doesn't bother me if release numbers are non-sequential.

With those opinions out there, let's step back: maybe we shouldn't even spend time polishing this script, and we should think about continuous deployment instead? [Old issue](https://github.com/hubmapconsortium/portal-ui/issues/1959), closed wont-fix.

@john-conroy / @ilan-gold -- Can you set direction on this, with the goal of minimizing overall hassle? Maybe that's rearchitecting everything... or maybe that's just tolerating the occasional snafus. Put on UI agenda or talk post-standup, if that would be useful.

**Comment by ilan-gold** [comment]
@mccalluc I would be fine with leaving things as-is, with non-sequential version numbers if something goes wrong.  I worry that CI will be its own can of worms in a case like this and we haven't really run into any major issues with the current mechanism.  I am a fan of "if it ain't broke don't fix" and it sounds like we don't consider this broken.

**Comment by ilan-gold** [comment]
FWIW regrading overriding git history - we can't push a `main` branch that has overriden old changes (i.e you can't `git push -f main`), so I think the biggest concern there would be superfluous commits getting added or something during the reversion step.

**Comment by mccalluc** [comment]
@ilan-gold , thanks for the feedback. I'll go ahead and close this... Most of the pain here falls on you guys, so if you decide that on the balance it does make sense to invest some time, feel free!
