### ISSUE TITLE
Design user customizable search columns

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2156]
Different things might matter to different users.

**Comment by tsliaw** [comment]
Notes from breakout session:
- "HuBMAP IDs are just random numbers/letters and don't tell me anything about the datasets. Status is also not as important. Would want user-customizable columns that is personal to users. For example, I want to see donor metadata as a column on dataset search page."

**Comment by tsliaw** [comment]
Mockups: https://www.figma.com/file/pkIZbpJOAQnylo1zjyhaU6/Search-Page?node-id=1584%3A19827

https://user-images.githubusercontent.com/16737715/142465876-9c81cbd3-268e-494f-9db1-51fbe9e6799e.mov

Donor and sample search should behave the same. Datasets will be in a separate github issue.
