### ISSUE TITLE
Fix the styling on the publication page

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2165]
The [one example](https://portal.hubmapconsortium.org/publication/kidney-cell-states-atlas) publication isn't linked yet from the home page. (The TMC needs to configure it.)

With the #2164, Nils confirmed that the structure is right, but the rendering isn't pretty. Might just be a matter of getting the right styling on section titles, but loop in Tiffany if needed.

**Comment by tsliaw** [comment]
This is the design: https://www.figma.com/file/INK3dAMWjyMoUhzpa8K3n0/Pub
![Screen Shot 2021-11-29 at 10 09 16 AM](https://user-images.githubusercontent.com/16737715/143920435-22fc8c71-1806-4d46-a5e2-f3bd2dc9a751.png)
lications?node-id=6%3A1343

The current font size for the paragraphs looks smaller than what we have everywhere else on the portal, but spacing looks better now.
