### ISSUE TITLE
UI support for retracted datasets

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2167]
@shirey will indicate what the flag we should look for is, and provide an example.

@ngehlenborg : I'm guessing we do not want to see retracted datasets in search results? The work that's being done in #2162 would need to be generalized to exclude these as well... or maybe at index time we add a flag that covers all the cases where a dataset should not be in search results?

**Comment by ngehlenborg** [comment]
It should be possible to find retracted datasets through the search interface but by default they should be excluded. Could this be handled as a facet with value `is_retracted` that would be set to `false` for all queries unless explicitly requested?

@shirey could probably comment on how this is handled in the data model. I guess a dataset is either retracted or not retracted. Sometimes people might want to see all that were ever available.

**Comment by ngehlenborg** [comment]
Was the agenda item discussed in any of our portal calls?

**Comment by shirey** [comment]
This was discussed extensively during a portal call, though I'm not sure we got into the UI much.  From my end, I'm adding two fields:
  `sub_status`  which will be set to "Retracted" in this case (and potentially has other  uses later)
  `retraction_reason` a reason for retraction and is required on retraction.
  https://github.com/hubmapconsortium/entity-api/issues/220

**Comment by mccalluc** [comment]
https://portal.test.hubmapconsortium.org/browse/dataset/04e7385339167e541ad42a2636e18398

```
status | "Published"
sub_status | "Retracted"
```

**Comment by mccalluc** [comment]
Details page handing is confirmed: Need to exclude from public search. Currently, [DEV has one public retracted dataset](https://portal.dev.hubmapconsortium.org/dev-search?has_substatus=true).
