### ISSUE TITLE
Support simple visualization of (expression) data

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/portal-ui#22]
Implement a simple expression heatmap at the level of tissues/organs. This visualization should gain many other features over time, but we should start with something straightforward that we can (finish) implement(ing) ASAP.

The human anatomical diagram in production at https://demo1.hubmapconsortium.org/ currently re-colors the organs/tissues after page load, with random values from the REST API. Adjust this to:
1. only re-color the diagram after a user searches for/selects a gene
2. use real data and not random values
3. adjust the color of the organ/tissue outlines in addition to the "fill" color

**Comment by keller-mark** [comment]
Closing this, Vitessce issues should take care of this https://github.com/hubmapconsortium/vitessce/issues/656 https://github.com/hubmapconsortium/vitessce/issues/645
