### ISSUE TITLE
Search by anatomy (heart) returns non-heart samples

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/portal-ui#2218]
This search should just be returning Samples with a RUI location and from Organ: Heart, but the results include at least lymph node and spleen. Points to something terribly wrong!

https://portal.hubmapconsortium.org/dev-search?entity_type[0]=Sample&anatomy_1-anatomy_2-anatomy_3-anatomy_4-anatomy_5[0][0]=heart&has_rui_sample=true

**Comment by mccalluc** [comment]
Notes from 10/29:

> KB “I just checked spleen RUI and only spleen tags are added to tissue block. Please share more info on who created the RUI data you looked at that had LN annotations.”

I don't believe that's true. "[Paracortex](http://purl.obolibrary.org/obo/UBERON_0010417)" is also an annotation on this dataset, and it also occurs in lymph nodes. See https://github.com/hubmapconsortium/search-api/pull/407.

> Leave out the “vasculature” organ; all other 10 organs are a proper tree with body at root.

That can be done, but as the example above demonstrates, it is not sufficient.

> Bruce requests not to remove the code and leave it in DEV search

Sure: The only PR that's out right now removes it from the display code in portal-ui: Having it in the index does no harm until there's a real fix.

**Comment by mccalluc** [comment]
- Closing: We've reverted to the flat list of organs, so the bug is "fixed"... but bringing back the hierarchical facets will require more work: https://github.com/hubmapconsortium/search-api/issues/420
