### ISSUE TITLE
The previous entity version shouldn't be removed from search results until the next version is published

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#2236]
We currently rely on `next_revision_uuid` to determine whether a dataset should be included in search results, but the entity represented by `next_revision_uuid` could not yet be published and available to users resulting in the most recent, published version not being available in the portal. We need a way to determine whether the next version of an entity is published.

**Comment by mccalluc** [comment]
Just talked with Bill: His recollection of the outcome of meeting is that @ngehlenborg would clarify what the desired behavior is. He does not believe there is anything actionable for IEC right now.

**Comment by ngehlenborg** [comment]
@shirey This is from the meeting notes on 11/17: https://docs.google.com/document/d/1ZXQ-tRYbnV1mRqFjaeaUxNPnh-6r6RkvHTzOTP3uk40/edit#heading=h.uw6gjpog7uy1

```
Depend on the next_revision_uuid but a document can have this pointing to another entity that may not be published yet. This stops the user from being able to access that entity with the rest of the data.
- The intention was when someone was no logged in, anything that is related to unpublished data, it should pass back the public version of the information from the index
- Bill will need to review to see if it is working that way
- An unpublished versioned dataset showed up in the public search
```

**Comment by mccalluc** [comment]
(Slacked Bill to say that we think it's in his court.)

**Comment by mccalluc** [comment]
From Bill:
> Currently in the public index public versions only reference public versions but in the private/logged-in index non-public (unpublished) versions can be included at the end of the version chain- we need to keep it this way for use cases that want to find non-published versions.  From our conversation I thought this would work for you?

@john-conroy : Currently, when I am not logged in, there are no datasets with next versions, but if I log in, there are. [Query](https://portal.hubmapconsortium.org/dev-search?has_next=true). Comparing the [JSON](https://portal.hubmapconsortium.org/browse/dataset/b1b4493122e8965e3684b0a7a5dd270a.json) when logged in and logged out:

```
diff <( python -m json.tool ~/Downloads/when-logged-in.json ) <( python -m json.tool ~/Downloads/when-logged-out.json )
1009,1010c1009,1010
<         "datetime": "2021-11-23 11:49:23.657834",
<         "size": 38852,
---
>         "datetime": "2021-11-23 11:49:22.493542",
>         "size": 38772,
1015c1015
<                 "message": "Additional properties are not allowed ('title', 'display_subtype', 'created_timestamp', 'next_revision_uuid', 'published_timestamp', 'hubmap_id', 'index_version', 'immediate_ancestors', 'immediate_descendants', 'dataset_info' were unexpected)"
---
>                 "message": "Additional properties are not allowed ('title', 'display_subtype', 'created_timestamp', 'published_timestamp', 'hubmap_id', 'index_version', 'immediate_ancestors', 'immediate_descendants', 'dataset_info' were unexpected)"
1117d1116
<     "next_revision_uuid": "3bf7c7b6444c3c3d6dbaf543e85cfc2b",
```

The last line is the one that matters: This seems correct to me. If you agree, please close. Thanks!
