### ISSUE TITLE
Implement header redesign

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#2237]
[Figma](https://www.figma.com/file/xUFFDr9TCeOfHxXLHvdn4l/Style-Guide-and-Components?node-id=432%3A0)
<img width="435" alt="Screen Shot 2021-11-10 at 11 46 38 AM" src="https://user-images.githubusercontent.com/16737715/141183039-47ea27b2-644c-4118-be47-96c3246f4414.png">
<img width="1229" alt="Screen Shot 2021-11-10 at 11 46 56 AM" src="https://user-images.githubusercontent.com/16737715/141183045-fa62b1a8-d633-4e5c-991c-bc99378a9f50.png">

**Comment by mccalluc** [comment]
John would also like to handle clipping + accessibility.

**Comment by mccalluc** [comment]
@tsliaw -- I'm not seeing a link to my-lists here... Could it fit under one of the three pulldowns? Sorry if it's there and I'm just missing it.
