### ISSUE TITLE
Include ID of original version next to ID of derived

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2284]
Nils is concerned that the new IDs on each version make it harder to think of it as a single thing. Reference the ID of the original version in the header?

Always show the original HBM version... people should think of it as a star rather than a linked list.

perhaps above on the right?

**Comment by tsliaw** [comment]
Design: https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=2252%3A16115
![Screen Shot 2022-01-11 at 9 15 28 AM](https://user-images.githubusercontent.com/16737715/148989916-f4bda07a-86dc-4424-928d-36ca30ac61a6.png)
