### ISSUE TITLE
Links on organ page not clickable

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#2288]
[Link](https://portal-prod.stage.hubmapconsortium.org/organ/pancreas)

The links in the referenced dataset section are not clickable. If they're not meant to be links, I would prefer them to be the regular black text color. If they are, they should be the 'info' color that we typically use for links. 

![Screen Shot 2021-12-07 at 12 17 50 PM](https://user-images.githubusercontent.com/16737715/145100130-5edffd53-5e6a-4317-af11-07f2b019ba5c.png)

**Comment by mccalluc** [comment]
I think the the problem is that the "Visualization" section below has a high z-index, and top-padding that extends over the "Referenced-Based Analysis" section, so click events are going to the "Visualization" div.
