### ISSUE TITLE
Array not found at path obs/predicted.ASCT.celltype

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/portal-ui#2298]
This is observed on PROD for the new scRNA-seq (10x Genomics) [Salmon] dataset https://portal.hubmapconsortium.org/browse/dataset/7cc96210e80d5736ca38711503e4ff06 .  This is the first to be processed from a new assay type, scRNA-seq (10x Genomics v2) .

**Comment by ilan-gold** [comment]
@jswelling Can you make sure the ASCT-azimuth pipeline was actually run successfully?   It is reported in the DAG  but there do not appear to outputs in the `anndata` store that Matt outputs, `secondary_analysis.h5ad`?  @mruffalo It should be in `obs`, no?
<img width="571" alt="Screen Shot 2021-12-13 at 5 28 18 PM" src="https://user-images.githubusercontent.com/43999641/145850590-4e9e442c-ed0b-4aaf-b316-ba4dc6ef23d4.png">

**Comment by mruffalo** [comment]
@ilan-gold The Azimuth pipeline doesn't include references for most of the tissues/organs, so predicted cell types are not stored for (currently) anything but kidney data sets.

The Azimuth pipeline writes annotation metadata to `.uns['annotation_metadata']` as in:

```
[ruffalo@login000 /hive/hubmap/data/consortium/EXT - Human Cell Atlas/7cc96210e80d5736ca38711503e4ff06]$ ipython
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import anndata

In [2]: d = anndata.read_h5ad('secondary_analysis.h5ad')

In [3]: d.uns
Out[3]: 
OverloadedDict, wrapping:
        {'annotation_metadata': {'is_annotated': False},
```
(irrelevant output after that)

**Comment by ilan-gold** [comment]
Ok so is there any way for us to know what organs this is actually run for besides just inspecting the zarr store directly via `zarr` in the portal backend (which we would rather not do)?

**Comment by mruffalo** [comment]
@ilan-gold by design, not really: the Azimuth pipeline is run for everything and sets `is_annotated` to `False` if there's no reference for that tissue/organ. References can be added whenever is appropriate, with no other part of HIVE infrastructure need to be adjusted after that (no duplication of knowledge of whether a tissue/organ has a reference).

**Comment by ilan-gold** [comment]
Thanks @mruffalo that makes sense.
