### ISSUE TITLE
Show QA/QC results where/when appropriate

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/portal-ui#23]
Related to hubmapconsortium/hubmap-data-portal#7. This applies to both raw and processed data. This will require automated reporting of QA/QC metrics from analysis pipelines, also.

Example from 4DN: https://data.4dnucleome.org/experiment-set-replicates/4DNESH4UTRNL/#graph-section

**Comment by ngehlenborg** [comment]
Will be addressed by #1009.
