### ISSUE TITLE
MALDI-IMS heatmap (?) crashes Chrome

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2304]
Right now, https://portal.hubmapconsortium.org/browse/dataset/c60ace99b7ee9e0d8d635fb7208b4522 consistently crashes Chrome. ("Aw snap! Something went wrong while displaying this webpage. Error code: 5")

FF doesn't crash, but I think there are other problems with this dataset: As I understand, there are multiple pyramids here where we expect only one, because the pipeline just recurses through the directory and handles every OME-TIFF it encounters. I've filed #2305.

@ilan-gold believes the problem that causes the crash is the size of the heatmap, and the only solution may be to exclude it from the visualiztion.

**Comment by ilan-gold** [comment]
This is exactly the image that we are having trouble with with respect to the new pyramid structure.  I think our wires crossed.  I was referring to removing the heatmap to solve https://github.com/vitessce/vitessce/issues/1125.  The issue here is this whole business with `ometiff/separate`

**Comment by mccalluc** [comment]
Sorry to misunderstanding. Closing: Duplicate of #2305

**Comment by ilan-gold** [comment]
Nope this was my fault, sorry to waste your time!
