### ISSUE TITLE
Use `get_view_config_builder` in `test_confs.py`?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2308]
@ilan-gold , to improve our test coverage, and avoid depending on test-only code, I'm wondering how you would feel about 
```diff
- AssayViewConfClass = AssayConfClasses[assay]
+ AssayViewConfClass = get_view_config_builder(entity)
```
in `test_confs.py`?

If I make this tweak (for the real thing, would figure out the mocking):
```diff
- type_client = TypeClient(current_app.config["TYPE_SERVICE_ENDPOINT"])
+ type_client = TypeClient('https://search.api.hubmapconsortium.org')
```
... then it fails with:
```
>                    for dag in entity['metadata']['dag_provenance_list'] if 'name' in dag]
E       KeyError: 'metadata'
```

Is there reason I couldn't just add the this information to the JSON fixtures? It feels like that that would a good part of the logic to have tested, too.

**Comment by ilan-gold** [comment]
I think this would work!
