### ISSUE TITLE
CODEX dataset, vitessce error

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2345]
https://portal.hubmapconsortium.org/browse/dataset/35ea0ff39fc1bd6846df15860dead4d3

(requires login)

on FF, in an error box in Vitessce:
```
i is undefined
```
on Chrome:
```
Cannot read properties of undefined (reading 'offset')
```
Looking in the console doesn't help much.

**Comment by ilan-gold** [comment]
https://github.com/geotiffjs/geotiff.js/issues/193 has resurfaced because it was not re-implemented when the new fetching mechanism was implemented: https://github.com/geotiffjs/geotiff.js/pull/94

We run on a fork of geotiff so I can fix this myself.

**Comment by ilan-gold** [comment]
To reproduce the issue where a fetch is made out of range (which is the issue as linked):

1. Download the mask from this dataset and either start a local file server to serve the file to Avivator
2. Look at the network requests
3. Notice the 416 error
<img width="1440" alt="Screen Shot 2022-01-11 at 6 57 39 PM" src="https://user-images.githubusercontent.com/43999641/148996508-eccc2dc1-4ce2-4a0e-ba58-ca676920f4b6.png">

**Comment by mccalluc** [comment]
Underlying fix has been made in viv... need to get that into vitessce ... and then get that into portal.
