### ISSUE TITLE
Revisit deleted user list: JS Error

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2380]
If I revisit a deleted list, I get a JS error. On FF:

> Error
> URL: https://portal.stage.hubmapconsortium.org/my-lists/d67c4a41-642e-4061-8041-836f843efae7
>
> TypeError: u is undefined

An error is fine, but it should be something more like a soft 404, not some cryptic internal problem.

**Comment by lchoy** [comment]
Created https://hms-dbmi.atlassian.net/browse/HMP-241.

**Comment by NickAkhmetov** [comment]
Fixed in #3206
