### ISSUE TITLE
Safari: Portal visualization of 3D IMC : WebGL2 viewer not working for this dataset

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/portal-ui#2385]
I activated WebGL2 to visualize the 3D IMC but can't see anything. Is this issue known to the team:
https://portal.hubmapconsortium.org/browse/dataset/cd880c54e0095bad5200397588eccf81
![Screen Shot 2022-01-26 at 12 19 32 PM](https://user-images.githubusercontent.com/8284878/151213871-52ac10e9-210a-409a-8701-8c8d7e5c890b.png)

**Comment by mccalluc** [comment]
@cebriggs7135 : What browser are you using?

**Comment by cebriggs7135** [comment]
Safari. When you select any of the 3D options in the dropdown you see above, that's what the message that appearsin the black viewer says to use to get WebGL2.

**Comment by mccalluc** [comment]
@cebriggs7135 -- I'm on Safari `Version 14.1.2 (16611.3.10.1.6)` and don't have a problem with any of the down-sampled 3D options. Can you check your version number, and if it's not out of date, let's do a screenshare after standup so I can see exactly what you're seeing. Thanks!

**Comment by cebriggs7135** [comment]
I have an older version and not enough room on my personal laptop to upgrade to the latest version of Catalina & Safari. I'll pick up my work laptop from IT this week and try on that.

**Comment by keller-mark** [comment]
It is working on my end so it would be helpful to know the Safari version you are running @cebriggs7135.
I am on Safari `Version 15.0 (16612.1.29.41.4, 16612)` and macOS Big Sur


![Screen Shot 2022-02-02 at 10 18 25 AM](https://user-images.githubusercontent.com/7525285/152182793-f69f2bcc-8e6a-4ccc-88d4-f6950308a71b.png)

**Comment by keller-mark** [comment]
Unrelated issue, but when I open the full screen mode I see extra HTML elements
![Screen Shot 2022-02-02 at 10 21 07 AM](https://user-images.githubusercontent.com/7525285/152183050-40e7d086-5ddd-4cf9-8b6e-e01db9c8af18.png)

**Comment by ngehlenborg** [comment]
> I have an older version and not enough room on my personal laptop to upgrade to the latest version of Catalina & Safari. I'll pick up my work laptop from IT this week and try on that.

Can you please let us know what version of Safari you're running?

**Comment by keller-mark** [comment]
You should be able to find out by clicking Safari > About Safari
<img width="308" alt="Screen Shot 2022-02-02 at 12 25 42 PM" src="https://user-images.githubusercontent.com/7525285/152205325-4fdb7049-2172-4db2-b8ad-25afe4a3012b.png">

**Comment by ngehlenborg** [comment]
@cebriggs7135 Could you please provide your Safari version so that we can address this?

**Comment by cebriggs7135** [comment]
Version 13.1.1 (15609.2.9.1.2)

**Comment by mccalluc** [comment]
I think this is purely a vitessce issue, so I'll move the issue, and the team can decide if it's worth investing more time.

**Comment by mccalluc** [comment]
I've just put this on the agenda for tomorrow, Feb 10.

**Comment by mccalluc** [comment]
Omics meeting didn't happen. Put on next UI meeting.

**Comment by mccalluc** [comment]
We reviewed the client versions, and clients this old are rare enough that we decided not to invest any time here.
