### ISSUE TITLE
In Vitessce, use Hugo IDs rather than Ensembl IDs

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2393]
The Ensembl IDs just aren't human-readable. Matt says Hugo IDs are in there... but Sean clarifies that it isn't filled out for every dataset. This depends on Vitessce functionality to alias fields from AnnData that aren't indexed. (Sorry if I'm not using the right terms to describe this!)

Vitessce blocker, and more details:
- https://github.com/vitessce/vitessce/issues/1147

**Comment by SFD5311** [comment]
Also worth noting, I think, in case y'all weren't aware:
Mappings from Ensembl IDs to hugo gene symbols aren't 1-to-1, so there are going to be some gene symbols which correspond to multiple Ensembl IDs/columns in the data matrix.
