### ISSUE TITLE
Organ pages: Use CCF API instead of hard-coding

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2396]
From @bherr2 :

> Yes, the CCF-API should be pretty good for getting you the reference organ info with https://ccf-api.hubmapconsortium.org/#/operations/reference-organs
> 
> Right now we have the AS and reference organs integrated into the CCF-API. We will eventually do more with CT and B types. So, there might be some use for you depending, but otherwise the ASCT+B API would be better.

(Don't invest time until #2394 is merged.)

**Comment by mccalluc** [comment]
[Started a branch](https://github.com/hubmapconsortium/portal-ui/compare/mccalluc/ccf-api-for-organs?expand=1), but have not made a PR. In my mind it would be a good thing if we could rely on APIs for data, instead of hard-coding it in the source. @bherr2, Let me know if you all are not on the same page.

Two areas of work: First, fields that could be added to the CCF API which are currently hard-coded in portal-ui:
- organ descriptions
- URLs for icons

Second, there are a number of differences in the URIs recognized by the component you've delivered, and the URIs returned by your API:

<details><summary>differences</summary>

```
{'http://purl.obolibrary.org/obo/UBERON_0000029': 'Lymph Node',
 'http://purl.obolibrary.org/obo/UBERON_0000056': 'Ureter',
 'http://purl.obolibrary.org/obo/UBERON_0000970': 'Eye',
 'http://purl.obolibrary.org/obo/UBERON_0000992': 'Ovary',
 'http://purl.obolibrary.org/obo/UBERON_0001465': 'Knee',
 'http://purl.obolibrary.org/obo/UBERON_0002048': 'Lung',
 'http://purl.obolibrary.org/obo/UBERON_0002049': 'Vasculature',
 'http://purl.obolibrary.org/obo/UBERON_0002113': 'Kidney',
 'http://purl.obolibrary.org/obo/UBERON_0002367': 'Prostate',
 'http://purl.obolibrary.org/obo/UBERON_0003889': 'Fallopian Tube'}
Reference organ URI not in descriptions:
{'http://purl.obolibrary.org/obo/FMA_24977': 'Right Knee',
 'http://purl.obolibrary.org/obo/FMA_24978': 'Left Knee',
 'http://purl.obolibrary.org/obo/FMA_54449': 'Right Eye',
 'http://purl.obolibrary.org/obo/FMA_7213': 'Right Ovary',
 'http://purl.obolibrary.org/obo/FMA_7214': 'Left Ovary',
 'http://purl.obolibrary.org/obo/UBERON_0000079': 'Prostate',
 'http://purl.obolibrary.org/obo/UBERON_0001004': 'Lung',
 'http://purl.obolibrary.org/obo/UBERON_0001222': 'Right Ureter',
 'http://purl.obolibrary.org/obo/UBERON_0001223': 'Left Ureter',
 'http://purl.obolibrary.org/obo/UBERON_0001302': 'Right Fallopian Tube',
 'http://purl.obolibrary.org/obo/UBERON_0001303': 'Left Fallopian Tube',
 'http://purl.obolibrary.org/obo/UBERON_0002108': 'Small Intestine',
 'http://purl.obolibrary.org/obo/UBERON_0002509': 'Lymph Node',
 'http://purl.obolibrary.org/obo/UBERON_0004537': 'Blood Vasculature',
 'http://purl.obolibrary.org/obo/UBERON_0004538': 'Left Kidney',
 'http://purl.obolibrary.org/obo/UBERON_0004539': 'Right Kidney',
 'http://purl.obolibrary.org/obo/UBERON_0004548': 'Left Eye'}
```

</details>

- The CCF component knows about the higher-level URIs for paired organs (`UBERON_0000970` for eye, vs. `UBERON_0004548` left + `FMA_54449` right). Is there some other way of confirming through the API that the higher-level URIs are correct?
- In that particular case, is there are reason left and right aren't coming from the same place?
- For some organs, the API is just returning a different URI for the same organ. Is the API wrong? `UBERON_0000079` vs. `UBERON_0002367` for prostate.
- Others are similar, but not quiet the same: "Vasculature" vs "Blood vasculature"

**Comment by bherr2** [comment]
>     * The CCF component knows about the higher-level URIs for paired organs (`UBERON_0000970` for eye, vs. `UBERON_0004548` left + `FMA_54449` right). Is there some other way of confirming through the API that the higher-level URIs are correct?

Yes, this is done in a kinda hacky way that we will work on making cleaner. 

>     * In that particular case, is there are reason left and right aren't coming from the same place?

Yes, there is. Right kidney reference organ is different from left kidney reference organ and have different terms associated with them.

> 
>     * For some organs, the API is just returning a different URI for the same organ. Is the API wrong? `UBERON_0000079` vs. `UBERON_0002367` for prostate.

If you look at the terms you'll see that <http://purl.obolibrary.org/obo/UBERON_0000079> is male reproductive system and <purl.obolibrary.org/obo/UBERON_0002367> is prostate gland. Some reference organs include more than the reference organ that you might think of. For instance the "Lung" reference organ is actually the respiratory system and includes several organs including trachea, left lung, right lung, left bronchi, and right bronchi. To support that, we associated multiple terms with a reference organ.

> 
>     * Others are similar, but not quiet the same: "Vasculature" vs "Blood vasculature"

Blood Vasculature is a subclass of Vasculature. We used to have a ref organ named "Vasculature" and used the more generic term, but we now use the more specific Blood Vasculature.

**Comment by mccalluc** [comment]
Given that the status quo works, and a complete alignment doesn't look easy, and since we don't think external users would benefit much from it, we're not going to invest more time here. Closing.

... but feel free to reopen if there are aspects of this worth completing.
