### ISSUE TITLE
Visualize data processing pipeline runs

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/portal-ui#24]
Adapt the 4DN workflow visualization function to our data portal, and use this to show the results of our data analysis runs. The 4DN interface consists of a large amount of ReactJS code, so this won't be trivial.

Example: https://data.4dnucleome.org/experiment-set-replicates/4DNESH4UTRNL/#graph-section

Additional information:
- Each node in the visualization represents either a data file (at different levels of processing) or a workflow run
- Clicking each node shows details about that data file or workflow run, allowing for (direct?) downloading of data
- Workflow runs should link to the “abstract” workflow (with no concrete input/output files), and to the implementation of the workflow in GitHub/Docker Hub/Dockstore/etc.
- Either convert Research Object (RO) output to input of visualization diagram, or adjust visualization diagram to read this directly

**Comment by mccalluc** [comment]
This was implemented a while ago. It needs refinements (in particular, handling large numbers of outputs), but there are separate issues for those.
