### ISSUE TITLE
Design display for license

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2431]
- #1305 ... **cc-by 4.0** 

Now we need a design...
- Where? In the footer? In the file download UI?
- What? "CC BY 4.0"? Text of license? Link to https://creativecommons.org/licenses/by/4.0/ ?

**Comment by mccalluc** [comment]
Needs to be run by PIs for approval.

**Comment by tsliaw** [comment]
Designs:
- [Data Use Agreement page Figma](https://www.figma.com/file/9nlXn9704s2zQ9CRvAQTXU/Data-Use-Agreement?node-id=0%3A1)
- [Home Page Changes](https://www.figma.com/file/cEZdI2tOMByTBW8RQ2kuAm/Home-Page?node-id=1550%3A2649)
- [Dataset Detail Page Changes](https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=2456%3A13797)

Designs are complete and approved. Will close this issue for implementation issue, but implementation needs to wait for feedback from legal.
