### ISSUE TITLE
Support New General Purpose SPRM-Anndata directory structure

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#2438]
We are in the process of settling on a directory structure that all future large, segmented, sprm-analyzed, anndata-backed, datasets can use.  The directory structure has been finalized and Cell Dive conforms to it.  Future CODEX-Cytokit-SPRM runs will as well (@jswelling reference PR or issue here?).  To resolve this issue we need to 
a) Make sure https://github.com/hubmapconsortium/portal-visualization/pull/3 is compatible with all datasets that already exist
b) Merge https://github.com/hubmapconsortium/portal-visualization/pull/3
The issue here is that in order to have the portal backend recognize these sorts of segmented, sprm-analyzed, anndata-backed, datasets, we are using hints that apply to an entire assay.  But switching all of the old CODEX-cytokit hints to these new hints would trick the portal into thinking that these old datasets obey the new directory structure, which they don't.

Therefore @jswelling and I decided to mark these older runs as "v1" via https://github.com/hubmapconsortium/search-api/pull/443 because we cannot give separate hints to datasets with a given `data_type`.  So the solution was to just give them a new `data_type` and give all future CODEX runs a different name.

At the moment, we have confirmed that future codex runs can conform to the directory strucutre (https://portal.dev.hubmapconsortium.org/browse/dataset/28f0d8a7e1eb06593fe5d323f1f850a1), Cell DIVE works with [the PR in](https://github.com/hubmapconsortium/portal-visualization/pull/3) (https://portal.dev.hubmapconsortium.org/browse/dataset/48f0a5ae6fa636266df3dff4cd1033aa) and old stitched CODEX runs work as well (https://portal.dev.hubmapconsortium.org/browse/dataset/9fec34311ea03c4a5c221e65b1d881ba).

The ooutstanding blocker here is that I want to see an old non-stitched CODEX dataset work before giving the all clear.  This does not seem to exist on dev (https://portal.dev.hubmapconsortium.org/browse/dataset/b69d1e2ad1bf1455eee991fce301b191 for example has not been marked as "v1" and so shows an error).

**Comment by mccalluc** [comment]
I don't understand the big picture, but
> To resolve this issue we need to
> a) Make sure https://github.com/hubmapconsortium/portal-visualization/pull/3 is compatible with all datasets that already exist
> b) Merge https://github.com/hubmapconsortium/portal-visualization/pull/3

It's now merged, so what next?

**Comment by mccalluc** [comment]
Ilan says:
> I think this is indeed done now.

Closing.
