### ISSUE TITLE
Design for DOI on dataset pages

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2453]
Assuming it should be similar to [collection pages](https://portal.hubmapconsortium.org/browse/collection/4964d24bbc6668a72c4cbb5e0393a6bc) ... Just need to decide whether it goes above or below the assay / organ info.

**Comment by tsliaw** [comment]
<img width="1522" alt="Screen Shot 2022-02-24 at 9 08 56 AM" src="https://user-images.githubusercontent.com/16737715/155572838-3e4ecb0c-379d-4e6f-9019-6512d82aba0f.png">

**Comment by mccalluc** [comment]
Thanks -- will implement
