### ISSUE TITLE
Reactivesearch updates are very slow

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#2459]
Updates to the entity search pages using `reactivesearch` are very slow taking seconds to render. The network requests to elasticsearch only take ~50-100ms. 

Removing each filter's dependency on other search components (other filters, search input) via the `react` prop fixes the issue, but the aggregations are not updated to reflect the results.

**Comment by mccalluc** [comment]
John says there's less support than we hoped. Not going in this direction.
