### ISSUE TITLE
Not getting metadata for CODEX [Cytokit + SPRM] notebook

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2498]
- [start here](https://portal-prod.stage.hubmapconsortium.org/search?mapped_data_types[0]=CODEX%20%5BCytokit%20%2B%20SPRM%5D&entity_type[0]=Dataset)
- download notebook

```
response = requests.post(
    "https://portal-prod.stage.hubmapconsortium.org/metadata/v0/datasets.tsv", json={"uuids": uuids}
)
metadata = list(DictReader(StringIO(response.text), dialect=excel_tab))

pd.DataFrame(metadata[:1]).T.head()
```
only returns 3 fields.

**Comment by ngehlenborg** [comment]
![image](https://user-images.githubusercontent.com/1216518/157764405-18441810-3087-4390-90ef-7b9909f73713.png)

**Comment by mccalluc** [comment]
The issues here are not particular to the notebook environment:
- This is a processed dataset: User-supplied metadata is on its parent. If you want the metadata to be propagated to descendants, that should be done back at the index, or neo4j.
- In the UI, on the details page, we do show sample and donor metadata, but the TSV download, which the notebook relies upon, only has _dataset_ metadata. I think the reasoning was that the number of columns was already unwieldy, and it makes sense for each endpoint to do one thing well.

Closing since there's not a bug here, but I'll put an item on the UI agenda to ask what we can do.
