### ISSUE TITLE
Missing Donor

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2514]
When logged out, [this recently published snRNA-seq](https://portal.hubmapconsortium.org/browse/dataset/da93581ef554e25ec1c7a12500a56b74) does not have a Donor in the prov table: The donor and origin sample are only in the private index so they aren’t returned from ES when logged out. When logged in the table is correct. (Thanks to John for diagnosis!) Bill Shirey, can you get someone to:
- Fix this instance.
- Look for other similar cases, and correct them as well.
- Propose a fix to the publication process so this doesn’t happen again?

**Comment by ngehlenborg** [comment]
Some additional observations to report on this:

1. Not good that private/unpublished donor and sample information is exposed through metadata:
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/1216518/158883395-a46ce77d-844b-47a2-9851-14e3059e856c.png">

2. IDs and provenance for unpublished donor and sample are included in the provenance graph display while missing from the tabular view (given that the donor is unpublished, it probably shouldn't be exposed through the provenance graph):
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/1216518/158883440-d991fe84-fabf-4dcb-85b0-74d8133fb327.png">

3. But donor is indeed not accessible even with direct link:
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/1216518/158883532-5e47450c-dd97-4c87-a2eb-9aed3186baf0.png">

**Comment by mccalluc** [comment]
Bill fixed the data, so there's a Donor now. There wasn't any retrospective: Not sure why it happened, or if it's less likely to happen in the future.
