### ISSUE TITLE
Show graph of how much data (cells/experiments/images/etc.) we have, by tissue

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/portal-ui#26]
A prototype version of these graphs is currently implemented, but we'll want some more functionality for these. At least, we should probably show additional data per unit time, such as the number of cells, experiments, and images.

We should show these as cumulative graphs with time on the *x*-axis.

**Comment by mccalluc** [comment]
John has implemented the homepage visualization we need for now: #497
