### ISSUE TITLE
Show male/female human anatomical diagrams on front page

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/portal-ui#27]
These diagrams should contain outlines of the organs/tissues from which the HuBMAP consortium has collected data. These diagrams should be interactive; clicking an organ/tissue should do one or more of the following:
* Filter the "data by time" plot to include only that tissue/organ
* Show a tabular list of experiments which profiled that organ
* Show genes which are differentially express in that tissue vs. the rest of the human body

... and anything else that seems appropriate.

Specific functionality for the anatomy diagram should probably be tracked with separate GitHub issues.

**Comment by tsliaw** [comment]
Decided design for home page to include bar graph visualization instead of human anatomy diagram since it was a better representation of the data.
