### ISSUE TITLE
Friendlier error if workspace auth fails

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2718]
Workspace auth seems to be flakey: 
- https://github.com/hubmapconsortium/user_workspaces_server/issues/58

We don't want to bother anyone with a big warning at login time if the process has failed, but we should have some messaging on the workspaces page if nothing is going to work.

**Comment by jpuerto-psc** [comment]
Is it possible to have a "workspaces temporarily unavailable" message here? Something like a yellow caution block?
