### ISSUE TITLE
`KeyError: 'files'`

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2772]
Spotted in logs: (at least) two published production datasets produce this:

https://portal.hubmapconsortium.org/browse/dataset/c6a254b2dc2ed46b002500ade163a7cc
https://portal.hubmapconsortium.org/browse/dataset/eaad5ed4b3aa2186bd87e05ff28b593e

```
File "/Users/chuck/github/hubmap/portal-ui/context/app/routes_browse.py", line 60, in details
conf_cells_uuid = client.get_vitessce_conf_cells_and_lifted_uuid(entity, marker=marker)
File "/Users/chuck/github/hubmap/portal-ui/context/app/api/client.py", line 166, in get_vitessce_conf_cells_and_lifted_uuid
derived_entity['files'] = derived_entity['metadata']['files']
```

**Comment by mccalluc** [comment]
Bill says: "nothing has changed on PROD for quite a while."

> Publication Date
> 2020-08-22
> Modification Date
> 2022-02-11

Could revert portal code to earlier state and see how it behaves.

Looking at the JSON: There is `immediate_descendants[1].metadata.files`. Should this be vis-lifted?

**Comment by mccalluc** [comment]
Trying to revert: 
- Same error at [v0.47.1](https://github.com/hubmapconsortium/portal-ui/commit/83aaffaa1c4f894135cd576f82b68122ec2f7ea2)
- Same error at [v0.37.2](https://github.com/hubmapconsortium/portal-ui/commit/043fd1feb9043edf85ad112a7a178f81c4fcc2f5) (February 9; before the dataset's modification date.)

Looking at similar datasets: There are 9 published `seqFISH` all from CalTech, three each of small intestine, spleen and heart. Vis-lifted visualization works for these, except 2 from heart tissue: The same two that we saw in the log.

Next: Compare these two to the heart dataset that does work to understand the difference.

**Comment by mccalluc** [comment]
Bill says it's in their court:
>  I think this is related to a problem that was reported previously, we’ve got a fix in for it (but hasn’t been released yet pending this whole other search-api reorg that we’re doing).

**Comment by mccalluc** [comment]
This heart seqFish works: https://portal.hubmapconsortium.org/browse/dataset/8f0becaf2d0eea9df67e45b8d66d69ac.json
- Two `descendants`: `seqFish_lab_processed` and `image_pyramid`+`seqFish`
- The latter has `metadata.files`

This heart seqFish does not work: http://localhost:5001/browse/dataset/eaad5ed4b3aa2186bd87e05ff28b593e.json
- Two descendants: `seqFish_lab_processed` and `image_pyramid`+`seqFish`
- The latter has `metadata`, but no `files` under it.

**Comment by mccalluc** [comment]
Bill suggested he understood the problem this morning. Asked for more info.

**Comment by mccalluc** [comment]
Bill says he will look more closely at this and reach out when he understands it better.

**Comment by mccalluc** [comment]
Scanned all the datasets and found two more similar errors:
```
d55e751748bd094ff5b0b55befb08d41	Image pyramid assay with uuid 0f3894d45b772804de43137fa8c353ed has no matching files
d3e05111d84be552b98f5fe2b18e3054	Image pyramid assay with uuid 3af85031cea5b0c772212855550cc3b1 has no matching files
```

**Comment by yuanzhou** [comment]
FYI @mccalluc @shirey I can confirm the issue has been addressed in search-api will soon be released to PROD.

**Comment by shirey** [comment]
@mccalluc The above datasets with errors were tested against the new, `/v3/` instance of the search-api/indices and none had errors.  The issue had to do with the `.files` attribute being missing from previously available locations in the ES documents- I think `descendants.metadata.files` was the one that fixed it, but we added `.files` back to multiple places where they used to be so I can't be 100% sure of the exact field that it was looking for.

**Comment by mccalluc** [comment]
Confirmed that http://localhost:5001/browse/dataset/eaad5ed4b3aa2186bd87e05ff28b593e works on main. This will be deployed to stage later today. Closing
