### ISSUE TITLE
Document JS dev process

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#280]
@john-conroy : Can you add a section to the README about the dev process we should have for JS?
- Install prettier plugin for you IDE?
- I've just been `npm run dev-build`ing, but setting up a rebuild on change shouldn't be impossible?
- How tests can be organized. (Same directory / separate directory?)
- Other things?

**Comment by ilan-gold** [comment]
Are we using prettier?  +1 For that, I like it a lot.

**Comment by john-conroy** [comment]
We have yet to agree upon prettier. I am in favor of it, but in the meantime I've been using an eslint extension to format.

**Comment by john-conroy** [comment]
Additional documentation was added.
