### ISSUE TITLE
Handle empty files array in search api v3 when generating Vitessce confs

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#2816]
From Bill:

> We found an issue with Vitesse and the new https://search.api.hubmapconsortium.org/v3/ indices.  These new indices are now providing an empty array for files everywhere instead of just no filed at all or and empty object (this is a fix for something else that hadn’t been released yet that we discussed a while ago)-- It looks like Vitesse is trying to display even though there are no files.

**Comment by mccalluc** [comment]
More context:

Bill:

> Right, but check https://portal.test.hubmapconsortium.org/browse/dataset/906ce8025bd07f04fe6a33d1a4daf400, which is connected to the new, v3 version of the indices.

John

> Gotcha, we look for files in the top level of the dataset document. In the TEST link, there is the empty files array.
> ```
>         elif 'files' not in entity or 'data_types' not in entity:
>             vitessce_conf = ConfCells(None, None)
> ```
> where entity is the dataset document returned from search-api.
