### ISSUE TITLE
Twitter on homepage is taking full height

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2856]
Both on production and stage. Maybe something in their widget changed? Or weird CSS side-effect from some unrelated change on our side.

**Comment by john-conroy** [comment]
https://twittercommunity.com/t/new-timeline-embed-is-not-respecting-documented-parameters/175729

**Comment by john-conroy** [comment]
https://twittercommunity.com/t/suggestions-for-the-new-twitter-embed/175690/5

**Comment by mccalluc** [comment]
Home page looks ok with the last PR, but the list isn't scrollable.
