### ISSUE TITLE
How to handle excessively large documents?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#289]
Nils writes:
> I am trying to access this dataset but it is taking forever to load (something is happening but I haven’t seen anything rendered on the page so far): https://portal.test.hubmapconsortium.org/browse/dataset/aedc30c204870180673b6ece299f2eb1 - do you have any idea what might be going wrong?
> 9:50
> Oh!!! The server response for that document is ~20MB
> 9:51
> Something must be wrong
> 9:54
> 127234 files referenced in that document …

**Comment by ilan-gold** [comment]
In addition to this, I think it would be good to understand why the CODEX output is so large in the first place and see if we can get the HIVE team to not index everything they see.  I have a funny feeling that a lot of that stuff consists of intermediary outputs.

**Comment by ngehlenborg** [comment]
There is a related issue for the ingest pipeline: https://github.com/hubmapconsortium/ingest-pipeline/issues/64

**Comment by mccalluc** [comment]
We believe we've tackled it with the manifest, and the URL in the original issue doesn't link, so I'll close this.

... but what we don't have is any easy way to find excessive response documents... but we could add that to our portal index! Filed https://github.com/hubmapconsortium/search-api/issues/73
