### ISSUE TITLE
Utility button bar overlaps with top of visualization in full screen mode on preview pages

### ISSUE THREAD

**Issue by keller-mark** [hubmapconsortium/portal-ui#2897]
The Vitessce element on the preview pages seems to be too tall so the top (and the toast message) becomes hidden under the top bar containing the share/theme/fullscreen buttons. It seems to occur on the Preview pages but not on the Dataset pages.

<img width="3005" alt="Screen Shot 2022-09-09 at 9 45 46 AM" src="https://user-images.githubusercontent.com/7525285/189364712-e3581b99-8e88-42f4-9a1b-16f51da45c92.png">

**Comment by NickAkhmetov** [comment]
Corresponding JIRA ticket: https://hms-dbmi.atlassian.net/browse/HMP-102
Fixed in #3102
