### ISSUE TITLE
protocols.io failure on some Donor pages

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2925]
https://portal-prod.stage.hubmapconsortium.org/browse/donor/fde7ac63c666fdaebe21e187293a8685

There is a "protocols" section on the page, but it stalls on "Please wait..."

It looks like we're trying to request
> https://www.protocols.io/api/v3/protocols/v1?last_version=1

but that doesn't seem right... there should be an ID in there. 

I suspect the JSON for this Donor is bad or has an unexpected structure, and we're trying to make a url from an empty string.

**Comment by mccalluc** [comment]
```
$ curl -s https://portal.hubmapconsortium.org/browse/donor/fde7ac63c666fdaebe21e187293a8685.json | jq '.protocol_url'
"dx.doi.org/10.17504/protocols.io.5qpvob93dl4o/v1, dx.doi.org/10.17504/protocols.io.dm6gpb7p5lzp/v1"
```
To be addressed upstream:
- We're not expecting a comma delimited list: Clarify whether we should (which would be weird), or if the response structure will change (better, but more work)
- Even without that, a hostname without a protocol is not a URL: If used as a URL, will turn into a bad relative link. Should be corrected.
- There should have been validation or QA that caught this earlier. Improve process.

For the portal:
- We're also not expecting the `/v1`: We're splitting at the final slash.

**Comment by ngehlenborg** [comment]
Just to confirm: the issue is also present on the production portal: https://portal.hubmapconsortium.org/browse/donor/fde7ac63c666fdaebe21e187293a8685

**Comment by yuanzhou** [comment]
I looked at the backend data attribute, and we do have inconsistent value format, for examples:
- "[dx.doi.org/10.17504/protocols.io.7hhhj36](http://dx.doi.org/10.17504/protocols.io.7hhhj36)" (the majority of the cases)
- "dx,doi,org/10.17504/protocols.io.568g9hw" (typo?)
- "10.17504/protocols.io.bqi6muhe" (start with specific DOI prefix)
- "https://dx.doi.org/10.17504/protocols.io.btnfnmbn" (with https://)
- "[dx.doi.org/10.17504/protocols.io.yxmvmnye5g3p/v2](http://dx.doi.org/10.17504/protocols.io.yxmvmnye5g3p/v2)" (with version number)
- "[dx.doi.org/10.17504/protocols.io.5qpvob93dl4o/v1](http://dx.doi.org/10.17504/protocols.io.5qpvob93dl4o/v1), [dx.doi.org/10.17504/protocols.io.dm6gpb7p5lzp/v1](http://dx.doi.org/10.17504/protocols.io.dm6gpb7p5lzp/v1)" (multiple values of comma separated, and with the version number)

**Comment by tsliaw** [comment]
https://portal-prod.stage.hubmapconsortium.org/browse/donor/3ac683032d95311f68b4af38c240a9bc
@john-conroy Doing QA on the portal and this issue is still present for some donors if you want to take a look at this.

Protocols API is producing a 400 error, and it's showing the "Please wait..." message.
![Screen Shot 2023-04-17 at 9 16 50 AM](https://user-images.githubusercontent.com/16737715/232547579-5af983c7-82f3-42a4-bb7b-9d1ecf6f6ee9.png)

**Comment by NickAkhmetov** [comment]
#3165 adjusted the handling protocols lookups to handle all the various formats described above.
