### ISSUE TITLE
Disclaimer at the top of cells

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2938]
From Nils:

> Cells API next steps:
> - PIs agreed that a beta release to a targeted audience would be the most reasonable next step
> - **On our end, we need to update the UI with “disclaimers” at the top of the page**
> - We should explore if we can integrate a “walk through” feature like the one that we have on the standard dataset search page (but don’t need to implement this)
> - There will be a broader discussion about proper mapping of entities in the data (proteins/image channels, cell types) to appropriate ontologies or controlled vocabularies 

we need the exact text for the disclaimer

**Comment by ngehlenborg** [comment]
Here's the proposal language (we might need @tsliaw to update the design to insert an additional box if it becomes too crowded in the current one):

> Retrieve datasets based on the abundance of transcriptomic, epigenomic, and proteomic biomarkers across cells. For example, you can retrieve a list of datasets where normalized transcript abundance for the UMOD (uromodulin) gene is above a user-defined cut off, e.g., 1, in at least 5% of all cells. This query will return a list of kidney datasets.
> To begin your search, select a query type ("Gene" for transcriptomic and epigenomic measurements, "Protein" for proteomic measurements) and set the desired parameters.
>
> Molecular data queries are in beta testing and there is a list of [known issues<LINK TO ISSUES TAGGED WITH "bug" AND "cells"?>](). In the future, [additional types of queries<LINK TO REPO WITH USE CASES?>]() will be supported.

@mruffalo: 
 1. Can you help with the language for the cut off? I am still not exactly sure what the meaning of that variable is and how one should use it.
 1. I assume the cut off has no unit. Is that correct? 
 1. Also, what is the quantity that is being measured for the protein queries? (right now it says "expression", which we will need to fix (see #2939).

**Comment by ngehlenborg** [comment]
@mruffalo @SFD5311: could you take a look at this issue and help with the language?

**Comment by ngehlenborg** [comment]
@mruffalo @SFD5311 We really need this to roll out the beta! Can you please provide a description by 2022-11-23? Thank you!

**Comment by mruffalo** [comment]
@ngehlenborg

- Genome annotations for RNA-seq and ATAC-seq don't always match due to differing pipeline needs, meaning that genes suggested by the typeahead dropdown may not actually be present for a given modality
- Gene expression doesn't actually match the actual counts in datasets; we compute an RPKM value, implemented at https://github.com/hubmapconsortium/cross-dataset-diffexpr/blob/master/bin/annotate_concatenate.py#L45
- We use CODEX dataset channels as-is, so the index currently contains multiple ways of specifying the same protein, to be corrected upstream in the CODEX (and other) pipelines
- Cell type availability is limited to datasets processed by Azimuth, which is "kidney only, but not many" at the moment

**Comment by ngehlenborg** [comment]
Based on the input by @mruffalo and @SFD5311, I have come up with the final text for the info box:

> Retrieve datasets based on the abundance of transcriptomic, epigenomic, and proteomic biomarkers across cells. For example, you can retrieve a list of datasets where normalized transcript abundance for the UMOD (uromodulin) gene is above a user-defined cut off, e.g., 1, in at least 5% of all cells. This query will return a list of kidney datasets.
> To begin your search, select a query type ("Gene" for transcriptomic and epigenomic measurements, "Protein" for proteomic measurements) and set the desired parameters. The nature of the cut off values is modality dependent, e.g., RPKM for transcriptomics.
>
> Molecular data queries are in beta testing and there is a list of [known issues<LINK TO ISSUES TAGGED WITH "bug" AND "cells"?>](). In the future, [additional types of queries<LINK TO REPO WITH USE CASES?>]() will be supported.
