### ISSUE TITLE
Organs: Why FMA instead of UBERON?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2942]
We want the different components of HuBMAP to align on organ terms. One challenge is when different groups use different IDs for the same concept. The CCF API uses an FMA ID in some cases when an UBERON exists. Why?

- FMA_7214/FMA_7213 : Left/right ovary
- FMA_24978/FMA_24977 : Left/right knee

Looking at the first one: [Ontobee FMA](https://ontobee.org/ontology/FMA?iri=http://purl.obolibrary.org/obo/FMA_7214) vs [OLS UBERON](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002119) (I might be doing it wrong, but Ontobee doesn't seem to cover UBERON URIs, and conversely, OLS doesn't seem to cover FMA... but could be doing it wrong.)

<details><summary>CCF API snippet</summary>

```
    {
        "@id": "http://purl.org/ccf/latest/ccf.owl#VHFLeftOvary",
        "@type": "SpatialEntity",
        "label": "Left Ovary",
        "creator": "Kristin Browne",
        "creator_first_name": "Kristin",
        "creator_last_name": "Browne",
        "creation_date": "2022-06-22T00:00:00.000Z",
        "representation_of": "http://purl.obolibrary.org/obo/FMA_7214",
        "reference_organ": "http://purl.org/ccf/latest/ccf.owl#VHFLeftOvary",
        "sex": "Female",
        "side": "Left",
        "rui_rank": 160,
        "x_dimension": 12.277396000000003,
        "y_dimension": 23.946987300000004,
        "z_dimension": 10.5341728,
        "dimension_units": "millimeter",
        "object": {
            "@id": "http://purl.org/ccf/latest/ccf.owl#VHFLeftOvaryObj",
            "@type": "SpatialObjectReference",
            "file": "https://ccf-ontology.hubmapconsortium.org/objects/v1.2/VH_F_Ovary_L.glb",
            "file_format": "model/gltf-binary",
            "file_subpath": "VH_F_left_ovary"
        }
    },
```

</details>

For now, this is just a question.

**Comment by bherr2** [comment]
Yeah, for those with FMA at the time there was not an appropriate Uberon term at the time. We are working to get new terms in Uberon and shift remaining FMA (and also a few LMHA) terms to Uberon.

**Comment by mccalluc** [comment]
Cool. Question is answered, and the organs page doesn't depend on any of the FMAs right now, so I think this can be closed.
