### ISSUE TITLE
Add Cluster ID and Cell Type name to tooltip in Vitessce

### ISSUE THREAD

**Issue by morganlturner** [hubmapconsortium/portal-ui#3000]
Cluster ID and Cell Type name need to be added to the Vitessce tooltip. 
These should likely appear just below Cell ID information.

**Comment by NickAkhmetov** [comment]
This appears to already be in place; the tooltip currently displays the hovered cell's values for every column in Cell Sets and expression values for any indicated marker genes.
e.g.: https://portal.hubmapconsortium.org/browse/dataset/bca0d1d7fcb2bdcde16a31d1484e83e5 and https://portal.hubmapconsortium.org/browse/dataset/e695c48cb6be99479daefaf372743f65 have different tooltips
![image](https://github.com/hubmapconsortium/portal-ui/assets/19957804/5f6b5a5d-982e-41d8-9c02-9ada8467814b)
![image](https://github.com/hubmapconsortium/portal-ui/assets/19957804/7d1068e8-0f6c-4aa6-aa22-0daae1510e8f)
