### ISSUE TITLE
When vitessce is closed background paper component remains

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#301]

**Comment by mccalluc** [comment]
@john-conroy : Can you give more description / screenshot / reproducer? I'm not sure if you mean the panels inside Vitessce, or minifying after being in full-window mode, or something else, but to me it seems to work.

**Comment by john-conroy** [comment]
Sorry, I'll be better about attaching screenshots to issues where applicable. The issue can be observed when you close the panels within Vitessce.

<img width="1127" alt="Screen Shot 2020-06-21 at 1 41 48 PM" src="https://user-images.githubusercontent.com/62477388/85231464-27730500-b3c5-11ea-9d9c-38fb072425a3.png">

<img width="1148" alt="Screen Shot 2020-06-21 at 1 41 19 PM" src="https://user-images.githubusercontent.com/62477388/85231465-293cc880-b3c5-11ea-9c4f-a5e2d99ce3b9.png">

**Comment by mccalluc** [comment]
Ok - I see what you're saying. I feel like this behavior is ok, but what's missing is something like [the ability to open new panes](https://github.com/hubmapconsortium/vitessce/issues/242), or [restore a previous state](https://github.com/hubmapconsortium/vitessce/issues/241), or disabling pane-closing in the portal.

I'd suggest closing, but if you think neither of those would really address your concern, this might go on the agenda for after release?
