### ISSUE TITLE
Document organ metadata logic

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#302]
I believe samples derived from other samples do not have organ data, but the logic should be confirmed before documenting.

**Comment by mccalluc** [comment]
@john-conroy : When I filter to a derived sample type, facets for organs are still available: https://portal.hubmapconsortium.org/search?mapped_specimen_type[0]=FFPE%20slide&entity_type[0]=Sample

So maybe whatever the original problem was has been solved? Closing, but reopen and clarify, if you think it's still useful.
