### ISSUE TITLE
Bad link for v1.0 lung on asctb-tables page

### ISSUE THREAD

**Issue by dw-dot** [hubmapconsortium/portal-ui#3027]
https://humanatlas.io/asctb-tables
With the HRA v1.0 ASCTB tables selected, clicking the Lung ASCTB table link will not send me to the Lung v1.0 table. Instead it sends me to https://humanatlas.io/722.

**Comment by bherr2** [comment]
@dw-dot wrong repository! https://github.com/cns-iu/humanatlas.io is the right one :-D
