### ISSUE TITLE
Add better error catching for vitessce conf generation

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#3044]
We've seen recurring 500s on raw datasets when trying to generate vitessce confs from derived datasets missing metadata. We need to add better error handling to provide more accurate error messages and allow the parent dataset to load without a visualization.

**Comment by NickAkhmetov** [comment]
Corresponding JIRA ticket: https://hms-dbmi.atlassian.net/browse/HMP-100
Fixed in #3106
