### ISSUE TITLE
Add sorting button on organ pages sample table's columns

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#3049]
![Screen Shot 2023-03-22 at 8 35 29 AM](https://user-images.githubusercontent.com/16737715/226956792-12d420dd-a584-4283-892c-88b3ec7532b6.png)

**Comment by lchoy** [comment]
Filed https://hms-dbmi.atlassian.net/browse/HMP-321

**Comment by NickAkhmetov** [comment]
Fixed in #3232
