### ISSUE TITLE
Wrong blue for link on organ page 

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#3050]
Use the regular link blue for the link in the "Reference-Based Analysis" section on organ pages. Currently is #0000EE, should be the info color.

![image](https://github.com/hubmapconsortium/portal-ui/assets/45410262/09774276-1d51-4f72-95bd-9d3ae6db2ef8)

**Comment by john-conroy** [comment]
This is coming from the organ markdown and won't be a straightforward fix.

**Comment by lchoy** [comment]
Filed https://hms-dbmi.atlassian.net/browse/HMP-320

**Comment by NickAkhmetov** [comment]
Fixed in #3220
