### ISSUE TITLE
Add "Download Jupyter notebook" button when Vitessce is fullscreen view

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#3057]
Jupyter notebook download button is not there when Vitessce is fullscreen.

![Screen Shot 2023-03-24 at 12 17 35 PM](https://user-images.githubusercontent.com/16737715/227619513-c34b2247-fc88-4b46-adcd-5a402f76cff9.png)

**Comment by NickAkhmetov** [comment]
Corresponding JIRA issue: https://hms-dbmi.atlassian.net/browse/HMP-97
Fixed in #3101
