### ISSUE TITLE
extra semicolon in collection block on dataset page

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#3098]
The additional semicolon should not be shown below the block, see, e.g., https://portal.hubmapconsortium.org/browse/dataset/0487454555924b54dd3f5b5232e3c77e#collections 

<img width="1139" alt="image" src="https://github.com/hubmapconsortium/portal-ui/assets/1216518/1b95fed8-fbe1-457a-abd1-c121f247ac7b">

**Comment by lchoy** [comment]
Fixed in #3105
