### ISSUE TITLE
Get assurance that API will provide what we need

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#31]
I've written up a [document](https://docs.google.com/document/d/1SewJnLgg6x-9juLdW7lXF-NzfDWJlGr-REjJgEtWe4c/edit#) detailing what we need from the API. @shirey will review this,  and either assure us that all of this will be provided by the API, at some point, or suggest that we need to find a different way of satisfying individual items.

**Comment by shirey** [comment]
I've review the document referenced above and left several comments.  We're on the same page, I don't see a problem with creating APIs to handle everything that you're thinking of there.

**Comment by mccalluc** [comment]
Cool: I'm going to copy your comments into the body of that document, and file issues if they don't already exist. Closing.
