### ISSUE TITLE
LineUp dashboard for samples error message when logged in

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#3119]
When I access https://portal.hubmapconsortium.org/lineup/samples without being logged in it works (displays LineUp visualization for all public samples), but I get an UI error when I try to access that URL when being logged into the portal. 

<img width="1470" alt="image" src="https://github.com/hubmapconsortium/portal-ui/assets/1216518/0cadfb0a-707c-46f5-8099-32a87f01c42e">

**Comment by ngehlenborg** [comment]
As of June 16th, we are also seeing this issue with the datasets _when the user is *not* logged in_:

<img width="1470" alt="image" src="https://github.com/hubmapconsortium/portal-ui/assets/1216518/7cbb00c6-af6a-4450-aa1b-ee3d5bd6c438">

**Comment by NickAkhmetov** [comment]
Corresponding JIRA ticket: https://hms-dbmi.atlassian.net/browse/HMP-182

**Comment by lchoy** [comment]
Fixed in #3132
