### ISSUE TITLE
theming issue affecting Vitessce instances with Layer Controller view

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#312]
Problem: the theme from the portal is partially applied to the Vitessce instance.

Example: https://portal.test.hubmapconsortium.org/browse/dataset/9e04dbf8d911c2c875fc961d5b25286a

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/1216518/82237593-e722f180-9903-11ea-821d-cc96ec7b6dc8.png">

**Comment by ilan-gold** [comment]
Just saw this too.  Thanks for opening the issue.  It does not seem to be an issue on my local instance so it might be something specific to our production build.
<img width="1662" alt="Screen Shot 2020-05-18 at 12 37 08 PM" src="https://user-images.githubusercontent.com/43999641/82237867-54368700-9904-11ea-9796-8eaff71f82e6.png">

**Comment by keller-mark** [comment]
If i may add: in vitessce we are now using the option `disableGlobal: true`. You may also want to try this for the parts of the portal that are also using material UI, but set a different seed value https://material-ui.com/styles/api/#creategenerateclassname-options-class-name-generator

**Comment by keller-mark** [comment]
Note: at that Material UI page, they also document something called `options.productionPrefix` but when I tried that in vitessce I could not figure out what difference it was making - it did not seem to affect the classnames in the production css bundle

**Comment by john-conroy** [comment]
I'll give that a try for the portal, thanks!
