### ISSUE TITLE
publication page should not show link to support dataset Globus directory in Files section

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#3125]
<img width="1196" alt="image" src="https://github.com/hubmapconsortium/portal-ui/assets/1216518/ba6f6706-2bb9-457c-b4c2-039390c09e50">

The second entry to the "Bulk Data Transfer (Support)" Globus directory should be hidden. It is meaningless for end users (unlike the image pyramid datasets).

**Comment by lchoy** [comment]
Fixed in #3137
