### ISSUE TITLE
[Ticket #3671] User Account Login in Data Portal doesn't work

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/portal-ui#3139]
## Feedback
Ticket History

Eric Moerth wrote: 
Hi 

I had contacted my local helpdesk and it doesn't look like a problem with Harvard Key. 

I think it is a problem on the HubMap side of things. 

Hope you can help me with that. 

Best, 

Eric Moerth, PhD

Chris Csonka wrote: 
Emailed requestor suggesting they seek relief from their [Harvard's] IT support.

Chris Csonka wrote: 
Hi Eric, 

We have had other users from Harvard experience issues using the Harvard 

key when logging in to the HuBMAP Consortium site or the HuBMAP Data portal. 

We recommend contacting your [Harvard] IT support regarding this issue. 

Also, be sure you are logging in using this approved identity ( 

[ericmoerth@fas.harvard.edu](mailto:ericmoerth@fas.harvard.edu)) . 

Please give that a try and get back to the Help desk if you are still 

experiencing issues. 

Thank you, 

Chris Csonka 

HuBMAP Helpdesk

Dear Hubmap Help,

I have registered for the hubmap portal and now when trying to logging in via Harvard Key I always get an internal server error.

My username is:
[ericmoerth@fas.harvard.edu](mailto:ericmoerth@fas.harvard.edu)

Furthermore I get stuck at the following page:
[https://portal.hubmapconsortium.org/login?code=sN2dVtuajSUwYdqaLIDbMf1KebX8dt&state=_default](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fportal.hubmapconsortium.org%2Flogin%3Fcode%3DsN2dVtuajSUwYdqaLIDbMf1KebX8dt%26state%3D_default&data=05%7C01%7Czhy19%40pitt.edu%7Cfb68c5cec8f24a7dda2208db735991eb%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C638230600777362661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SyvWOFl7kbyH6ZL4cart7Yw14%2FmLyDLZ%2FprEFoYMzyc%3D&reserved=0)

Hope you can help me with that.

Best,
Eric Moerth, PhD

@Chris-Csonka this is something the portal-ui team may help. I tried that link and got the 500 error too.
![image](https://github.com/hubmapconsortium/portal-ui/assets/195873/795a8b23-2966-4e8d-8100-e2633f435c1f)

**Comment by ngehlenborg** [comment]
The problem was that the email address was not fully registered for Globus. This was resolved manually with the of the HuBMAP Admin team. 

<img width="955" alt="image" src="https://github.com/hubmapconsortium/portal-ui/assets/1216518/a1e3e24e-99a2-4f03-af9a-f98849fa8c08">

<img width="955" alt="image" src="https://github.com/hubmapconsortium/portal-ui/assets/1216518/fa352b29-ace5-4520-9fff-2809d49cedfd">
