### ISSUE TITLE
"Derived samples" search returns empty result even though derived samples exist

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#314]
**Problem**: Searching for derived samples fails. 

Donor: https://portal.test.hubmapconsortium.org/browse/donor/2ef76fe31f322fb2349e97eb8ee549e8

<img width="1612" alt="image" src="https://user-images.githubusercontent.com/1216518/82240745-ef316000-9908-11ea-9cf2-be4c9613e216.png">

Clicking on the "Derived Samples" link produces empty search results:

<img width="1612" alt="image" src="https://user-images.githubusercontent.com/1216518/82240862-24d64900-9909-11ea-8212-e88a1491af2c.png">

Sample (one of several derived from the above donor): 
https://portal.test.hubmapconsortium.org/browse/sample/036aedbe6ea79708c5d77756e63b2c7f

<img width="1612" alt="image" src="https://user-images.githubusercontent.com/1216518/82240794-053f2080-9909-11ea-9f76-46d8f7c14a9a.png">

**Comment by john-conroy** [comment]
I believe this worked up until the portal search wrapper change?

**Comment by ngehlenborg** [comment]
Yes, it worked until Friday last week afaik.
