### ISSUE TITLE
Replace EUI screenshot in carousel on landing page with up-to-date screenshot

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/portal-ui#3271]
The landing page at https://portal.hubmapconsortium.org/ has a carousel, which shows a screenshot of the EUI (https://portal.hubmapconsortium.org/ccf-eui). This screenshot is **heavily** outdated. Can you please use the below instead?

Old:
![image](https://github.com/hubmapconsortium/portal-ui/assets/22821046/7af4079f-2476-4bf0-8168-74510352a1e9)

New:
![image](https://github.com/hubmapconsortium/portal-ui/assets/22821046/f9b5ef93-54f4-4460-876d-e15783af7484)

**Comment by NickAkhmetov** [comment]
Hi @andreasbueckle, thanks for providing this replacement screenshot! It definitely makes sense to update this image given the dramatic difference.

I've created a corresponding JIRA issue: https://hms-dbmi.atlassian.net/browse/HMP-417

**Comment by andreasbueckle** [comment]
@NickAkhmetov 
We have an updated screenshot, thanks for your patience, see below!

Updated text: 
**Navigate anatomical structures across scales with the Human Reference Atlas**
Explore the healthy human body via the Anatomical Structures, Cell Types and Biomarkers (ASCT+B) Tables linked to existing ontologies using the Registration User Interface (RUI) for tissue data registration and Exploration User Interface (EUI) for exploring experimental data semantically and spatially. 

![image](https://github.com/hubmapconsortium/portal-ui/assets/22821046/d74adbfb-3713-460f-be07-e84978be46fb)
