### ISSUE TITLE
Object with key "src_data/experiment.json" as React child

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#331]
On http://localhost:5000/browse/dataset/99c90fd778f652b5f0dc4e2f337d4791 / git: c11a5b1

> Error: Objects are not valid as a React child (found: object with keys {src_data/experiment.json, src_data/segmentation.json}). If you meant to render a collection of children, use an array instead.

<details>

    in td (created by ForwardRef(TableCell))
    in ForwardRef(TableCell) (created by WithStyles(ForwardRef(TableCell)))
    in WithStyles(ForwardRef(TableCell)) (created by MetadataTable)
    in tr (created by ForwardRef(TableRow))
    in ForwardRef(TableRow) (created by WithStyles(ForwardRef(TableRow)))
    in WithStyles(ForwardRef(TableRow)) (created by MetadataTable)
    in tbody (created by ForwardRef(TableBody))
    in ForwardRef(TableBody) (created by WithStyles(ForwardRef(TableBody)))
    in WithStyles(ForwardRef(TableBody)) (created by MetadataTable)
    in table (created by ForwardRef(Table))
    in ForwardRef(Table) (created by WithStyles(ForwardRef(Table)))
    in WithStyles(ForwardRef(Table)) (created by MetadataTable)
    in div (created by ForwardRef(TableContainer))
    in ForwardRef(TableContainer) (created by WithStyles(ForwardRef(TableContainer)))
    in WithStyles(ForwardRef(TableContainer)) (created by Styled(WithStyles(ForwardRef(TableContainer))))
    in Styled(WithStyles(ForwardRef(TableContainer))) (created by MetadataTable)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by MetadataTable)
    in div (created by styled.div)
    in styled.div (created by MetadataTable)
    in MetadataTable (created by DatasetDetail)
    in div (created by ForwardRef(Container))
    in ForwardRef(Container) (created by WithStyles(ForwardRef(Container)))
    in WithStyles(ForwardRef(Container)) (created by Styled(Styled(WithStyles(ForwardRef(Container)))))
    in Styled(Styled(WithStyles(ForwardRef(Container)))) (created by DatasetDetail)
    in div (created by ForwardRef(Container))
    in ForwardRef(Container) (created by WithStyles(ForwardRef(Container)))
    in WithStyles(ForwardRef(Container)) (created by Styled(WithStyles(ForwardRef(Container))))
    in Styled(WithStyles(ForwardRef(Container))) (created by DatasetDetail)
    in DatasetDetail (created by Routes)
    in Routes (created by App)
    in div (created by App)
    in ThemeProvider (created by App)
    in App

</details>

[99c90fd778f652b5f0dc4e2f337d4791.json.txt](https://github.com/hubmapconsortium/portal-ui/files/4646280/99c90fd778f652b5f0dc4e2f337d4791.json.txt)

**Comment by mccalluc** [comment]
@john-conroy : Could you look at these two cases? (on test APIs):
http://localhost:5001/browse/dataset/99c90fd778f652b5f0dc4e2f337d4791
http://localhost:5001/browse/dataset/fd1c1ab4890f527704b20de52b797551

They are both showing that same error.

**Comment by john-conroy** [comment]
I'll take a look.

**Comment by mccalluc** [comment]
Filed https://github.com/hubmapconsortium/search-api/issues/72 to get clarification on whether this is a case we need to be able to handle.

**Comment by mccalluc** [comment]
Neither of the two cases I cited earlier (on TEST) are still there, so without a reproducer, I'll close this.
