### ISSUE TITLE
Better changelog pattern with multiple devs?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#332]
When it was just me, doing the changelog by hand was fine... but now we get merge conflicts all the time. It's a headache. Is the a better practice we should follow? cc @ilan-gold / @john-conroy .

**Comment by john-conroy** [comment]
Gitlab uses [this](https://docs.gitlab.com/ee/development/changelog.html) which may be intensive for our needs, but I like the idea of each of us creating separate files which are then compiled into changelog entries at the time of release.
