### ISSUE TITLE
Incorporate advanced JSON viewer

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#333]
Instead of showing bare JSON we should set up a JSON viewer with 

- [ ] syntax highlighting
- [ ] folding
- [ ] search (optionally)

The MS Monaco editor (w/ r/o) is looking promising: https://microsoft.github.io/monaco-editor/

**Comment by mccalluc** [comment]
The browser provides each of these features for free. I'd be very reluctant to spend developer time on this.

**Comment by ngehlenborg** [comment]
Can you be more specific?

**Comment by mccalluc** [comment]
FF renders it as a nice fold-down by default:
<img width="485" alt="Screen Shot 2020-05-18 at 10 21 46 PM" src="https://user-images.githubusercontent.com/730388/82277526-16fae500-9956-11ea-80ee-b573a522dd7f.png">

... but Chrome doesn't. It looks like it should be able to format it in dev tools, but right now it's not working for me. So, not quite as low a priority, but pretty low. :)
