### ISSUE TITLE
portal returning "Internal Server Error" (500) for certain datasets

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#335]
Problem: the portal UI returns a 500 error for certain datasets

Reproduce:
Access https://portal.test.hubmapconsortium.org/browse/dataset/662ef4c9807517df51554a6fa6ba33e3
(Dataset ID HBM657.ZRBM.357, LC-MS-untargeted submitted by Vanderbilt TMC, status new). 

Viewing the JSON for this dataset works: https://portal.test.hubmapconsortium.org/browse/dataset/662ef4c9807517df51554a6fa6ba33e3.json

I have found this problem with every single Vanderbilt TMC dataset (independently of the status) as well as several other data sets.

**Comment by mccalluc** [comment]
Every Vanderbilt dataset has the same problem, we think...
