### ISSUE TITLE
Design error pages

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#339]
I think Nils wants some of the Hubmap colors on the error pages. Not clear if there needs to be any substantial difference in treatment for 4xx vs 5xx.

**Comment by mccalluc** [comment]
- See also: #351: 404 pages are being rendered differently, depending on context.
- See also: #406: Error messages should be updated.

**Comment by tsliaw** [comment]
https://www.figma.com/file/aLzj4gBvpOVdXvD5TrzTRt/Portal-Site-v.1?node-id=580%3A6

**Comment by mccalluc** [comment]
Oy! That's colorful. I would drop the border, or at least pull the title inside the border, but really between you and Nils. Thanks!

**Comment by tsliaw** [comment]
Updated Figma Design: https://www.figma.com/file/xQvctr8yojWLHlDXMAhKrL/Error-Pages?node-id=46%3A21

**Comment by tsliaw** [comment]
<img width="519" alt="Screen Shot 2020-08-14 at 11 24 26 AM" src="https://user-images.githubusercontent.com/16737715/90281001-b9751800-de20-11ea-9a62-8dbaa20adbc0.png">

**Comment by ngehlenborg** [comment]
Approved version is here: https://www.figma.com/file/xQvctr8yojWLHlDXMAhKrL/Error-Pages?version-id=422935672&node-id=1%3A3&viewport=-2545%2C2004%2C0.4815593361854553
