### ISSUE TITLE
Design re-usable entity tiles

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#340]
We want tiles that can summarize the key information for Donors, Samples, and Datasets, and could be used either in search results, or in the provenance table.

**Comment by tsliaw** [comment]
https://www.figma.com/file/aLzj4gBvpOVdXvD5TrzTRt/Portal-Site-v.1?node-id=543%3A18

**Comment by ngehlenborg** [comment]
I approved this version: https://www.figma.com/file/pkIZbpJOAQnylo1zjyhaU6/Search-Page?version-id=370650921&node-id=1%3A2&viewport=2914%2C1312%2C0.7021380662918091

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/1216518/85902694-a8216f00-b7d2-11ea-8034-d2f7e7c86b8e.png">
