### ISSUE TITLE
There are two different 404 pages 

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#351]
We seem to have two different implementations of the 404 page at the moment:

Go to: https://portal.test.hubmapconsortium.org/about:
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/1216518/83012881-0992ca00-9fea-11ea-9016-f6acd43ff827.png">

Go to https://portal.test.hubmapconsortium.org/browse/sample/8426f37e8e2001b5cb7849b34ba06dd:
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/1216518/83012941-23341180-9fea-11ea-83d4-768c30a74af2.png">

The look of the 404 page should be identical for all errors.

**Comment by mccalluc** [comment]
fixed
