### ISSUE TITLE
mxIF Data Integration

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#358]
Our Pipelines:
- [TIFF Tiler/Pyramid](https://github.com/hubmapconsortium/portal-containers/tree/master/containers/ome-tiff-tiler)
 - [TIFF Offsets](https://github.com/hubmapconsortium/portal-containers/tree/master/containers/ome-tiff-offsets)
- [SPRM](https://github.com/hubmapconsortium/portal-containers/tree/ilan-gold/sprm/containers/sprm-to-json)

TMC:
- Vanderbilt
 - [x] TIFF Pyramid (Visualized in portal)
 - [ ] SPRM? (Visualized in portal)

Outstanding Issues:
 - The main thing is what is happening with SPRM.  I heard once that it was being run on this data but I am not clear.

**Comment by mccalluc** [comment]
@ilan-gold : Is this issue still useful, or could it be closed?

**Comment by ilan-gold** [comment]
I think we can close this since mxIF will never be in the portal.
