### ISSUE TITLE
Evaluate typography

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/portal-ui#386]
We need to come to a consensus on typography in the theme.

**Comment by ngehlenborg** [comment]
We will use only Inter 300 and Inter 500.

**Comment by tsliaw** [comment]
Updated typography according to portal style guide: https://www.figma.com/file/xUFFDr9TCeOfHxXLHvdn4l/HuBMAP-Design-Systems?node-id=33%3A1842
