### ISSUE TITLE
Should docker build be split off?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#412]
@ilan-gold and @john-conroy : Do you think it would be worthwhile to separate the docker build from the rest of portal-ui? At this point, I think our build process is pretty stable... but rebuilding docker each time is probably doubling the length of our travis runs, and makes it unlikely that anyone runs test.sh locally.

More specifically, I'd propose a new repo `portal-ui-docker` with a Dockerfile that would checkout `portal-ui` at a particular tag, and then follow the same build process from there.

**Comment by john-conroy** [comment]
I think it makes sense. The travis builds are taking a long time.

**Comment by ilan-gold** [comment]
I don't understand too deeply what is going on here, but if the issue is only the time for travis/local testing, we could just run those tests on PR/Merge instead of every commit and then use what we already have for a local virtual environment for the tests.  I am, however, partial towards monorepos.

**Comment by mccalluc** [comment]
@john-conroy : How do you feel about this now? Running tests against the build has caught problems a couple times... I'm thinking of my last PR to pull in the version number... but you are right: It is slow. On the other hand, I am very rarely waiting for it: I'll make the PR, and then move on to something else... Your workflow may be different.

If we did move this forward, I'd use make this a submodule of the new repo, and have the script be responsible for updating master here, and in the new containing repo... Typing it out, I worry a bit about the complexity: It's do-able... just worry if it's really worth it.

**Comment by mccalluc** [comment]
@john-conroy : any thoughts about this?

**Comment by mccalluc** [comment]
John will look at best practices.

**Comment by mccalluc** [comment]
@john-conroy -- My sense is that github CI runs faster, so the time it takes to run is less of an issue... We could still split it out, but I think the added complexity would not be a good trade-off. Closing... but reopen if you think this could still be a good idea.
