### ISSUE TITLE
select final Inter font weights

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#441]
To reduce bundle size, we need to remove unused Inter font weights by finalizing our selection of fonts to be used in the portal UI.

**Comment by ngehlenborg** [comment]
Required for #382.

**Comment by tsliaw** [comment]
https://www.figma.com/file/xUFFDr9TCeOfHxXLHvdn4l/HuBMAP-Design-Systems?node-id=33%3A1842
