### ISSUE TITLE
Implement click-through agreement

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#443]
@ngehlenborg will deliver text, and specify the logic.

Questions:
- Is this a modal? A bottom of the page gdpr-style click-through? A full page?
- When is this presented? On welcome page? On details?
- I think I've heard that this is about downloading data... Is viewing imagery a "download" in this sense, or do we only mean looking at a list of files and "downloading" there?
- Is it ok if this is only a UI layer, and not actually enforced by the assets API?

**Comment by mccalluc** [comment]
Got clarifications:
> Before the user clicks to download the first file, there should be a modal to confirm or deny. That they could go through the API is not a concern.

**Comment by ngehlenborg** [comment]
Draft text for the message:

**Appropriate Use**
Users of HuBMAP open-data or processed data agree not to use the requested datasets, either alone or in concert with any other information, to identify or contact individual participants or family members from whom data and/or samples were collected.

**Acknowledgement**
Investigators using HuBMAP data in publications or presentations are requested to cite _The Human Body at Cellular Resolution: the NIH Human BioMolecular Atlas Program_ (doi:[10.1038/s41586-019-1629-x](https://doi.org/10.1038/s41586-019-1629-x)) and to include an acknowledgement of HuBMAP. Suggested language for such an acknowledgment is: “The results <published or shown> here are in whole or part based upon data generated by the NIH Human BioMolecular Atlas Program (HuBMAP): https://hubmapconsortium.org."

**Data Sharing Policy**
The HuBMAP Data Sharing Policy can be found at [https://hubmapconsortium.org/policies/](https://hubmapconsortium.org/policies/).

**Comment by ngehlenborg** [comment]
Final mockup in https://github.com/hubmapconsortium/portal-ui/issues/637.

**Comment by ngehlenborg** [comment]
Revised messages:

---

# HuBMAP _Public Data_ Usage

**Appropriate Use**
By downloading HuBMAP raw or processed data and using this data alone or combined with any other information, you affirm you will abide by rules set by the HuBMAP _Data Sharing Policy_; including not re-identifying or contacting sample donors or their families and maintaining confidentiality of HuBMAP participant data.

**Acknowledgement**
Investigators using HuBMAP data in publications or presentations are requested to cite _The Human Body at Cellular Resolution: the NIH Human BioMolecular Atlas Program_ (doi:[10.1038/s41586-019-1629-x](https://doi.org/10.1038/s41586-019-1629-x)) and to include an acknowledgement of HuBMAP. Suggested language for such an acknowledgment is: “The results <published or shown> here are in whole or part based upon data generated by the NIH Human BioMolecular Atlas Program (HuBMAP): https://hubmapconsortium.org."

**Data Sharing Policy**
The HuBMAP Data Sharing Policy can be found at [https://hubmapconsortium.org/policies](https://hubmapconsortium.org/policies).

---

# HuBMAP _Controlled Data_ Usage

**Appropriate Use**
You are attempting to download data *accessible only to HuBMAP Members*. By downloading HuBMAP raw or processed data and using this data alone or combined with any other information, you affirm you will abide by rules set by the HuBMAP _Data Sharing Policy_ and by provisions of the _Data Use Agreement_ signed by your institutional signatory; including not re-identifying or contacting sample donors or their families and maintaining confidentiality of HuBMAP participant data. You are not permitted to email or to transfer HuBMAP data to collaborators.

**Acknowledgement**
Investigators using HuBMAP data in publications or presentations are requested to cite _The Human Body at Cellular Resolution: the NIH Human BioMolecular Atlas Program_ (doi:[10.1038/s41586-019-1629-x](https://doi.org/10.1038/s41586-019-1629-x)) and to include an acknowledgement of HuBMAP. Suggested language for such an acknowledgment is: “The results <published or shown> here are in whole or part based upon data generated by the NIH Human BioMolecular Atlas Program (HuBMAP): https://hubmapconsortium.org."

**Data Sharing Policy**
The HuBMAP Data Sharing Policy can be found at [https://hubmapconsortium.org/policies](https://hubmapconsortium.org/policies).

---

# HuBMAP _Genomic Sequence Data_ Usage

**Appropriate Use**
You are attempting to download protected genomic sequence data *accessible only to HuBMAP Members who have requested and been granted access*. Access to these data will be made available in dbGAP for non-consortium members. By downloading HuBMAP raw or processed data and using this data alone or combined with any other information, you affirm you will abide by rules set by the HuBMAP _Data Sharing Policy_, by provisions of the _Data Use Agreement_ signed by your institution and the NIH Genomic Data Sharing Policy; including not re-identifying or contacting sample donors or their families and maintaining confidentiality of HuBMAP participant data. You are not permitted to email or to transfer HuBMAP data to collaborators.

**Acknowledgement**
Investigators using HuBMAP data in publications or presentations are requested to cite _The Human Body at Cellular Resolution: the NIH Human BioMolecular Atlas Program_ (doi:[10.1038/s41586-019-1629-x](https://doi.org/10.1038/s41586-019-1629-x)) and to include an acknowledgement of HuBMAP. Suggested language for such an acknowledgment is: “The results <published or shown> here are in whole or part based upon data generated by the NIH Human BioMolecular Atlas Program (HuBMAP): https://hubmapconsortium.org."

**Data Sharing Policy**
The HuBMAP Data Sharing Policy can be found at [https://hubmapconsortium.org/policies](https://hubmapconsortium.org/policies).
