### ISSUE TITLE
Design entity tile states for hover vs. clicked vs. current

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#446]
https://www.figma.com/file/aLzj4gBvpOVdXvD5TrzTRt/Portal-Site-v.1?node-id=543%3A18

**Comment by tsliaw** [comment]
Updated provenance table with hover state and current state. Figma link: https://www.figma.com/file/pkIZbpJOAQnylo1zjyhaU6/Search-Page?node-id=40%3A397

![provenancetable](https://user-images.githubusercontent.com/16737715/85757896-b3867480-b6c4-11ea-870c-05833a5c6d5c.gif)

**Comment by ngehlenborg** [comment]
Looking good!

**Comment by ngehlenborg** [comment]
@john-conroy: approved design is here: https://www.figma.com/file/pkIZbpJOAQnylo1zjyhaU6/Search-Page?version-id=374311040&node-id=1%3A2&viewport=1849%2C937%2C0.48279786109924316
