### ISSUE TITLE
Update provenance table design

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#452]
https://www.figma.com/file/aLzj4gBvpOVdXvD5TrzTRt/Portal-Site-v.1?node-id=543%3A18

**Comment by ngehlenborg** [comment]
Let's discuss in our meeting next week. It is looking pretty good but I am wondering if we can do something about the box-in-a-box look. It might not be possible though.

**Comment by ngehlenborg** [comment]
Decided to revisit box-in-a-box issue later.
