### ISSUE TITLE
Integrate Real Data into Preview

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#454]
Once we have real data, we should replace the URL's in #451 with `assets` urls and potentially alter them to add a token.

**Comment by mccalluc** [comment]
@ilan-gold : I don't think any harm is being done by referencing the s3 buckets? It feels like this is in the same neighborhood as integrative-analysis-visualizations, but I don't think the particular work outlined here really needs to be done... but reopen if I'm mistaken.

**Comment by ilan-gold** [comment]
I didn't have a chance to say this in the meeting yesterday @mccalluc but we could replace the preview for Spraggins multi-modal with real data (as this issue mentions) which would be "integrative analysis" since it would only be HuBMAP data.  But no harm is being done ATM.  This is similar to what I proposed for turning the "previews" page into a place for links that automatically compile the lists needed for the visualization.
