### ISSUE TITLE
Show status and descendants in dev-search

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#463]
A simple view where we can see the list of data sets, their status, and if they have a derived dataset and the status of the derived data set, all grouped by data type. It would be help us and the IEC to get a better handle on the amount of work that lies ahead.

@mccalluc comments:
```
- status is easy.
- We haven’t been using it, but I have seen a descendants prop like the ancestors we do use. But - I’m not sure if it’s official, or consistent
- I would be more surprised if it also had the status of the descendant.
- Could get that by iterating over the list and querying, or maybe doing a multi-id query… but that’s significant development effort.
- Sorting by datatype wouldn’t be hard.
```

@mccalluc additional comments:
```
- Quickest way is to take the existing dataset search, sort by type,  up the rows, and see if columns can be added for the information you want.
- Realize that every deployment environment and public/private distinction would give you a different result.
```

**Comment by mccalluc** [comment]
Dashboard in one environment and one access level is a very different thing than a CLI reporting tool that would summarize across environments and access levels. Clarify which you want?

**Comment by ngehlenborg** [comment]
I am looking for a dashboard. Removed comment about CLI and removed comment about how long it will be used. 

A dashboard will be useful to all a broader audience (NIH, curators, TMCs, etc.), a CLI wouldn't get much usage. 

There is no need to summarize across environments. Dashboard shows that in current environment and it will only really matter in prod.

**Comment by mccalluc** [comment]
@ngehlenborg : I think I could add what you're requesting to dev-search... Or do you want something separate?

**Comment by ngehlenborg** [comment]
That would be a good starting point. Presumably we can move the functionality from there into a more prominent location in the portal if needed.
