### ISSUE TITLE
Pass CCF empty string if no nexus token

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#466]
The team has committed to making public data available without login. Right now, there really is very-little-to-no public data in the various environments, but this is the plan.

@bherr2 : How do you want to the hand-off to CCF to work when there is no nexus token? Pass an empty string? Or something else?

**Comment by bherr2** [comment]
Empty string will work. So, when empty string occurs, do not add the Authorization/Bearer to the header when querying the search-api and that will work for public data, right?

**Comment by mccalluc** [comment]
It should - there just really isn't any data there right now. :( I'll take the question tag off, and leave this issue around to implement on our end. Thanks!
