### ISSUE TITLE
With input from collaborators, propose top-of-page summary for details page

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#47]
With input from @mruffalo , @shirey , and anyone else, make a proposal for what the top of the details page should look like. Deliverable is a google doc mock-up which @ngehlenborg has signed off on.

**Comment by mccalluc** [comment]
@ngehlenborg : It sounds like for just the very top of the page, we don't need that many fields, so I don't think more feedback from backend folks is required.

Here's a mock up: https://docs.google.com/drawings/d/19eX28YnVaXNu2iPSnWhZZkCBaN8LLr1yoS4CWckAM0Y/edit

**Comment by ngehlenborg** [comment]
Thank you @mccalluc!

I reviewed the mock up and made some changes to alignment of the top header. Also compressed the information in the secondary header.

**Comment by mccalluc** [comment]
Cool. Since I don't think the back-end folks will have much of an opinion on this, will close, and file a new issue to implement.
