### ISSUE TITLE
Login button hard to read during hover

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#474]
<img width="132" alt="Screen Shot 2020-06-20 at 2 21 38 PM" src="https://user-images.githubusercontent.com/730388/85208880-be768900-b301-11ea-86e3-0fd17eaaeeac.png">
The Login button becomes almost invisible during hover... @tsliaw , if there's not already a proposal for this, can you make one?

cc: @john-conroy

**Comment by tsliaw** [comment]
Can you make the hover state for the login button (if we will continue to have login/logout on the portal) like this? The hover state in the design is:
elevation=8
overlay=#000000, 8% transparency
Or at least something similar to that. 

![login_hoverstate](https://user-images.githubusercontent.com/16737715/85629324-808da380-b626-11ea-91d2-b9db35da4a88.gif)

**Comment by john-conroy** [comment]
I'll take care of this, thanks!
