### ISSUE TITLE
Implement Collections

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#485]
Bill says the URL just needs to be added to the gateway... Need to clarify what that url is.

**Comment by mccalluc** [comment]
From Bill:

## GET List Collections

GET /collections with optional argument ?component=<COMP CODE>, where <COMP CODE> is from the table below.  Returns a list of Collections which include the basic Collection information and the uuids of all connected datasets.  If the component argument is omitted all Collections are returned. Sample return json is in the attached collection-list.json.

COMP CODE | Component Name
-- | --
UFL | University of Florida TMC
CALT | California Institute of Technology TMC
VAN | Vanderbilt TMC
STAN | Stanford TMC
UCSD | University of California San Diego TMC
RTIBD | Broad Institute RTI
RTIGE | General Electric RTI
RTINW | Northwestern RTI
RTIST | Stanford RTI
TTDCT | Cal Tech TTD
TTDHV | Harvard TTD
TTDPD | Purdue TT
TTDST | Stanford TTD
TEST | IEC Testing Group

**Comment by john-conroy** [comment]
Fixed in #532
