### ISSUE TITLE
Inconsistent left-right ordering of Donor, Sample, Dataset on welcome page?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#487]
Noticed that the left-right ordering on the Welcome page is different between the header and and the top of the body. Thoughts? Maybe this isn't actually a problem?

**Comment by tsliaw** [comment]
I thought about this, and I wanted to ask if eventually the donor, sample and dataset header links will go under a drop-down menu called "Browse" or something like that, similar to how the "Collections" header is currently.

**Comment by mccalluc** [comment]
I'm not sure. Can you follow-up on this - Make a proposal to Nils and either get buy-in, or chart a different course? Thanks!

**Comment by mccalluc** [comment]
@tsliaw -- My sense is that the status quo is fine, but if it needs to change, you can handle that in the redesign.
