### ISSUE TITLE
If page requires API, redirect to login page ... or show human-readable error.

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#49]
In the long run, all pages will be accessible, and the API will return different results depending on your credentials... but in the near term, it will just error if you try to access a page that hits the API, and that is confusing.

Should we have better messaging for this temporary problem? If so, what?

**Comment by ngehlenborg** [comment]
Would addressing #67 take care of this issue for now?

**Comment by mccalluc** [comment]
#67 will give us a nice hubmap-branded error page when we hit a 500... but the user would still have no idea that the page required login. --> We will need additional handling to give a useful message to unauthenticated users, so keep this issue separate.
