### ISSUE TITLE
Use Error Boundaries

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#505]
We've never been able to get API responses to conform to a schema, and I don't know that we ever will. Given that, and errors like #331, and perhaps more as we get more users, we should make the frontend less brittle to unexpected input. I think [Error Boundaries](https://reactjs.org/docs/error-boundaries.html) would be useful here. I'm imagining we replace the higher level index.js code with an Error Boundary class around the original export.

@john-conroy : Do you have thoughts about this? Either how useful it would be, or it what level it would be best to set boundaries?

**Comment by john-conroy** [comment]
Would it make sense to first wrap the `Routes` component in an error boundary and then add more later as we see fit?

**Comment by mccalluc** [comment]
So we'd at least get the page header and footer? Yeah, that sounds like a good place to start.
