### ISSUE TITLE
Design UI for Globus file browser link

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#506]
I should have the API calls for #444 sorted out soon, but I don't know what it should look like. @tsliaw : My sense is that belongs in the "Files" section, as a link above the table. Beyond that I'm not sure.

**Comment by mccalluc** [comment]
Tiffany's sketch [here](https://github.com/hubmapconsortium/portal-ui/pull/507#issuecomment-649102230) looks good -- Closing!

**Comment by mccalluc** [comment]
Actually, going to reopen. This is enough for now, but there are a few more cases that probably need to be handled.
- There can be a Globus access but no files available through the assets API, and just having a section title with no body below is weird.
- Should we just be mirroring the HTTP error messages, or adding more explanation?
- Should we suggest what they should do if they still want to get the data? Send and email to `help`?

No rush on these refinements: I'd suggest going through the usual process, with Nils in the loop. Thanks!

**Comment by tsliaw** [comment]
Figma link: https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=23%3A435
Current look: 
![globus_link](https://user-images.githubusercontent.com/16737715/85867421-bbeeb600-b77d-11ea-8fdc-433b5eee728a.png)

**Comment by tsliaw** [comment]
Updated UI. Figma link: https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=185%3A1325
Screenshot:
![globusfiles_success](https://user-images.githubusercontent.com/16737715/87585837-7e05f300-c694-11ea-896b-c9056cfdc749.png)
![globusfiles_401error](https://user-images.githubusercontent.com/16737715/87585841-7fcfb680-c694-11ea-993f-a3c0f3196ef1.png)

**Comment by tsliaw** [comment]
Approved version: https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=185%3A1325
![globus_success](https://user-images.githubusercontent.com/16737715/87601332-bd8b0a00-c6a9-11ea-95fa-ded6097e2313.png)
![globus_404](https://user-images.githubusercontent.com/16737715/87601335-bfed6400-c6a9-11ea-8f60-03b3e66d36a2.png)

See additional use cases in Figma
