### ISSUE TITLE
Mockup Collection Overview pages

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#516]
Figma link: https://www.figma.com/file/W2HtnD1g9FAknOt9YFPyVK/Collections?node-id=27%3A21
Current look:
![collection_landing](https://user-images.githubusercontent.com/16737715/85866348-1b4bc680-b77c-11ea-8ef4-d2b8803b9113.png)

**Comment by ngehlenborg** [comment]
I added one minor comment in Figma. Otherwise it is good to go!

**Comment by ngehlenborg** [comment]
Version 1.0 is approved: https://www.figma.com/file/W2HtnD1g9FAknOt9YFPyVK/Collections?version-id=370679605&node-id=2%3A2&viewport=-93%2C659%2C0.7756413817405701

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/1216518/85905199-c4280f00-b7d8-11ea-8945-4431e97d2804.png">
