### ISSUE TITLE
Better description on Vitessce select dataset pulldown, with general-purpose LookupEntities

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#611]
![pulldown](https://user-images.githubusercontent.com/730388/86518787-0b7a5500-be02-11ea-8bfb-0e9f94244c1d.png)

Instead of UUIDs, show HBM IDs. Do this with a general purpose `LookupEntities` component, based on the work in #610 (Not sure right now whether it makes more sense to have two separate components, or just one.)

**Comment by ngehlenborg** [comment]
We need to support two use cases, both of which can be handled with one solution:

Use case 1: drop down allows user to select datasets, in which case the HuBMAP ID should be shown under normal circumstances. In some cases it might also require additional information, such as organ information (e.g. "HBM123.ABCD.456 - Kidney") or the dataset might not be part of the portal (for some showcases) and therefore doesn't have a HuBMAP ID.

Use case 2: dropdown allows user to select a part of a data set, e.g., tiles in a CODEX data set. These don't have HuBMAP IDs.

Proposed solution: support a string as a label that can be defined by the developer who is implementing the use of the selection component in the UI. That string could be a HuBMAP ID or anything else.

**Comment by mccalluc** [comment]
I think #632 fixed this: On https://portal.hubmapconsortium.org/preview/cell-type-annotations the pull-down is the `HBM...` id.
