### ISSUE TITLE
Decide on roadmap for faceted search

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#63]
This might be divided into several sub issues, but I think just agreeing to a roadmap is a prerequisite.
- API design: Can the API team give us a spec in the near term, or should we make assumptions about functionality in the near term and implement them in the API-client, and leave the API itself for later?
- Indexing: For each entity type, precisely what fields will be available? Until we get details on this from the API team, I don't think we should make any assumptions about the precise fields which will be available.
- UI: We shouldn't be doing anything interesting or new in the UI. Nils can point at example he likes, or Chuck could, or we can make mockups from scratch, or ....?

Close this issue when precise sub-issues have been filed, and responsibilities are clear.

**Comment by mccalluc** [comment]
@ngehlenborg : Can you choose from one of the examples [here](https://docs.google.com/drawings/d/1XP4D7yLkkHAKIqfWwo7F2Opy7kAovA58b6hq1ZFzefA/edit), or point to another site that would be good to take as a model?

**Comment by ngehlenborg** [comment]
The option that will meet our initial needs best is this one:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/1216518/70184808-9a7d8e00-16b6-11ea-90d1-cecb1cfdb27b.png">

We need to be able to do the following:
- show counts per facet value (bars in the background don't seem to work well)
- collapse and expand facets
- define which facets are expanded or collapsed by default
- provide alternative controls besides checkboxes: e.g. a range slider for numeric data such as age, etc.
- [possibly: ability to limit the list of facet values to some number X and provide a "Show all" option]
- [possibly: show number of facet values for each facet]

**Comment by ngehlenborg** [comment]
@mccalluc: related to my request for the ability to use different types of controls (range sliders and maybe others as well), we should discuss with the API folks if whatever search API (Elasticsearch, Globus Search) can deliver data types associated with facet values, e.g. categorical, ordinal, quantitative. That way we could  come up with a generic faceted browsing UI that choose appropriate controls automatically. 

If data type info is not available, we can either try to guess it (probably not a good idea) or define it for more specialized faceted browsing interfaces.

**Comment by mccalluc** [comment]
> can deliver data types associated with facet values
Could be misunderstanding, but the choice of fields to facet is on the UI side: I don't think we need anything from the API.

I think the roadmap is clear on the API and UI side. Closing: new issues for finer grained questions.
