### ISSUE TITLE
link to the CODEX metadata page doesn't work

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/portal-ui#635]
![Screen Shot 2020-07-06 at 10 55 01 AM](https://user-images.githubusercontent.com/8284878/86608108-1ce56d80-bf78-11ea-8550-2288f8f68806.png)
The  link following the pink highlighted text in this page in the portal should go to the CODEX metadata page but it doesn't :  https://portal.test.hubmapconsortium.org/docs/submission

**Comment by mccalluc** [comment]
@cebriggs7135 : You've included an exclamation point:
```
![example metadata](https://github.com/.../README.md)
```
This generates an image tag, and tries to read the README.md as an image. I'll fix.

**Comment by cebriggs7135** [comment]
I copied and pasted this format so thanks for the correction. Thanks. I'll fix it and submit a PR.
