### ISSUE TITLE
Add multiplier symbol in seqFISH assay description

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/portal-ui#636]
See the highlighted section (20 20 20) in the screenshot below. These numbers should be separated by "x" or "*" to indicate 20 * 20 * 20 = 8000. The asterisks are in the .md doc here"
https://github.com/hubmapconsortium/portal-ui/blob/master/context/app/markdown/docs/assays.md

..but didn't come through to the portal display.
https://portal.test.hubmapconsortium.org/docs/assays
![Screen Shot 2020-07-06 at 11 08 54 AM](https://user-images.githubusercontent.com/8284878/86609402-e577c080-bf79-11ea-8295-38d0aa3b2c12.png)

**Comment by mccalluc** [comment]
Notice that the 20 in the middle is italicized: The `*` on either side of it are interpretted as metacharacters. Fixes:
- Add spaces,
- or, copy and paste this: ×

**Comment by cebriggs7135** [comment]
Got it! Thanks.

**Comment by cebriggs7135** [comment]
Fixed with a PR
