### ISSUE TITLE
UI mockup for data usage click-through

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#637]
Details about use and mechanism are in #443.

Can we use a standard Material UI modal for this? 

It should support an overall title ("HuBMAP Data Usage"), body of text (see #443 for draft) that might need to be scrollable and support basic formatting (two sections, each with a header) and 2 buttons at the bottom:

1. Agree
2. Cancel (default and preselected so that user has to actively select "Agree")

**Comment by tsliaw** [comment]
Two options. Figma link: https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?node-id=146%3A299

![datausage](https://user-images.githubusercontent.com/16737715/86627792-b4998a80-bf7d-11ea-873c-46b5685750e3.png)

**Comment by ngehlenborg** [comment]
I approved version 1: https://www.figma.com/file/awtd3Klx2hka54jyekr9pV/Detail-Pages?version-id=380225178&node-id=146%3A298&viewport=8126%2C229%2C1.1274313926696777

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/1216518/86648680-12929600-bfaf-11ea-95c9-7a9065904cbb.png">
