### ISSUE TITLE
Clicking the first node in the provenance graph causes provenance graph to disappear

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#657]
Clicking on the purple node (source) results in the provenance graph disappearing and this error on the console:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/1216518/86923544-30214600-c0fc-11ea-9d06-55d1d601c174.png">

Dataset: https://portal.test.hubmapconsortium.org/browse/dataset/3897a3d5ffa6d1cdfbb0b5ffbb232c3e
Browser: Safari Version 13.1.1 (15609.2.9.1.2)

**Comment by mccalluc** [comment]
Definitely was a problem, but unable to reproduce. I've tried a couple different datasets, on FF, Chrome, and Safari.
