### ISSUE TITLE
Simplify prov code when index has mapped fields

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#662]
When https://github.com/hubmapconsortium/search-api/issues/84 is done, use the mapped data in prov.

**Comment by mccalluc** [comment]
@john-conroy : The indexes should be updated with the data you need.

**Comment by john-conroy** [comment]
I think this pertains to the provenance table. We presently won't be updating the provenance table. If we do it will be more of a redesign and new issues will be created.
