### ISSUE TITLE
consistent link colors

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#665]
From #652:

> We probably want to make the color of this link consistent with other links.

```
{codesNames.map(({ code, name }, i) => [i > 0 && ' / ', <a href={`/docs/assays#${code}`}>{name}</a>])}
```

**Comment by ngehlenborg** [comment]
Can this be closed?

**Comment by mccalluc** [comment]
Putting in milestone: Need to remind myself of context, and hopefully close.

**Comment by mccalluc** [comment]
Yep, this link light blue like everything else.
