### ISSUE TITLE
combination of facets and search could be improved

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#675]
## Feedback

__Submitter Name__: @computationdoc

__Message__:

Release Issue - for Nils most likely

Faceted Search coupled with Open Main search has a confusing relationship.

The faceted search shows facets for the “level” one is at: Donors, Samples, Datasets

At the same time the open text search allows the search for facets at other levels.

This is Great that one can simultaneously do both, BUT:

It is confusing conceptually because it does not add the facet per se…I well understand switching contexts on the main menu “blows away” the facet selections.

So, my thinking is this:

There are one of two possibilities here:

1. The open search basically uses the content from the facets for search (its a facet hit at any level) 
a. In this case can one add the facet selection on the top line and retain it until dismissed like it was selected as a facet on that page ? 
1. basically maintain some “state” across these pages OR 
2. Add the facet selection that is the hit on the top line when after one does a successful open text search

2. The open search doesn’t tell us what facet we’ve hit - its just functioning as some general search rather than as a facet hit level at some level 
a. In this case can one add the restriction as feedback at the top level AND
1. Basically maintain some “state” across the pages so they stay there when one switches context OR 
2. Retain the subsetting of the hits until a “clear” event

Here is the use case:

Click on Donors 
Facet Select Male 
Facet Select White 
Click on Datasets

Result: See only Datasets from White Males with those facet selections on the top as restricting the listing then add additional restrictions

Here is another version of same:

Click on Datasets 
Free Text Search Male 
Free Text Search White

Result: See only Datasets from White Males with those facet selections on the top as restricting the listing then add additional restrictions

-----

Another option occurred to me to perhaps solve this, which is to allow the full list of facets on all three page levels (perhaps with a header/cascade opening for the level one is at)…(though in this case again one loses one’s facets when switching levels because its a page load)… 
Cheers, 
JCS

**Comment by mccalluc** [comment]
I'm going to unassign myself until the design is clear. I can say that it would be fairly easy to treat the entity type like any other facet: Right now we have special logic to hide it in the list of facets, but it sounds like for this use case, it would be better to be present? Though, it would need to be a radio button, so only one could be selected at a time.

Or, we can update the urls for the other types, as facets are added or removed in current type.

**Comment by mccalluc** [comment]
Added to UI agenda.

**Comment by mccalluc** [comment]
No action now. This will be resolved by cross entity search. #368
