### ISSUE TITLE
Add link to Alpha survey to Portal for phase duration

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#680]
## Feedback

__Submitter Name__:  Aaron Horning

__Submitter Email__: ahorning@stanford.edu

__Message__:
Requested to add Alpha survey to Portal for the Alpha phase duration to make it easier for TMCs to be aware of and access.

**Comment by mccalluc** [comment]
Reasonable. Will put on UI Agenda. https://docs.google.com/document/d/1J8k9YDyUKUr1MeDnHB52gVfMhqe_yo8O21dipjpxaUU/edit#bookmark=id.2t3c50owx3kt

**Comment by mccalluc** [comment]
Nils said there's been plenty of communication about this. No action. cc @pecan88
