### ISSUE TITLE
Request from TMCs for "Stable links to consortium members' information" on Portal

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#682]
## Feedback

__Submitter Name__: TMCs?  (From Bi-monthly TMC meeting - Nils was there)

__Submitter Email__: nils@hms.harvard.edu (?)

__Message__:
So ... this is worth just running by Nils to see if he thinks it's relevant.

TMC members indicated a desire to have stable links back to information about their components / contributions within the Portal.  I honestly don't recall more of the context, so I'd suggest giving to Nils and letting him decide if it's even worth putting any thinking time toward it ...

**Comment by mccalluc** [comment]
On UI meeting agenda. https://docs.google.com/document/d/1J8k9YDyUKUr1MeDnHB52gVfMhqe_yo8O21dipjpxaUU/edit#bookmark=id.rwd1eroivlsq

**Comment by mccalluc** [comment]
Long term goal is to have formal entities for these.
