### ISSUE TITLE
In page / modal login

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#69]
@ngehlenborg would prefer if, instead of taking you to the globus page, login remained within HuBMAP. Is this possible?

**Comment by mccalluc** [comment]
After working with it, I doubt this is possible... perhaps it could be put in a iframe, but I don't think that would be less confusing, maybe at the end of the session in the iframe, the parent page would again have access to the url and could close the iframe? Sounds like a lot of work for little benefit.

**Comment by ngehlenborg** [comment]
Have you talked to Bill or others who are more familiar with Globus?

**Comment by mccalluc** [comment]
If this is worth the time right at this moment, can you clarify what you want?
- Not using Globus and just using a login process that stays within the portal, shifting the burden of account management to us?
- Using Globus, but somehow skipping their one screen and going directly to institution login?
- Doing Globus login flow within an iframe, so there's the sense that we're still in the portal?

Notes:
- Just following their most basic directions for getting this set up took days. Anything else would take more time.
- Third party login auth is not unusual, and having your own per-site login is getting to be less common.

**Comment by mccalluc** [comment]
@ngehlenborg : Just noticed [this](https://docs.globus.org/api/auth/developer-guide/#skinning) ... Let me know if it's worth following up.
> Globus Auth supports skinning, so that when a user comes in from your app the look of Globus Auth matches that of your application. Setting this up is a manual process, please contact us for more details!

(As you might predict, I'm not enthusiastic about investing effort here, but your call.)

**Comment by ngehlenborg** [comment]
I don't think it is worth the effort, as it won't improve the user experience.

**Comment by mccalluc** [comment]
Closing.
