### ISSUE TITLE
Visualization of gene expression on the UMAP plots in Vitescce 

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#696]
Rahul is noting that the visualization of gene expression on the UMAP plots in Vitescce is supposed to be enabled and, presently, he's not seeing it.  Not entirely sure if Bug, but putting in FYI.

**Source email:**

On Jul 9, 2020, at 3:47 PM, Kant, Peter M <peterkant@pitt.edu> wrote:

Thank you, Rahul.  This has been a grand effort.
 
@Nils – I can log this however wanted to check w/ you first on plans re: the gene expression visualization for UMAP plots.
 
Peter
 
From: Rahul Satija [mailto:rsatija@nygenome.org] 
Sent: Thursday, July 9, 2020 3:27 PM
To: Kant, Peter M <peterkant@pitt.edu>; Gehlenborg, Nils <nils@hms.harvard.edu>; Ziv Bar-Joseph <zivbj@andrew.cmu.edu>
Subject: Re: HuBMAP Portal & Data phased release approach, ALPHA feedback by Wednesday July 15 CoB
Importance: High
 
Hi Peter, 
 
First of all congrats on the Alpha which looks great!
 
I can deliver feedback in more formal channels, but as an important start - is the plan to enable the visualization of gene expression on the UMAP plots in Vitescce? This would be quite an important feature for myself and Ziv too I think, in order to interpret his clusters and UMAP.
 
I remember Nils’ saying it was supported but I didn’t see this in the portal.
 
Best,
Rahul

**Comment by ngehlenborg** [comment]
@keller-mark: can you check if there is gene expression data for the datasets that we are currently hosting in our showcases?

**Comment by keller-mark** [comment]
Yes I will check if it is available and implement a processing script if so

**Comment by keller-mark** [comment]
The current showcase datasets have the `salmon_rnaseq_10x` data type. There is gene expression data for these datasets in the files `cluster_marker_genes.h5ad` and `out.h5ad`.

It looks like the expression values in `cluster_marker_genes.h5ad` have been normalized, and many genes have been filtered out. For example, for dataset `2dca1bf5832a4102ba780e9e54f6c350`, `cluster_marker_genes.h5ad` is `6010 cells × 9006 genes` while `out.h5ad` is `6287 cells × 38032 genes`.

Some questions:
- Which of the two files should be used for gene expression visualization?
- The gene names/IDs in these files are in the `ENSG` format. Should I keep these gene names or do they need to be converted to a different format?
- The gene names have suffixes - what does these represent? Should I keep them?
- With thousands of genes, do we need to update the gene selection component in vitessce to support searching?

![Screen Shot 2020-07-09 at 9 47 52 PM](https://user-images.githubusercontent.com/7525285/87107484-dcaf1500-c22d-11ea-95d0-773b78472767.png)

**Comment by ngehlenborg** [comment]
Good summary, @keller-mark!

1. @mruffalo: How are you planning to do the mapping from Ensembl IDs to gene symbols? Since this is just for the showcase, we don't need have to have a final solution, but if you have done this for other HuBMAP data, we would follow your lead. @keller-mark: the suffixes are just [version numbers](http://useast.ensembl.org/info/genome/stable_ids/index.html), you can ignore them.

1. @mruffalo: Can you explain what, if any, filtering is done to explain the difference in gene counts in these datasets?

1. @mruffalo: Is there any way to identify a subset of genes of interest? @keller-mark: we will definitely need to add support for long gene lists to Vitessce. Could you add an issue in the vitessce repo?

**Comment by mccalluc** [comment]
@ilan-gold - https://github.com/hubmapconsortium/portal-containers/pull/55 hasn't moved since september? Is there something blocking that? Can you assess whether there is still work to do here, and possibly file new, small, issues, and then close this?

**Comment by ilan-gold** [comment]
My sense is that there is no longer a technical blocker to this as we have the "chunking" of https://github.com/vitessce/vitessce/pull/876 and virtualized scroll of https://github.com/vitessce/vitessce/pull/791/files.  @keller-mark I believe there was a reason we didn't want to show the current genes in the heatmap example?  I can't remember.

**Comment by keller-mark** [comment]
Now that we have support for AnnData-as-Zarr, it may make sense to update the implementation in https://github.com/hubmapconsortium/portal-containers/pull/55 (which was using the custom `expression-matrix.zarr` format). Also @ilan-gold may want to take a look at how that pipeline is doing the chunking of the matrix to make sure it is compatible with loading genes on demand

**Comment by keller-mark** [comment]
Also does HuBMAP have has a standard for gene naming? In https://github.com/hubmapconsortium/portal-containers/pull/55 I added a step to convert the ENSEMBL gene IDs to gene names but since it has been a while (and I believe things like search-by-expression-level have started to be implemented) would it be better for one or the other be the "primary" gene identifier?

**Comment by mccalluc** [comment]
> Also does HuBMAP have a standard for gene naming? In [hubmapconsortium/portal-containers#55](https://github.com/hubmapconsortium/portal-containers/pull/55) I added a step to convert the ENSEMBL gene IDs to gene names but since it has been a while (and I believe things like search-by-expression-level have started to be implemented) would it be better for one or the other be the "primary" gene identifier?

My sense is that ENSEMBL is good for internal IDs, but it's not the best for use in the UI.

@ilan-gold - I'm going to put this in the next sprint... If it's definitely not a priority, fine to move it back out, but I'd like to know that it _could_ be done, if we wanted to put the time there.

**Comment by mccalluc** [comment]
Ilan Gold  < 1 minute ago
I think the content of the discussion in the issue meandered but the original goal is complete.

Ilan Gold  < 1 minute ago
I’d say we can close.
