### ISSUE TITLE
Top Site Navigation: 3 tabs?

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#699]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/593/activity

__Message__: 

•	Overall is there a way to collapse the Donors, Samples, Datasets, tabs into a single branching arbor? It would be nice to have an option to start with Donor, have a listing of all possible samples, then then go down the branches of the tree to get to individual datasets.

**Comment by ngehlenborg** [comment]
Eventually, we will have a unified search interface with drill down functionality but for the first release this is not possible. 

@tsliaw: please take note of the functionality requested here for a redesign of the search/browse UI.

**Comment by mccalluc** [comment]
@tsliaw : My sense is that with the number of entities at each level, a tree-base UI just wouldn't work. Closing, but please reopen if you think there's something actionable here.
