### ISSUE TITLE
Additional metadata for tables (Donor, Sample, etc.) - TMC, Race

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#700]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/593/activity

__Message__:
not all useful information/metadata is listed in the tables. For Donors its just age, BMI, gender and race. How would you find spleen data for example from the Donor tab, without previously knowing which TMC was doing spleen. Or type of assay, or type of preparation. Likewise on samples tab, without clicking on a single data set , there is no way to select just males, or African Americans.

Full context:
•	Overall is there a way to collapse the Donors, Samples, Datasets, tabs into a single branching arbor? It would be nice to have an option to start with Donor, have a listing of all possible samples, then then go down the branches of the tree to get to individual datasets. 
o	Related not all useful information/metadata is listed in the tables. For Donors its just age, BMI, gender and race. How would you find spleen data for example from the Donor tab, without previously knowing which TMC was doing spleen. Or type of assay, or type of preparation. Likewise on samples tab, without clicking on a single data set , there is no way to select just males, or African Americans.

**Comment by mccalluc** [comment]
> there is no way to select just males, or African Americans.

There is in the latest release. yay!

> How would you find spleen data for example from the Donor tab, without previously knowing which TMC was doing spleen. Or type of assay, or type of preparation. 

This is something we could gather at index time. I've filed #716.

> Overall is there a way to collapse the Donors, Samples, Datasets, tabs into a single branching arbor? It would be nice to have an option to start with Donor, have a listing of all possible samples, then then go down the branches of the tree to get to individual datasets.

This is essentially what the prov table / vis does. If we hear from more people that they can't find it, maybe reorganize?

Part of this has just been fixed, I've filed a focused issue for another part, and the rest is there already, but may need to be more prominent. I don't think that covers it, so I'll close this.
