### ISSUE TITLE
Table links in Donor, Sample, Dataset take you to the same place

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#701]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/593/activity

__Message__:
*See Ticketbove for referenced image*

On the tables across Donor, Sample and Datasets tabs, each of the links for the same data set take you to the same dataset page, regardless if you pick ID, Group, specimen type, organ, last modified etc…   This seem redundant and overkill. At first I thought that when clicking the “group” hyperlink, it would have taken me a to a description of that group and all their datasets, or likewise clicking the hyperlink in the organ section would have take me to all the “thymus” data for example. If I wanted to get to the actual data set, that’s when I would have clicked on the ID itself

**Comment by pecan88** [comment]
Image

![image](https://user-images.githubusercontent.com/21177919/87169236-a8733d00-c29d-11ea-9326-5086b5c00eb2.png)

**Comment by mccalluc** [comment]
The whole row is the result, not the columns.

@tsliaw : Would a hover effect on the row help to make this clear? Is this something you've considered in the new UI, and will making a little progress there fix the experience for this user? Either close this and reference an existing issue, or keep it open and clarify what our fix is. Thanks!

**Comment by tsliaw** [comment]
In the new UI I'm considering, there should be a hover feature on the row and only the ID is a link to the detail page. I'll keep this issue open so I know that this is a current issue for users.
