### ISSUE TITLE
Interpreting HuBMAP ID structure

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#702]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/593/activity

__Message__:

•	How is the HuBMAP IDs generated—is there meaning behind the separate sections in the number itself? If there is meaning, maybe a callout/popup appear when clicking /hovering over the column heading with a diagram (ala checks)?  Could help understand provenance (see next bullet)  [Image of bottom left of check - routing, check, account number]

[Next bullet for Context:]
 •	Regarding Q#4: “Are the donors and samples correctly linked to one another (provenance) when you review a few records?
o	As an outsider (NIH) I have no idea how to verify if the provenance is correctly linked. When clicking on the provenance section of the dataset the options of “table” or graph” are not intuitive. I don’t know what to do with the provided hubmap ID number in relation to its provenance. Should the HuBMAP ID have specific component parts / roots that indicate its origin? Just because the arrows in the “graph” point down stream to generic terms, (ex: What does “Register Donor” clickable box mean? And when clicked get a “type” an “ID” and a “created” date)—how does that information indicate connected provenance?
o	 
o	The example I picked (https://portal.hubmapconsortium.org/browse/donor/ae36b667325281a00d66eed4c43c585f) seems to have an error when selecting “ HubMap entieities” under “Graph” mode. As it collapses the “provenance” box when clicked.  

![image](https://user-images.githubusercontent.com/21177919/87169154-8f6a8c00-c29d-11ea-87e8-888a171fb1f4.png)

**Comment by pecan88** [comment]
Image: 
![image](https://user-images.githubusercontent.com/21177919/87169154-8f6a8c00-c29d-11ea-87e8-888a171fb1f4.png)

**Comment by shirey** [comment]
FYI: There is no meaning to the HuBMAP ID, it was designed to be unique across all HuBMAP entities and human readable.

**Comment by ngehlenborg** [comment]
The bug in the provenance graph has been described in #657.

Regarding IDs: @shirey's comment hits the nail on the head.

Closing.
