### ISSUE TITLE
How to verify Provenance? + Potential Bug

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#703]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/593/activity

__Message__:
•	Regarding Q#4: “Are the donors and samples correctly linked to one another (provenance) when you review a few records?
o	As an outsider (NIH) I have no idea how to verify if the provenance is correctly linked. When clicking on the provenance section of the dataset the options of “table” or graph” are not intuitive. I don’t know what to do with the provided hubmap ID number in relation to its provenance. Should the HuBMAP ID have specific component parts / roots that indicate its origin? Just because the arrows in the “graph” point down stream to generic terms, (ex: What does “Register Donor” clickable box mean? And when clicked get a “type” an “ID” and a “created” date)—how does that information indicate connected provenance?
o	 

![image](https://user-images.githubusercontent.com/21177919/87169097-782b9e80-c29d-11ea-8f56-22d78aa0d37d.png)

o	The example I picked (https://portal.hubmapconsortium.org/browse/donor/ae36b667325281a00d66eed4c43c585f) seems to have an error when selecting “ HubMap entieities” under “Graph” mode. As it collapses the “provenance” box when clicked.

**Comment by shirey** [comment]
@mccalluc and @ngehlenborg The "Activity"/Action boxes in the provenance graph should, I think, just be a line (or continuation) of a line in the provenance graph as there is no real information in them that is useful for a user other than "this entity was created from this other entity" which is shown with just an arrow.

Also, the top level, first node, of the graph should be a Donor, not the "hubmap entities" node, which is meaningless to a user.  We could remove the top level "hubmap entites" node from the PROV json returned if you'd like.  I think the actions need to stay in the returned json, though.

**Comment by ngehlenborg** [comment]
I think the boxes need to remain but should point to workflow etc. executions that took place. @shirey: do you track those somewhere and could we get an API to access them at some point?

**Comment by shirey** [comment]
@ngehlenborg Most of these don't have any workflow information to track, but no in any case we don't track that in these nodes at this point but I believe it is stored elsewhere based on the conversations you and Joel had.  Presumably there should be protocols.io information to stash at this level, which could be displayed for most of them- direct click to protocols.io in those cases?

**Comment by ngehlenborg** [comment]
We have the analysis provenance in form of pointers to a specific commit hash for a github repo but we don't have information about a specific workflow execution (when it was run, what were the input files, what were the exact output files, etc.). If this is not being tracked, then we can only point to the Github repos.

For the donor and sample extraction/processing steps we could refer to protocols but they would need to show up in the provenance graph. I don't think they do at the moment but @mccalluc or @shirey might know better.

**Comment by mccalluc** [comment]
> I assume that the top-level node is included because it is part of the PROV response. @mccalluc: can you confirm?

Yes, it's in the PROV, so it gets rendered.

> For the donor and sample extraction/processing steps we could refer to protocols but they would need to show up in the provenance graph. I don't think they do at the moment but @mccalluc or @shirey might know better.

I don't believe that information is available in the PROV right now.

I've filed https://github.com/hubmapconsortium/portal-ui/issues/714 for the bug and will unassign myself for now.
