### ISSUE TITLE
UX: Showcases and user context, contextual relevance of institution name in table

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#705]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/593/activity

__Message__:

•	“showcases” dropdown lists Spraggins and Satija. Unless you know who they are and are familiar with HuBMAP you would have no idea what those options are until you open the page.  A better description of what you are likely to see is more informative to choose one or the other
o	Which brings up the point of using institution names and people as Dataset, Samples, Donor descriptors. Its not intuitive to an outside user to know what significance of that naming is. Sure its important to provide attribution to the data, but can that be held off until the individual data webpage?

**Comment by ngehlenborg** [comment]
Showcases are still in progress.

@tsliaw: For search page redesign: we can drop group and creator facets as primary attributes for entities but should still have them as some sort of secondary filters.

**Comment by ngehlenborg** [comment]
Showcases have been renamed into previews in #867. Institutions and submitters still available as facets but have been moved to the end of the list.
