### ISSUE TITLE
Label naming for Donor ID & Group name, Last Modified meaning

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#707]
## Feedback

__Help Desk Issue Tracker URL__:  NIH feedback logged in GitHub (Issue not showing up in "Reference an Image or Pull request")

__Message__:

-	* ID should be called Donor ID. (???) – @mccalluc 
-	* Group name can be abbreviated. @mccalluc 
-	* What is the interpretation of ‘last modified’? Why is this useful? - @cebriggs7135  would you please add to the interface documentation?

**Comment by ngehlenborg** [comment]
@tsliaw: last modified date documentation should be handled via "?" icon.

ID could be renamed into "HuBMAP ID" but not "Donor ID".

Group name question to be addressed by overall portal team. Added to meeting agenda.

**Comment by mccalluc** [comment]
Granular issues filed. Nothing left here. Closing.
