### ISSUE TITLE
Users unable to access protocols.io w/out logging into that system?

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#709]
## Feedback

__Help Desk Issue Tracker URL__: n/a - from NIH individual feedback

__Message__:
This should be addressed by Jeff Spraggins and by @cebriggs7135 .  @schwenk102 & I can assist as needed.

Donor metadata & protocols: 
-	* Clicking on an ID and then the protocols: does NOT take me to donor protocols aka any information about how the surgery or something like that was performed. This needs fixing. 
* Clicking on the donor: HBM737.MBKD.598 protocol takes me to a page that says ‘There is a newer version of protocols available’ this needs to be fixed. Though I like the protocol organization provided by Vanderbilt. The other groups need to be encouraged to have individual protocols like this one: https://www.protocols.io/view/vu-biomolecular-multimodal-imaging-center-biomic-k-bfskjncw 
* There needs to be some marker if the protocols change between two or more donors or it hasn’t. Otherwise the user is left to click on a complicated series of protocols to find out if there is any difference at all or not. 
* HBM528.WJLC.564 donor has no information in the protocols or any other details. This seems to be true for BOTH Caltech and Stanford samples. This is URGENT.

**Comment by ngehlenborg** [comment]
Complex issues affecting multiple HIVE components. Added this to the agenda for the next meeting.

**Comment by mccalluc** [comment]
These items were also in #693 : I've broken then out and determined follow-up over there. Closing this as duplicate.
