### ISSUE TITLE
Without log in to portal Collections are listed on Collections page and when one clicks on a Collection 401 error

### ISSUE THREAD

**Issue by computationdoc** [hubmapconsortium/portal-ui#712]
I think Collections are probably not supposed to be public yet but not sure.

I am sure 401 is an error.

**Comment by mccalluc** [comment]
I've put on agenda for next UI meeting. Thanks!

**Comment by mccalluc** [comment]
From Nils: When Collections are in Elasticsearch, we get this behavior for free. No action now.
