### ISSUE TITLE
"?" hover over to explain last modified date.

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#720]
Derived from hubmapconsortium/portal-ui#707

**Comment by ngehlenborg** [comment]
If this can be solved, there might be additional table fields for which we would want to add "?" icons with descriptions.

**Comment by mccalluc** [comment]
- More general issue: #1182

**Comment by mccalluc** [comment]
> * More general issue: [write help text messages for UI portal-ideas#10](https://github.com/hubmapconsortium/portal-ideas/issues/10)

This issue is subsumed by that one: We can't implement without the text of the messages, and @ngehlenborg volunteered to provide that text.

Closing.
