### ISSUE TITLE
Still referencing mixif

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#722]
Find ref to https://github.com/hubmapconsortium/ingest-validation-tools/tree/master/docs/mixif and correct

**Comment by cebriggs7135** [comment]
Changed Github link in the .md doc from ....mixif to .....mxif.

**Comment by mccalluc** [comment]
Please do not close issues manually: Instead, add a note like "Fixes #722". Sometimes there are problems with PRs, and we don't want to think work is done when it isn't.
