### ISSUE TITLE
Provenance: Collapse nodes with lots of multiples (Hard?)

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#73]
Talking with Alex, this is possible with the 4DN tool... not sure about in our wrapper.

**Comment by mccalluc** [comment]
@tliaw512 : The provenance vis is an important part of the details pages. I really have no idea how hard this will be to fix, but this would be a focused task that would at least introduce you to that part of the code base.

**Comment by john-conroy** [comment]
I think this issue can be reinterpreted to allowing any node to be collapsed.
