### ISSUE TITLE
Link from /docs/assay to relevant google docs

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#752]

**Comment by cebriggs7135** [comment]
@mccalluc Are you saying there's a broken link from an assay doc to a google doc? Which assay.md file?

**Comment by mccalluc** [comment]
@cebriggs7135 : Sorry, at this point I'm not really sure what was meant here. I think the question was whether there are any other docs that the [list of assays](https://github.com/hubmapconsortium/portal-ui/blob/0e79397bc6e11bee3e82786cc395bd6327bc247b/context/app/markdown/docs/assays.md) should point to... and if not, great; Let's close this issue.

**Comment by mccalluc** [comment]
If no objection, I'll close.
