### ISSUE TITLE
Re-registration Issue + lack of data

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#765]
## Feedback

__Help Desk Issue Tracker URL__: n/a (via Google forms)

__Message__:

Questions:
1. Are you able to log in using your consortium identity?
2. Are you able to easily find search, visualization, and download capabilities?
3. Are the donors and samples present that your HuBMAP component is including in the first release? Any missing?
4. Are the donors and samples correctly linked to one another (provenance) when you review a few records?
5. Is the donor, sample, and assay-specific documentation complete and correct?  Do your assay experts approve for public release?
6. What bugs and technical issues do you encounter?
7. Are all protocols associated with donors, samples, and assays linked from the portal and loaded into protocols.io with public access?

Answers:
1) No I can't log in. it makes me re-register.

2) I don't see any data when I click Donors, samples or datasets. I do however see the showcased things for satija and Spraggins. 

3) When I looked at "Collections" I didn't see anything from Stanford. Not sure if thats because it would be considered something other than a collection or something else.

4 and 5) I can't answer because I don't see anything when I click those links.  

6) The login makes me reregister when I know I already have a HUBMAP ID. This may cause me to not be able to see the rest of the data possibly.

7) I can't see the protocols.io links because I can't see the data.

**Comment by mccalluc** [comment]
- I started a thread with Peter and Bill for numbers 1 and 2.
- I'll put 3 on [UI meeting agenda](https://docs.google.com/document/d/1J8k9YDyUKUr1MeDnHB52gVfMhqe_yo8O21dipjpxaUU/edit#bookmark=id.2bk6bo5lh28b)
