### ISSUE TITLE
Use of "Creator" to identify provider ...

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#775]
## Feedback

__Help Desk Issue Tracker URL__: n/a (email submitted directly)

__Message__:

[_Likely within context of the Assays documentation page._]

"Creator" is used a lot throughout the site, which is strange to me given there is a "creators" section that is most complete and many of the datasets were created by a multitude of people (I'm a creator on some and feel weird having my name be the only one since it was a team effort... may just be me). I would consider exchanging the "creator" title with "Point of contact" or "contact" or "reference" or "uploader" to be more clear. I think that may be more clear and help differentiate that between "creator" and "creators".

**Comment by mccalluc** [comment]
@pecan88 : If this is on the documentation page, I'm going to (wishfully?) say it's a documentation issue, and pass it back to you to consider. I'll also put it on the UI meeting agenda.

**Comment by mccalluc** [comment]
Also [on agenda](https://docs.google.com/document/d/1J8k9YDyUKUr1MeDnHB52gVfMhqe_yo8O21dipjpxaUU/edit#bookmark=id.w5gva7ss5tds) for UI meeting.

**Comment by mccalluc** [comment]
This will be handled on in the UI code.

**Comment by john-conroy** [comment]
I believe this has been fixed in #910.
