### ISSUE TITLE
Replace Portal Policy text on front page

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#788]
## Feedback

__Help Desk Issue Tracker URL__: n/a (from conversations w/ Policy group)

__Message__:
Would you please replace the DUA Guidlines body text with the following on the front page of the HuBMAP portal?

"The majority of Data available on the HuBMAP Portal is Open Access Data to be used for Research of Human Biology.  Certain Data types with potential for re-identification are available in restricted access either directly through this Portal by login-dependent permissions or through dbGAP. All Data users are expected to respect the privacy and confidentiality of the donors who provided samples. Data are not to be used to re-identify donors or their family members without further approval from HuBMAP.”

**Comment by mccalluc** [comment]
Will make a PR.
