### ISSUE TITLE
Warning re: data not published or is protected for public user

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#789]
## Feedback

__Help Desk Issue Tracker URL__: n/a (coming from Policy group discussions)

__Message__:

Would you please display for public users the following text next to the "Download via Globus" button on pages where you can get the data via Globus?  @computationdoc - I believe this doesn't have to be context specific to Public user vs. logged in, however if you can clarify here that would be great.

“This button may link to data that you do not have access to because: 1) the Consortium is still curating the data or 2) the data is protected data that requires you to be a member in the Consortium “Protected Data Group”. Such protected data will be available via dbGaP in the future.”

If using the Globus Info type object, we can list the following:
Info text: “How to use Globus (Coming soon!)”
Info link: Empty or https://docs.globus.org/how-to/ - a HuBMAP specific page has not yet been authored

Reference document (not open to public):
https://docs.google.com/document/d/1JGAPDaocjcnh5HopDVYTRsrUGLSNeEJJ5g36ZqW5loU/edit#bookmark=id.soa020pwhh3g

**Comment by mccalluc** [comment]
@tsliaw : Can you integrate this into your current work on the Globus link?
@pecan88 : I don't think I know what "Globus Info type" is: Can you clarify that?

**Comment by tsliaw** [comment]
Approved redesign of Globus file section for public users: 
![globus_publicuser](https://user-images.githubusercontent.com/16737715/87601476-0b077700-c6aa-11ea-89df-b95b7dcbfb7d.png)

Did not implement Globus Info type since I was not sure what that meant. Will close issue for now.

**Comment by pecan88** [comment]
Updated to try to be clearer: - ideally, we link out to instructions on what to do as an end user.  Right now there is not FAQ authored, and we may want to link to Globus' current user documentation (see below.)  We will need a HuBMAP-specific FAQ in the near future. @schwenk102, @debnigra 

For example, something like: 
“How to use Globus (Coming soon!)” - FAQ URL TBD 
Empty or https://docs.globus.org/how-to/; Goal is to have a “how to use Globus” FAQ - how to sign up, how to get consortium access, how use Globus connect personal version ultimately, but likely not for v1
