### ISSUE TITLE
Caltech feedback - Overall

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#794]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/614/activity

__Message__:

Overall feedback from Caltech.  I will parse these into separate issues, however I wanted to make sure you have an overall copy for context.
[HuBMAP_Alpha_release_Issues.docx](https://github.com/hubmapconsortium/portal-ui/files/4927916/HuBMAP_Alpha_release_Issues.docx)

**Comment by mccalluc** [comment]
By doing a couple searches from phrases in the doc, I have confirmed that followup issues have been filed. Closing this since it's redundant, and no action is required.
