### ISSUE TITLE
Top level Nav: uncertainty on purpose of Donor / Sample / Dataset

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#795]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/614/activity

__Message__:

2.	Are you able to easily find search, visualization, and download capabilities?
- Not sure what the rationale is for donor/samples/datasets/collections.  I’m thinking users will just want the datasets, and it seems they are searchable by donor and sample characteristics on that page.  I’m not sure what the collections adds as well.

**Comment by pecan88** [comment]
Other comment: - I can easily search for certain datasets based on different parameters. Visualization of each dataset is clear and simple. The interface is quick and responsive.

**Comment by mccalluc** [comment]
- Confusion about collections is common: Added to https://docs.google.com/document/d/1J8k9YDyUKUr1MeDnHB52gVfMhqe_yo8O21dipjpxaUU/edit#bookmark=id.2bk6bo5lh28b

- For other folks, donors and samples matter. No action on that.

Closing.
