### ISSUE TITLE
Inability to Download data

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#796]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/614/activity

__Message__:

2.	Are you able to easily find search, visualization, and download capabilities?
- I can't download any datasets besides seqFISH, but I get redirected to Globus and credentials are required (probably fixed in beta testing).
- Can not download ATAC data, get redirected to Globus with no authorization.

**Comment by mccalluc** [comment]
I'm interpreting the root problem here is that the user missed is not getting Globus privs during on-boarding ... Or they have privs, but just haven't tried to use them? Will message Bill on Slack, and he can reopen if needed.
