### ISSUE TITLE
Missing / Non-Visible protocols for Caltech datasets

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#799]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/614/activity

__Message__:

5.	Are all protocols associated with donors, samples, and assays linked from the portal and loaded into protocols.io with public access?
- pdf of protocol is not viewable for.  Only place for protocols now is for samples (not donors or assays).  
- the seqFISH protocols are not linked for all organ pieces: tissue preservation HBM598.KHTX.275: dx.doi.org/10.17504/protocols.io.7e7hjhn

**Comment by mccalluc** [comment]
> pdf of protocol is not viewable for. 

@pecan88 : It looks like there is missing text here? 

> Only place for protocols now is for samples (not donors or assays).

Not true: https://portal.hubmapconsortium.org/browse/donor/3439871e0617807d2711465a249af9a5#protocols

> the seqFISH protocols are not linked for all organ pieces: tissue preservation HBM598.KHTX.275: dx.doi.org/10.17504/protocols.io.7e7hjhn

```
portal_uploaded_protocol_files: 
  protocol_doi: ""
  protocol_file: "/hive/hubmap/lz/tissue-reg-data/def5fd76-ed43-11e8-b56a-0e8017bdda58/1b9a6cd7e5875e6e812d564a3c27a03c/hubmap_protocol_tissue_collection.pdf"
```

I'll message Bill: I believe this is one of the cases where we're going to turn around and ask the TMCs for protocols DOIs.
