### ISSUE TITLE
What is "sample data portal" checkbox in new user registration?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#80]
Chris is going through the new user registration form (which I don't think existed when I began?) and there is a checkbox to request access for "Sample data portal". Is this being used? ... If so, what does it mean in terms of Globus request/response? (I'm asking so that if someone has a login problem and comes to me, I'll have a better idea about what could be wrong.)

@shirey ?

**Comment by shirey** [comment]
This will be removed in the next release of the registration page.  Now that we have real data we don't need the sample data.

This issue removes it (among other things) https://github.com/hubmapconsortium/member-ui/issues/40
