### ISSUE TITLE
"Unexpected Code"

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#811]
## Feedback

__Help Desk Issue Tracker URL__: n/a (Zoom w/ NP)

__Message__:

"NP and I don’t know what “unexpected code” means and whether the organ information is wrong, being presented incorrectly, or whether something else is going on."

**Comment by mccalluc** [comment]
`origin_sample` is not set correctly on some records. https://github.com/hubmapconsortium/search-api/issues/89

(More generally - There's a balance between hiding problems entirely, and showing too much debugging info in the UI, and we're happy with the balance that's been struck.)
