### ISSUE TITLE
"Unexpected Code", Display of data modality, linkage of ATAC & RNA sets for dual modality (SNARE seq2)

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#812]
## Feedback

__Help Desk Issue Tracker URL__:  Alpha survey response Number 4

__Message__:

No data descriptions. SNARE-Seq2 data shows large number of datasets listed as "unexpected code". Modality for SNARE-seq2 data is not listed (e.g. RNA or Accessible Chromatin). SNARE-seq2 dual-modalities are not linked (no indication of matching RNA and Chromatin Accessibility Data sets from the same collection)

**Comment by mccalluc** [comment]
> No data descriptions.

As far as I know, there were no precise requirements for the description field, so that's the data we have. cc @cebriggs7135 .

> SNARE-Seq2 data shows large number of datasets listed as "unexpected code".

"Unexpected Code" should be fixed on next reindex.

> Modality for SNARE-seq2 data is not listed (e.g. RNA or Accessible Chromatin).
> SNARE-seq2 dual-modalities are not linked (no indication of matching RNA and Chromatin Accessibility Data sets from the same collection)

Will bring this up on Slack for Bill.

Closing.
