### ISSUE TITLE
Globus Institutional Account and making it Primary for HuBMAP access

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#813]
## Feedback

__Help Desk Issue Tracker URL__: Alpha survey response No 5

__Message__:

This feedback has come from a number of folks.  I'll try to append other ones I note to this message going forward.

"I had previously used my ORCID globus identity to login to the HuBMAP Collaboration portal but access to the data portal was given to my institutional identity. I had to make my institutional identity my primary globus identity which required closely reading documentation. The process worked in the end but was a bit awkward."

**Comment by mccalluc** [comment]
Slacked to bill. Closing.
