### ISSUE TITLE
Visualizations of non-showcase data, search UX (matching), search inconsistency ("Exactive")

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#814]
## Feedback

__Help Desk Issue Tracker URL__: Alpha survey response No 5

__Message__:

I could [not] find any visualizations of datasets outside of the "Showcases". Not sure if that was a failure in navigation on my part though. Searching metadata sometimes worked (e.g. VAN0029 or "tribrid"), returning reasonable results but it wasn't clear that the search was matching against. Other metadata searches (e.g. "Exactive") did not return results even though the term exists in metadata. Downloading data was easy enough though.

**Comment by mccalluc** [comment]
Abscence of visualization is just waiting for pipelines to run. Asked in curation channel if there should be results for "Exactive". Closing.
