### ISSUE TITLE
Globus needed for Access

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#815]
## Feedback

__Help Desk Issue Tracker URL__: Alpha survey response No 6

__Message__:
[Sharing this more for potential UX or training referral than any kind of "bug".]

I didn't realize that you needed to have a additional permissions to log into the portal (I guess I hadn't checked that box when I signed up) and you need to login again when accessing the data in globus, some of which I couldn't access (though it was only a few datasets I encountered).

**Comment by mccalluc** [comment]
Passed along to Bill.
