### ISSUE TITLE
UX: Visualization, direct access to files, file naming conventions, CCF images are black

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#816]
## Feedback

__Help Desk Issue Tracker URL__: Alpha survey response No 6

__Message__:

I didn't know how to visualize the data. I haven't been part of portal discussions, but I figured I would be able to click on a dataset and see the image(s) for it. Rather,  I need to go through each file system for each dataset to see any imaging data. There's no legend or key on the final images and files aren't always intuitively named, so it's difficult to understand what I'm looking at. Depending on the data type, I may not be able to see anything. The CCF data also just shows me black images with no data.

**Comment by mccalluc** [comment]
Again, pipelines haven't been run that would provide visualization. Closing.
