### ISSUE TITLE
SeqFISH display of protocol link; link to documentation

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#817]
## Feedback

__Help Desk Issue Tracker URL__: Alpha survey response No 7

__Message__:

Missing:
1. Links to protocols.io for the tissue preparation of seqFISH tissue sample 2. Link to the appropriate data in the seqFISH documentation

Email sent to responder and copied @tsliaw to ensure any response makes it to team HMS ASAP.

**Comment by mccalluc** [comment]
Will ask Bill about missing Protocols.

@pecan88 : Any idea what "Link to the appropriate data in the seqFISH documentation" means? ... maybe they want a link from the static docs to the search page?

**Comment by mccalluc** [comment]
From: "Pierson, Nico" <nicogpt@caltech.edu>

> Hey Peter, 
>
> All of the missing protocols.io have been filled and verified in the google doc and in the HuBMAP ingest.

**Comment by ngehlenborg** [comment]
I am unable to check which samples were missing the protocols or if it has been addressed. @shirey Do you know if any protocols were added in your ingest system?

**Comment by shirey** [comment]
@ngehlenborg  I just ran a queries in both Neo4j and Elasticsearch we have a single protocol.io DOI URL for EVERY Sample (and Donor).  FYI in ES this is stored in the protocol_url field.

**Comment by ngehlenborg** [comment]
Thanks!

**Comment by shirey** [comment]
@ngehlenborg Yes, they were added during ingest, though recently we cleaned things up with the TMCs manually because TMCs were originally allowed to upload a protocol file or DOI URL.  Peter went back and had them add protocols.io entries for all that were files.
