### ISSUE TITLE
Visualization ideally include gene expression levels and UMAP plots

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#818]
## Feedback

__Help Desk Issue Tracker URL__: Alpha Survey response No 8

__Message__:

My two biggest challenges were that many datasets were not processed. For the datasets that were processed, I felt it would be helpful to visualize gene expression levels alongside the UMAP plots. I've contributed this feedback and other small points to Peter/Nils, and am also monitoring the GitHub

**Comment by mccalluc** [comment]
Dataset processing is known / Added gene expression vis to UI agenda.
