### ISSUE TITLE
KNOWN ISSUE: Image pyramids

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#819]
## Feedback

__Help Desk Issue Tracker URL__:

__Message__:

Image pyramids required to display VU data in tissue viewer. IEC needs to run https://github.com/hubmapconsortium/portal-containers/blob/master/containers/ome-tiff-tiler/README.md

**Comment by mccalluc** [comment]
Right, this is already being tracked. Known issues don't need to be filed here.
