### ISSUE TITLE
Links to protocols not shown

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#820]
## Feedback

__Help Desk Issue Tracker URL__: Alpha survey response No 11

__Message__:

Links to the protocol for each stage of processing (screenshot attached)

[https://drive.google.com/file/d/1zXA0ViXy7YCOyTUr1L9uQgU_maHYmyyF/view](https://drive.google.com/file/d/1zXA0ViXy7YCOyTUr1L9uQgU_maHYmyyF/view)

**Comment by mccalluc** [comment]
I don't have access. Getting more provenance info is a known issue.
