### ISSUE TITLE
sci-RNA-seq3 dataset missing, Creator case, blank datatypes

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#821]
## Feedback

__Help Desk Issue Tracker URL__:  Alpha survey response No 12

__Message__:

I'm posting comments for Shin Lin (sci-RNA-seq3 dataset)

-Expected sci-RNA-seq data is present
-provenance is correct
-Amir and Daniel (sample “Creators) need to be capitalized on Samples page
-On datasets page, HBM686.ZPMW.826 and HBM286.BGXG.335 are blank for datatypes

**Comment by mccalluc** [comment]
- Capitalization on UI agenda.
- Slacked Bill about missing datatypes.
