### ISSUE TITLE
Vanderbilt feedback: overall UX, server errors, why show items w/ no data? (samples, derived), missing DOIs, what is "unexpected code", some datasets not connected, attribution

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#823]
## Feedback

__Help Desk Issue Tracker URL__: Alpha survey response No 16

__Message__:

@ngehlenborg  - you should probably look this one over yourself.  The respondent offered to have a call w/ you to go over.

-I'm getting multiple "Internal Server Errors" after navigating to the first dataset.

-It is strange to click on a donor and see a list of 100 samples, 99 of which have NO data associated with them.  Why are we showing the user a list of samples that have not been analyzed yet?  This makes navigating the samples unusable when you have hundreds of sections but only a few have been analyzed.

-When you have drilled down to look at a Dataset, in the provenance box, under the Dataset on the right, there is a button that says "View Derived Datasets"... when you click that nothing is there.  This makes it seem like something is broken.

-Where do you find the DOIs for the datasets that are downloaded by the user?

-It might not be possible, but when you click on a Dataset it should show you "Co-registered" or "Linked" Datasets.  For example, indicating other datasets that are available from the same tissue.

-Overall, I find navigating the Provenance very confusing and unusable for the VU samples.

-In the UCSD metadata I see "unexpected code" in many of the tables.

- The multimodal imaging collections for the VU data are missing modalities in most cases or are not connected correctly.

 - I am looking at an AF microscopy Dataset and I do not see a link to a protocol anywhere. (HBM455.XGQZ.542 Autofluorescence Microscopy)... same with the MALDI IMS data (HBM286.FJBP.622), no protocols listed.  Seems this is an issue for all Assays.

- In the Table of Samples and Datasets it would be helpful to include Age, Sex, Race and BMI.

- The way the navigation is setup it is REALLY hard to figure out what is there and what might be missing.  Based on the number of assays when you filter on Datasets it seems like everything is there.

When you land on a dataset, under the attribution box, it might be good to list the PIs in each case.

**Comment by mccalluc** [comment]
@ngehlenborg : Not clear that this was looked at; Probably should have scanned it first rather than just assigning to you.

> -I'm getting multiple "Internal Server Errors" after navigating to the first dataset.

We're really not using the logs... either with live monitors, or retrospectively. Asked Bill on slack if there is log monitoring. -- Response, no, there is none.

> -It is strange to click on a donor and see a list of 100 samples, 99 of which have NO data associated with them. Why are we showing the user a list of samples that have not been analyzed yet? This makes navigating the samples unusable when you have hundreds of sections but only a few have been analyzed.

"Why are we showing the user a list of samples that have not been analyzed yet?": Let me ask if we want to change the default... Put on UI meeting agenda.

> -When you have drilled down to look at a Dataset, in the provenance box, under the Dataset on the right, there is a button that says "View Derived Datasets"... when you click that nothing is there. This makes it seem like something is broken.

I think this has been fixed.

> -Where do you find the DOIs for the datasets that are downloaded by the user?

This doesn't make sense to me....?

> -It might not be possible, but when you click on a Dataset it should show you "Co-registered" or "Linked" Datasets. For example, indicating other datasets that are available from the same tissue.

Yeah, this is a big topic, and was discussed in the call this morning. I don't think I'm able to summarize the direction forward, though.

> -Overall, I find navigating the Provenance very confusing and unusable for the VU samples.

Sorry. 

> -In the UCSD metadata I see "unexpected code" in many of the tables.

"unexpected code": Indexing problem: Should be resolved.

>     * The multimodal imaging collections for the VU data are missing modalities in most cases or are not connected correctly.
>     * I am looking at an AF microscopy Dataset and I do not see a link to a protocol anywhere. (HBM455.XGQZ.542 Autofluorescence Microscopy)... same with the MALDI IMS data (HBM286.FJBP.622), no protocols listed.  Seems this is an issue for all Assays.

Data issues?

>     * In the Table of Samples and Datasets it would be helpful to include Age, Sex, Race and BMI.

Technically, easy, but we just don't have the horizontal space. Will reconsider if we hear from more labs. Or give users more control? On UI agenda.

>     * The way the navigation is setup it is REALLY hard to figure out what is there and what might be missing.  Based on the number of assays when you filter on Datasets it seems like everything is there.

Sorry.

> When you land on a dataset, under the attribution box, it might be good to list the PIs in each case.

Could do... Add to ui agenda.

**Comment by mccalluc** [comment]
I'm going to trust that after talking about the points that were put on the agenda, we set a direction, and new granular issues were filed, if work was needed. Closing, but feel free to reopen if you think any point should be re-evaluated.
