### ISSUE TITLE
Globus / Portal login issue

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#824]
## Feature request or Bug report

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/614/activity

__Message__:

Likely HuBMAP to Globus account issue.  Recommend assign to MDS.

4.	What bugs and technical issues do you encounter?
- When I go from to a dataset to download data from Globus, it says I need to login again with another account.  When I login, the link to the dataset I’m trying to download is no longer there.    
- I didn't find any technical issues. I repeated the error Shin tried above, and I also had to login again. I'm not sure if "derived datasets" is supposed to be blank.

**Comment by shirey** [comment]
UPDATE: It looks like Globus just today changed the login message so it is more user friendly now.

**Comment by mccalluc** [comment]
Filed #832 to cover what remains.
