### ISSUE TITLE
Accessing UCSD & UFL DOI URLs directs you to another TMCs protocol

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#826]
## Feedback

__Help Desk Issue Tracker URL__: https://on.spiceworks.com/tickets/open/616/activity

__Message__:

For Florida & UCSD TMCs, distinct DOI URLs are created, however when one follows that URL, a separate TMC's protocol is served up [Preparation of Adult Human Kidney Tissue for Single Nuclei ... ](https://www.protocols.io/view/preparation-of-adult-human-kidney-tissue-for-singl-568g9hw).  The Stanford DOI URLs do not appear to be affected by this.  Example affected DOI URLs:

dx.doi.org/10.17504/protocols.io.568g9hw (UCSD)
dx.doi.org/10.17504/protocols.io.bbgmiju6 (Florida)

Reference document (non-public access): [https://docs.google.com/spreadsheets/d/1i3KQuLBHpZ0HpjA2cx4u6Sn_W-Rukq25LgvCi5YUvYY/edit#gid=1276450904](https://docs.google.com/spreadsheets/d/1i3KQuLBHpZ0HpjA2cx4u6Sn_W-Rukq25LgvCi5YUvYY/edit#gid=1276450904 )

**Comment by mccalluc** [comment]
As this is a data issue, I'll alert Bill and close.
