### ISSUE TITLE
Missing Caltech datasets for release?

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#828]
## Feedback

__Help Desk Issue Tracker URL__:

__Message__:
Potentially missing Caltech datasets for release.

Good Morning,

I am looking through this document for missing protocols and it is missing the 2 data sets we are included in the release, I thought I saw them yesterday?

HBM697.BXTK.979
HBM666.FFFW.363

Thanks,

**Comment by pecan88** [comment]
Ticket: https://on.spiceworks.com/tickets/open/618/activity

**Comment by mccalluc** [comment]
Data issue. Slacked Bill. Closing.
