### ISSUE TITLE
sort entries in file table lexicographically

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#836]
The list of files in the file table should be sorted lexicographically (ignoring capitalization) within each level of the hierarchy:

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/1216518/87939222-bf681b00-ca65-11ea-8eb6-1f1519911a9c.png">

**Comment by mccalluc** [comment]
I'll address this in search-api

**Comment by mccalluc** [comment]
This will be fixed in the index with https://github.com/hubmapconsortium/search-api/pull/105. I'll close this, though we won't see anything until it's been reindexed.
