### ISSUE TITLE
Implement "best z" support for CODEX images

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#842]
Once https://github.com/hubmapconsortium/vitessce/issues/657 has been addressed, we should support it in the portal UI for CODEX data via the `focal_plane_selector/best_z` variable found in `data.json` (as of v.1.6.5 of the CODEX pipeline): 

<img width="704" alt="image" src="https://user-images.githubusercontent.com/1216518/87953113-a2891300-ca78-11ea-92c9-28a34018d65f.png">

**Comment by mccalluc** [comment]
@ilan-gold : I don't think we reference `focal_plane_selector` in the code base. Is this still something that would be useful to add to the vitessce conf generation?

**Comment by ilan-gold** [comment]
Yes we could and should.

**Comment by ilan-gold** [comment]
Started a branch: https://github.com/hubmapconsortium/portal-ui/tree/ilan-gold/initial_z_stack

Ran into an issue with SSL and requesting to the assets API from the portal backend for this file as well as (given the current architecture) the need to resolve https://github.com/vitessce/vitessce-python/issues/54 first

**Comment by ngehlenborg** [comment]
CODEX pipeline is no longer providing an image stack.
