### ISSUE TITLE
Reorganize portal header

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#846]
Portal header might become too cluttered in the future when new features are added. 

Need to add:

- Link to hubmapconsortium.org. (was #892)

To consider:

- Categorizing donor, sample, dataset search in one tab of "Browse Data" or 'Data" 
- Categorizing collections and CCF under "Resources"

Current look:
![Screen Shot 2020-07-20 at 11 32 53 AM](https://user-images.githubusercontent.com/16737715/87973034-c3536780-ca7c-11ea-976d-44c0de50af98.png)

**Comment by ngehlenborg** [comment]
Is there a link to a sketch?

**Comment by mccalluc** [comment]
@tsliaw - I'm going to close this: Real estate in the header is still a concern, since neither of the ideas above came up in the discussion yesterday, my sense is that we want to keep those all at the top level. Reopen if you think there is something actionable here.
