### ISSUE TITLE
Add description and tooltip to collections

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#847]
Users are getting confused about the purpose of collections. 
Figma: https://www.figma.com/file/W2HtnD1g9FAknOt9YFPyVK/Collections?node-id=244%3A22

**Comment by tsliaw** [comment]
Design: 
![collections](https://user-images.githubusercontent.com/16737715/88086023-8a2dfc80-cb3b-11ea-9241-933d47f75c10.png)

**Comment by tsliaw** [comment]
@shirey Can you provide the text for the description on the collection overview page? The draft for the text is in the screenshot above.

**Comment by ngehlenborg** [comment]
I came up with this and got it approved by @shirey:

--- 

Collections of HuBMAP datasets represent data from related experiments—such as assays performed on the same organ—or data that has been grouped for other reasons. In the future, it will be possible to reference collections through Document Object Identifiers (DOIs).
```

**Comment by tsliaw** [comment]
Updated mockup: https://www.figma.com/file/W2HtnD1g9FAknOt9YFPyVK/Collections?node-id=244%3A22
![Screen Shot 2020-07-30 at 2 06 03 PM](https://user-images.githubusercontent.com/16737715/88974808-0d52ff00-d26e-11ea-8636-ca8b74bdf1d4.png)
