### ISSUE TITLE
Refactor Vitessce Configuration Creation

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#882]
https://github.com/hubmapconsortium/portal-ui/blob/master/context/app/api/vitessce.py Needs to be refactored.  It's hard to do that without knowing what the data is going to look like, but I think there are some thing we can do:

- [ ] Subclass the different configurations/assays
- [ ] Sub-subclass the imaging modalities.
- [ ] Figure out a more unified way of searching for files that need to be fetched.

**Comment by mccalluc** [comment]
@ilan-gold : I think you've covered this in the recent PR: It looks like you were thinking about about having separate subclass hierarchies, but I think you've got something that works, and the collections of regexes seem to work well. Reopen if you think there is more work to do here.
