### ISSUE TITLE
Remove CCF API links on /docs/api

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/portal-ui#884]
<https://portal.hubmapconsortium.org/docs/apis> has links to the CCF API that we ended up discarding. You can delete the whole section, which looks something like below:
```
Common Coordinate Framework (CCF) Registration User Interface (RUI) and Exploration User Interface (EUI) API

A specification and set of web service calls to return information about CCF-mapped data

    GitHub
    Smart API
```

**Comment by mccalluc** [comment]
Fixed in #873; Just wasn't deployed when you looked.
