### ISSUE TITLE
add link to hubmapconsortium.org to header or footer of all portal pages

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#892]
The header is getting very crowded and it would have to go into a menu.

The footer isn't set up for this at the moment but we could add something there.

**Comment by mccalluc** [comment]
@tsliaw : Can you make a proposal? My take would be to make the big "HuBMAP" link on the left side a pull-down, with "Data Portal" and "Consortium" under it. In the footer, the copy-right note is already a link to https://hubmapconsortium.org/

**Comment by mccalluc** [comment]
This is subsumed under header redesign: #846. Closing.

**Comment by mccalluc** [comment]
Actually, noticing that you say "Or"... and that's already satisfied, by the copyright link in the footer.
