### ISSUE TITLE
"No channel names found in OMEXML.  Please be sure to use numeric indexing."

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#895]
On https://portal.test.hubmapconsortium.org/browse/dataset/2392b8c6e84b3874cc0530fa058cb96e, this warning occurs multiple times.
"No channel names found in OMEXML.  Please be sure to use numeric indexing."

@ilan-gold : Do you know if this is a data issue? Is a fix required in the pipeline?

(Same page produces #891, but not sure if related.)

**Comment by ilan-gold** [comment]
@mccalluc These are all test images that Ivan used.  I wouldn't read into it too much.  The data could be malformatted etc.  I'll look into it to confirm there are no real bugs.

**Comment by ngehlenborg** [comment]
This was test data, closing.
