### ISSUE TITLE
Create description text for preview pages

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#902]

**Comment by ngehlenborg** [comment]
Text:

```
HuBMAP Data Portal Previews demonstrate functionality and resources that will become available in future releases.
```

**Comment by tsliaw** [comment]
![preview](https://user-images.githubusercontent.com/16737715/88573716-00c47180-cff6-11ea-9f58-b0f348e30dd2.png)
[Figma link](https://www.figma.com/file/ejCWSUFHyIGY900cZZ8Jgl/Previews?node-id=48%3A441)

**Comment by tsliaw** [comment]
Approved 
![preview](https://user-images.githubusercontent.com/16737715/88575260-76314180-cff8-11ea-802f-f1af83186c4e.png)
Figma link: https://www.figma.com/file/ejCWSUFHyIGY900cZZ8Jgl/Previews?node-id=48%3A441
