### ISSUE TITLE
Create user login status 

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#903]
Notes:
Design a pull down, and eventually a profile page.
Figma: https://www.figma.com/file/ADoZYtjNbhtYEeKSoVFYTy/Login?node-id=12%3A1986

**Comment by mccalluc** [comment]
Asked on Slack: 
> If we want to display the logged in user’s name in the portal, should that already be available to us as part of the login process? (Not seeing it, but might be there, somewhere.) Or, should we make a separate request to the [Identities API](https://docs.globus.org/api/auth/reference/#identities_api)? Has anyone else done this? Does this sound like an OK idea?

**Comment by tsliaw** [comment]
Finalized design: https://www.figma.com/file/ADoZYtjNbhtYEeKSoVFYTy/Login?node-id=12%3A1986
Logged In:
![Screen Shot 2020-08-11 at 10 32 03 AM](https://user-images.githubusercontent.com/16737715/89929298-e970b100-dbbd-11ea-9644-6a3811dbf701.png)

Drop Down (Log Out):
![Screen Shot 2020-08-11 at 10 32 37 AM](https://user-images.githubusercontent.com/16737715/89929346-fbeaea80-dbbd-11ea-993e-060aa6b4af6d.png)
