### ISSUE TITLE
unable to select text in search results tables

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#929]
(tested only on Safari)

I am unable to select any text in the search results tables, which is problematic when trying to copy IDs etc. 

Text in the table should be selectable.

**Comment by mccalluc** [comment]
Display block which we use to get the whole row clickable seems to disagree with selecting text... maybe if I override that on an inner span? Investigating...

**Comment by mccalluc** [comment]
That didn't work. Also tried [user-select](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) with different values, and a bit of googling. My sense is that `display: block` makes interactions take place with the whole block, and it doesn't let you select substrings within.

Unassigning myself, but leaving open.

**Comment by mccalluc** [comment]
@john-conroy : I couldn't get traction on this, but a different approach might strike you?

**Comment by john-conroy** [comment]
I don't think we should do this. Having selectable text inside of a link is not normal or expected behavior. I think we should reconsider the design and how the entity detail pages are linked.

**Comment by ngehlenborg** [comment]
I agree that selecting text inside the link is not needed or desirable but at the moment I am unable to even select the full link text, which I need in order to get the HuBMAP IDs.

**Comment by john-conroy** [comment]
Right click and copy link or address are working for me. I'll check Safari.

**Comment by ngehlenborg** [comment]
I can't copy the text in Safari and the link has the UUID but no the HuBMAP ID.

**Comment by john-conroy** [comment]
This is going to be tricky. For now you can crtl click to highlight the ID and then hit ⌘ + C.

**Comment by john-conroy** [comment]
So it is possible to copy the ID in Safari, but definitely not UX friendly. Is the goal to be able to be able to select text with left click and drag or for 'copy' to show up in the right click menu in Safari similar to other links?

**Comment by ngehlenborg** [comment]
Yes, that would be ideal.

**Comment by john-conroy** [comment]
Although the outcome is undesirable, both the table and row link are behaving as normal. I think if we want to change how text is selected in the table I'd suggest we remove the row link and link to the detail page only in the uuid or something similar.  I don't know how we'd fix this while retaining the row link and if we did figure something out it would probably be a fragile solution, but I can figure it out.

I briefly mentioned this to @tsliaw and she said that's a common design to use the id as a link in other data portals.

**Comment by mccalluc** [comment]
We decided just now not to take action on this, but with more feedback from users, it could change. We have the current UI because, when the links were just on the text, users found it confusing that the rest of the row seemed inactive. We've done a bit of a survey, and haven't found an example where the row is clickable, and the contents of the row are selectable.

(There's a bit of confusion about whether this is a Material UI idiom or not: John and I believe this is not a detail Material UI has an opinion on... the problem is lower, with HTML.)

No action for now, but if user-feedback suggests we can get rid of row-clickability, may reopen.
