### ISSUE TITLE
Investigate design for links with different functionalities

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#945]
Scenarios:

- Email
- Files
- Portal links
- External links

To Do: 
- Consider UI for visited links

**Comment by mccalluc** [comment]
@tsliaw -- Is this still active, or could it me closed?

**Comment by tsliaw** [comment]
This still needs to be done, I need to communicate to John which icons to use for external links and email links.

**Comment by mccalluc** [comment]
These issues have been filed, so I'm going to close this: Update the granular issues if there are still display details to be resolved.
- #2016
- #2096
