### ISSUE TITLE
entity ids are cropped in search results page

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#960]
Under some circumstances the IDs in the first column are cropped (here selecting data type "[sc_atac_seq_snare]" causes the problem):

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/1216518/89180651-34584c00-d560-11ea-9d22-62585cc39571.png">

The same is true for other columns that contain text that doesn't have any spaces in it (see "Data Types" in this example).

At least the IDs should always be fully visible.

**Comment by mccalluc** [comment]
- Can you give me your browser, url, and zoom level? I'm having trouble reproducing this...
- but after merging #955, the behavior may change here.
- I think Tiffany has a different idea of how this should work down the road: You and her should get on the same page before we implement anything new.
> Eventually the columns entries should always stay on one line and the table should be horizontally scrollable (if applicable), especially the "ID" column since I don't like how the ID currently splits into two lines.

**Comment by ngehlenborg** [comment]
This seems to occur only in Safari (I confirmed that it looked fine in Chrome). Zoom was 100% and pixel resolution 2560x1600.
