### ISSUE TITLE
SPRM Tile does not Load

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#963]
On prod 31d0eca8591c5d8592992df452f629be does not load because it expects to have more than just imaging data but there are no segmentations.

There are two issues here:
1.  Foremost, we should not be telling `vitessce` to render things that are not there, like cell segmentations.
2. `vitessce-grid` is not updating properly when the proper view config is passed in.

**Comment by ngehlenborg** [comment]
If the grid updating issue cannot be addressed easily, we can take the same approach as before: create the same view config but don't load any data into the views for which there is no data.

**Comment by ilan-gold** [comment]
@ngehlenborg I have opened the first PR to start fixing this - should be done by EOD, hopefully.
