### ISSUE TITLE
spacing between footer and page content is missing on help & preview pages

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#966]
Currently:
<img width="1784" alt="image" src="https://user-images.githubusercontent.com/1216518/89202767-704fd900-d581-11ea-8c7e-b552828e2561.png">

It should look like this:
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/1216518/89202859-970e0f80-d581-11ea-88a2-c894b04dc6ca.png">

**Comment by mccalluc** [comment]
Fixed
