### ISSUE TITLE
IMC image pyramids fail to load in Vitessce 0.2.2 in Safari and Chrome

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#977]
See https://portal.test.hubmapconsortium.org/browse/dataset/b81ca02627280283e791c82d8e3f8e09.

It loads fine in Firefox but in Safari and Chrome the process indicator never disappears and this error message appears in the console after a while:

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/1216518/89295549-2e7d6c00-d62f-11ea-839f-e4df5cdf130c.png">

**Comment by ilan-gold** [comment]
See https://github.com/hubmapconsortium/vitessce-image-viewer/issues/236
