### ISSUE TITLE
Error clicking on "clustering tree"

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#991]
From NIH feedback provider

On a different bug-report note: 
I generated an error, see screen shot below. It was obtained by clicking on the clustering tree on the right, I can’t describe exactly where I clicked, but it is repeatable.

![image](https://user-images.githubusercontent.com/21177919/89430330-a40b3a00-d70c-11ea-9bda-22e94bfc8529.png)

**Comment by ngehlenborg** [comment]
This was addressed in https://github.com/hubmapconsortium/vitessce/pull/699.
