### ISSUE TITLE
Display public collections

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#995]
Bill writes:
> The public/no-auth-token-needed collections methods are installed on TEST.  It looks like a small tweak will be needed for the portal to work with this-- the portal is now assuming that when you click into an individual collection that login is needed.  If the list is shown without login (no token) then clicking to an individual collection will not require login.
>
> public:
> https://portal.test.hubmapconsortium.org/browse/collection/1ff9aa1193ac810eb84234d9943114dc
> https://portal.test.hubmapconsortium.org/browse/collection/4cd83b9505c057999c9a05c4980b2e2a
>
> not public:
> https://portal.test.hubmapconsortium.org/browse/collection/72ca3a11112b9305fc713074014cffd6
> https://portal.test.hubmapconsortium.org/browse/collection/49764ab158ba1808d99b00712f3fd801

Need to clarify if this is urgent... if it's not, we should just wait for availability through Elasticsearch.

**Comment by ngehlenborg** [comment]
What is the small tweak that is needed?

**Comment by mccalluc** [comment]
`Collections` was removed from portal, for the time being. If/when it comes back, may be handled differently. Closing.
