### ISSUE TITLE
Validation Process Feedback, Issue for post-Release #1 consideration

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#996]
## Feedback

__Help Desk Issue Tracker URL__: n/a (email from NIH team member)

__Message__:
The following list of questions were ones identified as being important to discuss / follow up upon post Release #1 with the Portal team as well as data producing representatives.  I have logged this item to ensure we include this in coming discussions as well as incorporate any needed work into the backlog.

Based on these questions from the Beta testing phase:
#3 - Are you seeing expected results for pipeline processed data?  Are the outputs correct?
#4 - Do the visualizations correctly represent your data?
#6 - Is the metadata associated with the donors, samples, and assays correct?  Does it match your local records?

There are three items in there that can be potentially complicated and might need more specific guidance:
1)	How are they going to validate #3, expected results? What exactly would the steps be for different assay types?
2)	How do they check #4, visualizations? Can they compare their internally developed UMAPS to what is from the one in the portal? Can they compare CODEX segmentations or CODEX expression levels? Or the clustering results on the right, (BTW, some of the k-means have only 1 cell set in a cluster).
3)	How would they validate metadata?

Full text with some identifying information redacted:

"Hi All,

So I took a look at the things the TMCs are supposed to validate as found here: https://docs.google.com/document/d/1eXOD2Vfy5RAVYtv6UuGwRO8kisEL4xHD9nCJrl0s9OI/edit under ‘Beta’.

There are three items in there that can be potentially complicated and might need more specific guidance:

1)	How are they going to validate #3, expected results? What exactly would the steps be for different assay types?
2)	How do they check #4, visualizations? Can they compare their internally developed UMAPS to what is from the one in the portal? Can they compare CODEX segmentations or CODEX expression levels? Or the clustering results on the right, (BTW, some of the k-means have only 1 cell set in a cluster).
3)	How would they validate metadata?

I think we need to think about giving them some sort of summary tables that they can compare or something like say the top ten (or 50) genes/proteins identified. The spatial distribution will be trickier, of course. For metadata, there might be a way to hand people a csv file for the donor, sample, tissue, assay to validate with their internal data.

On the other hand there might be an entirely different meaning of validation of these things you have in mind.

Thanks for considering."

**Comment by mccalluc** [comment]
This is asking for clarification on the Beta testing process itself. The email instructions are already out, and we can not implement any features just for the beta testing now. I will summarize this and bring it to Nils attention.
